import { readFileSync, writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

/**
 * Array capacity, generated from the declarations.
 *
 * Review finding 30: the plan's total mixed a constant table into the
 * writable figure and omitted two writable arrays, so it represented neither
 * category. The table in `bootstrap-plan.md` is now generated by this test,
 * which reads the sizes out of the Lanternfly source, and it fails when the
 * checked-in figures no longer match.
 *
 * These are measurements of the current source. The front end still lacks
 * forms Candlemoth itself uses and the code generator is unwritten, so the
 * numbers will move.
 */

const SOURCES = [
  "candlemoth/tokenizer.lafy",
  "candlemoth/expression.lafy",
  "candlemoth/symbols.lafy",
  "candlemoth/statement.lafy",
  "candlemoth/runtime.lafy",
];

const PLAN = "docs/bootstrap-plan.md";
const BEGIN = "<!-- generated:capacity -->";
const END = "<!-- /generated -->";

const WIDTH: Record<string, number> = { u8: 1, u16: 2, i16: 2, boolean: 1 };

interface Array_ {
  readonly file: string;
  readonly name: string;
  readonly bytes: number;
  readonly writable: boolean;
}

function strip(text: string): string {
  return text
    .split("\n")
    .map((line) => line.replace(/\/\/.*$/, ""))
    .join("\n");
}

function collect(): Array_[] {
  const text = SOURCES.map((p) => strip(readFileSync(p, "utf8"))).join("\n");
  const scalars = new Map<string, number>();
  for (const m of text.matchAll(/^const (\w+) as u\d+ = (\d+)\s*$/gm)) {
    scalars.set(m[1], Number(m[2]));
  }

  const found: Array_[] = [];
  for (const source of SOURCES) {
    const body = strip(readFileSync(source, "utf8"));
    for (const m of body.matchAll(/^(var|const) (\w+) as (\w+)\[(\w+)\]/gm)) {
      const [, kind, name, type, count] = m;
      // An enum-typed array is one byte per element, like the u8 it is over.
      const width = WIDTH[type] ?? 1;
      const length = /^\d+$/.test(count) ? Number(count) : scalars.get(count);
      if (length === undefined) throw new Error(`${name}: unknown length ${count}`);
      found.push({
        file: source.replace("candlemoth/", ""),
        name,
        bytes: width * length,
        writable: kind === "var",
      });
    }
  }
  return found;
}

function render(arrays: readonly Array_[]): string {
  const writable = arrays.filter((a) => a.writable);
  const constant = arrays.filter((a) => !a.writable);
  const sum = (list: readonly Array_[]) => list.reduce((t, a) => t + a.bytes, 0);

  const rows = (list: readonly Array_[]) =>
    [...list]
      .sort((a, b) => b.bytes - a.bytes)
      .map((a) => `| \`${a.name}\` | ${a.file} | ${a.bytes} |`);

  return [
    "**Writable arrays** — RAM the loaded image allocates.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(writable),
    `| **Total** | | **${sum(writable)}** |`,
    "",
    "**Constant arrays** — bytes in the image itself.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(constant),
    `| **Total** | | **${sum(constant)}** |`,
  ].join("\n");
}

describe("array capacity", () => {
  const arrays = collect();

  it("keeps the two categories apart", () => {
    const writable = arrays.filter((a) => a.writable).reduce((t, a) => t + a.bytes, 0);
    const constant = arrays.filter((a) => !a.writable).reduce((t, a) => t + a.bytes, 0);
    // Finding 30: the earlier figure put the character-class table, which is
    // constant, into the writable total, and omitted the helper-address and
    // loop-stack arrays, which are writable.
    const names = arrays.map((a) => a.name);
    expect(names).toContain("characterClass");
    expect(names).toContain("helperAddress");
    expect(names).toContain("loopBreakLabel");
    expect(arrays.find((a) => a.name === "characterClass")!.writable).toBe(false);
    expect(arrays.find((a) => a.name === "helperAddress")!.writable).toBe(true);

    expect(writable).toBeGreaterThan(0);
    expect(constant).toBeGreaterThan(0);
    console.log(`writable ${writable} bytes, constant ${constant} bytes`);
  });

  it("matches the table in the plan", () => {
    const existing = readFileSync(PLAN, "utf8");
    const start = existing.indexOf(BEGIN);
    expect(start, `${PLAN} has no ${BEGIN} marker`).toBeGreaterThanOrEqual(0);
    const from = start + BEGIN.length;
    const to = existing.indexOf(END, from);
    const rendered = `${existing.slice(0, from)}\n${render(arrays)}\n${existing.slice(to)}`;

    if (process.env.UPDATE_CAPACITY === "1") {
      writeFileSync(PLAN, rendered, "utf8");
      console.log(`wrote ${PLAN}`);
      return;
    }
    expect(existing).toBe(rendered);
  });
});
