import { readFileSync, writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

/**
 * Array capacity, generated from the declarations.
 *
 * Review finding 30: the plan's total mixed a constant table into the
 * writable figure and omitted two writable arrays, so it represented neither
 * category. The table in `bootstrap-plan.md` is now generated by this test,
 * which reads the sizes out of the Lanternfly source, and it fails when the
 * checked-in figures no longer match.
 *
 * These are measurements of the current source. The front end still lacks
 * forms Candlemoth itself uses and the code generator is unwritten, so the
 * numbers will move.
 */

const SOURCES = [
  "candlemoth/tokenizer.lafy",
  "candlemoth/expression.lafy",
  "candlemoth/symbols.lafy",
  "candlemoth/statement.lafy",
  "candlemoth/runtime.lafy",
];

const PLAN = "docs/bootstrap-plan.md";
const BEGIN = "<!-- generated:capacity -->";
const END = "<!-- /generated -->";

const WIDTH: Record<string, number> = { u8: 1, u16: 2, i16: 2, boolean: 1 };

export class CapacityError extends Error {}

/**
 * Element width, from the type's own declaration.
 *
 * Review finding 32: this was `WIDTH[type] ?? 1`, which counted the u8-backed
 * enum arrays correctly and gave every unknown type one byte as well. A record
 * array, a named scalar type or a misspelled type would have entered the table
 * with a plausible wrong size, and the stale-document check would have stayed
 * green while the report understated memory.
 *
 * An enum's width now comes from its stated representation. Anything else is
 * an error, because a reader that cannot compute a layout should say so rather
 * than guess at it.
 */
function widthOf(type: string, enums: ReadonlyMap<string, string>): number {
  const scalar = WIDTH[type];
  if (scalar !== undefined) return scalar;

  const representation = enums.get(type);
  if (representation === undefined) {
    throw new CapacityError(
      `array element type "${type}" is neither a level-0 scalar nor a declared enum; ` +
        `the capacity reader has no layout for it`,
    );
  }
  const width = WIDTH[representation];
  if (width === undefined) {
    throw new CapacityError(`enum ${type} is declared over "${representation}", which has no width`);
  }
  return width;
}

/** Every enum in the source, with the type it is declared over. */
export function enumRepresentations(text: string): ReadonlyMap<string, string> {
  const enums = new Map<string, string>();
  for (const m of text.matchAll(/^enum (\w+) as (\w+)\s*$/gm)) {
    enums.set(m[1], m[2]);
  }
  return enums;
}

interface Array_ {
  readonly file: string;
  readonly name: string;
  readonly bytes: number;
  readonly writable: boolean;
}

function strip(text: string): string {
  return text
    .split("\n")
    .map((line) => line.replace(/\/\/.*$/, ""))
    .join("\n");
}

export function collectFrom(sources: readonly { path: string; text: string }[]): Array_[] {
  const all = sources.map((s) => strip(s.text)).join("\n");
  const scalars = new Map<string, number>();
  for (const m of all.matchAll(/^const (\w+) as u\d+ = (\d+)\s*$/gm)) {
    scalars.set(m[1], Number(m[2]));
  }
  const enums = enumRepresentations(all);

  const found: Array_[] = [];
  for (const source of sources) {
    const body = strip(source.text);
    for (const m of body.matchAll(/^(var|const) (\w+) as (\w+)\[(\w+)\]/gm)) {
      const [, kind, name, type, count] = m;
      const width = widthOf(type, enums);
      const length = /^\d+$/.test(count) ? Number(count) : scalars.get(count);
      if (length === undefined) {
        throw new CapacityError(`${name}: array length "${count}" is not a known constant`);
      }
      found.push({
        file: source.path.replace("candlemoth/", ""),
        name,
        bytes: width * length,
        writable: kind === "var",
      });
    }
  }
  return found;
}

function collect(): Array_[] {
  return collectFrom(SOURCES.map((path) => ({ path, text: readFileSync(path, "utf8") })));
}

function render(arrays: readonly Array_[]): string {
  const writable = arrays.filter((a) => a.writable);
  const constant = arrays.filter((a) => !a.writable);
  const sum = (list: readonly Array_[]) => list.reduce((t, a) => t + a.bytes, 0);

  const rows = (list: readonly Array_[]) =>
    [...list]
      .sort((a, b) => b.bytes - a.bytes)
      .map((a) => `| \`${a.name}\` | ${a.file} | ${a.bytes} |`);

  return [
    "**Writable arrays** — RAM the loaded image allocates.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(writable),
    `| **Total** | | **${sum(writable)}** |`,
    "",
    "**Constant arrays** — bytes in the image itself.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(constant),
    `| **Total** | | **${sum(constant)}** |`,
  ].join("\n");
}

describe("array capacity", () => {
  const arrays = collect();

  it("keeps the two categories apart", () => {
    const writable = arrays.filter((a) => a.writable).reduce((t, a) => t + a.bytes, 0);
    const constant = arrays.filter((a) => !a.writable).reduce((t, a) => t + a.bytes, 0);
    // Finding 30: the earlier figure put the character-class table, which is
    // constant, into the writable total, and omitted the helper-address and
    // loop-stack arrays, which are writable.
    const names = arrays.map((a) => a.name);
    expect(names).toContain("characterClass");
    expect(names).toContain("helperAddress");
    expect(names).toContain("loopBreakLabel");
    expect(arrays.find((a) => a.name === "characterClass")!.writable).toBe(false);
    expect(arrays.find((a) => a.name === "helperAddress")!.writable).toBe(true);

    expect(writable).toBeGreaterThan(0);
    expect(constant).toBeGreaterThan(0);
    console.log(`writable ${writable} bytes, constant ${constant} bytes`);
  });

  it("takes an enum's width from its declared representation", () => {
    // Every enum in the source is over u8 today, so this passes either way.
    // The fixtures below are what distinguish a derived width from a default.
    const enums = enumRepresentations(
      SOURCES.map((p) => readFileSync(p, "utf8")).join("\n"),
    );
    expect(enums.get("SymbolKind")).toBe("u8");
    expect(enums.get("TypeKind")).toBe("u8");

    const wide = collectFrom([
      {
        path: "fixture.lafy",
        text: "enum Wide as u16\n    first\nend\n\nvar table as Wide[4]\n",
      },
    ]);
    expect(wide).toHaveLength(1);
    expect(wide[0].bytes).toBe(8);
  });

  it("reports an element type it has no layout for", () => {
    // Review finding 32: a record array counted as one byte per element.
    expect(() =>
      collectFrom([
        {
          path: "fixture.lafy",
          text: "record Point\n    x as u16\n    y as u16\nend\n\nvar path as Point[64]\n",
        },
      ]),
    ).toThrow(CapacityError);

    // A misspelled scalar is the same failure and not a silent one byte.
    expect(() =>
      collectFrom([{ path: "fixture.lafy", text: "var table as u9[16]\n" }]),
    ).toThrow(/neither a level-0 scalar nor a declared enum/);
  });

  it("reports an array length it cannot resolve", () => {
    expect(() =>
      collectFrom([{ path: "fixture.lafy", text: "var table as u8[unknownLimit]\n" }]),
    ).toThrow(/not a known constant/);
  });

  it("matches the table in the plan", () => {
    const existing = readFileSync(PLAN, "utf8");
    const start = existing.indexOf(BEGIN);
    expect(start, `${PLAN} has no ${BEGIN} marker`).toBeGreaterThanOrEqual(0);
    const from = start + BEGIN.length;
    const to = existing.indexOf(END, from);
    const rendered = `${existing.slice(0, from)}\n${render(arrays)}\n${existing.slice(to)}`;

    if (process.env.UPDATE_CAPACITY === "1") {
      writeFileSync(PLAN, rendered, "utf8");
      console.log(`wrote ${PLAN}`);
      return;
    }
    expect(existing).toBe(rendered);
  });
});
