import { readFileSync, readdirSync, writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

/**
 * Array capacity, generated from the declarations.
 *
 * Review finding 30: the plan's total mixed a constant table into the
 * writable figure and omitted two writable arrays, so it represented neither
 * category. The table in `bootstrap-plan.md` is now generated by this test,
 * which reads the sizes out of the Lanternfly source, and it fails when the
 * checked-in figures no longer match.
 *
 * These are measurements of the current source. The front end still lacks
 * forms Candlemoth itself uses and the code generator is unwritten, so the
 * numbers will move.
 */

const SOURCES = [
  "candlemoth/tokenizer.lafy",
  "candlemoth/expression.lafy",
  "candlemoth/symbols.lafy",
  "candlemoth/statement.lafy",
  "candlemoth/runtime.lafy",
];

const PLAN = "docs/bootstrap-plan.md";
const BEGIN = "<!-- generated:capacity -->";
const END = "<!-- /generated -->";

const WIDTH: Record<string, number> = { u8: 1, u16: 2, i16: 2, boolean: 1 };

export class CapacityError extends Error {}

/**
 * Element width, from the type's own declaration.
 *
 * Review finding 32: this was `WIDTH[type] ?? 1`, which counted the u8-backed
 * enum arrays correctly and gave every unknown type one byte as well. A record
 * array, a named scalar type or a misspelled type would have entered the table
 * with a plausible wrong size, and the stale-document check would have stayed
 * green while the report understated memory.
 *
 * An enum's width now comes from its stated representation. Anything else is
 * an error, because a reader that cannot compute a layout should say so rather
 * than guess at it.
 */
function widthOf(type: string, enums: ReadonlyMap<string, string>): number {
  const scalar = WIDTH[type];
  if (scalar !== undefined) return scalar;

  const representation = enums.get(type);
  if (representation === undefined) {
    throw new CapacityError(
      `array element type "${type}" is neither a level-0 scalar nor a declared enum; ` +
        `the capacity reader has no layout for it`,
    );
  }
  const width = WIDTH[representation];
  if (width === undefined) {
    throw new CapacityError(`enum ${type} is declared over "${representation}", which has no width`);
  }
  return width;
}

/** Every enum in the source, with the type it is declared over. */
export function enumRepresentations(text: string): ReadonlyMap<string, string> {
  const enums = new Map<string, string>();
  for (const m of text.matchAll(/^enum (\w+) as (\w+)\s*$/gm)) {
    enums.set(m[1], m[2]);
  }
  return enums;
}

interface Array_ {
  readonly file: string;
  readonly name: string;
  readonly bytes: number;
  readonly writable: boolean;
}

function strip(text: string): string {
  return text
    .split("\n")
    .map((line) => line.replace(/\/\/.*$/, ""))
    .join("\n");
}

export function collectFrom(sources: readonly { path: string; text: string }[]): Array_[] {
  const all = sources.map((s) => strip(s.text)).join("\n");
  const scalars = new Map<string, number>();
  for (const m of all.matchAll(/^const (\w+) as u\d+ = (\d+)\s*$/gm)) {
    scalars.set(m[1], Number(m[2]));
  }
  const enums = enumRepresentations(all);

  const found: Array_[] = [];
  for (const source of sources) {
    const body = strip(source.text);
    for (const m of body.matchAll(/^(var|const) (\w+) as (\w+)\[(\w+)\]/gm)) {
      const [, kind, name, type, count] = m;
      const width = widthOf(type, enums);
      const length = /^\d+$/.test(count) ? Number(count) : scalars.get(count);
      if (length === undefined) {
        throw new CapacityError(`${name}: array length "${count}" is not a known constant`);
      }
      found.push({
        file: source.path.replace("candlemoth/", ""),
        name,
        bytes: width * length,
        writable: kind === "var",
      });
    }
  }
  return found;
}

function collect(): Array_[] {
  return collectFrom(SOURCES.map((path) => ({ path, text: readFileSync(path, "utf8") })));
}

function render(arrays: readonly Array_[]): string {
  const writable = arrays.filter((a) => a.writable);
  const constant = arrays.filter((a) => !a.writable);
  const sum = (list: readonly Array_[]) => list.reduce((t, a) => t + a.bytes, 0);

  const rows = (list: readonly Array_[]) =>
    [...list]
      .sort((a, b) => b.bytes - a.bytes)
      .map((a) => `| \`${a.name}\` | ${a.file} | ${a.bytes} |`);

  return [
    "**Writable arrays** — RAM the loaded image allocates.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(writable),
    `| **Total** | | **${sum(writable)}** |`,
    "",
    "**Constant arrays** — bytes in the image itself.",
    "",
    "| Array | File | Bytes |",
    "| --- | --- | --- |",
    ...rows(constant),
    `| **Total** | | **${sum(constant)}** |`,
  ].join("\n");
}

describe("array capacity", () => {
  const arrays = collect();

  it("keeps the two categories apart", () => {
    const writable = arrays.filter((a) => a.writable).reduce((t, a) => t + a.bytes, 0);
    const constant = arrays.filter((a) => !a.writable).reduce((t, a) => t + a.bytes, 0);
    // Finding 30: the earlier figure put the character-class table, which is
    // constant, into the writable total, and omitted the helper-address and
    // loop-stack arrays, which are writable.
    const names = arrays.map((a) => a.name);
    expect(names).toContain("characterClass");
    expect(names).toContain("helperAddress");
    expect(names).toContain("loopBreakLabel");
    expect(arrays.find((a) => a.name === "characterClass")!.writable).toBe(false);
    expect(arrays.find((a) => a.name === "helperAddress")!.writable).toBe(true);

    expect(writable).toBeGreaterThan(0);
    expect(constant).toBeGreaterThan(0);
    console.log(`writable ${writable} bytes, constant ${constant} bytes`);
  });

  it("takes an enum's width from its declared representation", () => {
    // Every enum in the source is over u8 today, so this passes either way.
    // The fixtures below are what distinguish a derived width from a default.
    const enums = enumRepresentations(
      SOURCES.map((p) => readFileSync(p, "utf8")).join("\n"),
    );
    expect(enums.get("SymbolKind")).toBe("u8");
    expect(enums.get("TypeKind")).toBe("u8");

    const wide = collectFrom([
      {
        path: "fixture.lafy",
        text: "enum Wide as u16\n    first\nend\n\nvar table as Wide[4]\n",
      },
    ]);
    expect(wide).toHaveLength(1);
    expect(wide[0].bytes).toBe(8);
  });

  it("reports an element type it has no layout for", () => {
    // Review finding 32: a record array counted as one byte per element.
    expect(() =>
      collectFrom([
        {
          path: "fixture.lafy",
          text: "record Point\n    x as u16\n    y as u16\nend\n\nvar path as Point[64]\n",
        },
      ]),
    ).toThrow(CapacityError);

    // A misspelled scalar is the same failure and not a silent one byte.
    expect(() =>
      collectFrom([{ path: "fixture.lafy", text: "var table as u9[16]\n" }]),
    ).toThrow(/neither a level-0 scalar nor a declared enum/);
  });

  it("reports an array length it cannot resolve", () => {
    expect(() =>
      collectFrom([{ path: "fixture.lafy", text: "var table as u8[unknownLimit]\n" }]),
    ).toThrow(/not a known constant/);
  });

  it("matches the table in the plan", () => {
    const existing = readFileSync(PLAN, "utf8");
    const start = existing.indexOf(BEGIN);
    expect(start, `${PLAN} has no ${BEGIN} marker`).toBeGreaterThanOrEqual(0);
    const from = start + BEGIN.length;
    const to = existing.indexOf(END, from);
    const rendered = `${existing.slice(0, from)}\n${render(arrays)}\n${existing.slice(to)}`;

    if (process.env.UPDATE_CAPACITY === "1") {
      writeFileSync(PLAN, rendered, "utf8");
      console.log(`wrote ${PLAN}`);
      return;
    }
    expect(existing).toBe(rendered);
  });
});

/**
 * The call graph, measured against the limits declared for it.
 *
 * The first version of these limits stopped at 128 routines when the source
 * already had 144, so the compiler would have faulted before finishing its own
 * text. The representation was also chosen from an argument rather than a
 * measurement — a bit matrix, sized on the assumption that an edge costs four
 * bytes when a routine ordinal fits one.
 *
 * These figures decide the representation, so they are generated rather than
 * quoted.
 */
describe("the call graph", () => {
  // Every Candlemoth source file, including the generated runtime. An earlier
  // version measured the four front-end files and reported the figure as the
  // whole graph; the runtime contributes a routine and an edge of its own.
  const SOURCE = SOURCES;

  function graph() {
    const text = SOURCE.map((p) => strip(readFileSync(p, "utf8"))).join("\n");
    const bodies = [...text.matchAll(/^sub (\w+)/gm)].map((m) => m[1]);
    const defined = new Set(bodies);
    const forwards = new Set([...text.matchAll(/^forward sub (\w+)/gm)].map((m) => m[1]));

    const edges = new Set<string>();
    let sites = 0;
    let current: string | undefined;
    for (const line of text.split("\n")) {
      const open = /^sub (\w+)/.exec(line);
      if (open) {
        current = open[1];
        continue;
      }
      if (/^end\s*$/.test(line)) {
        current = undefined;
        continue;
      }
      if (current === undefined) continue;
      for (const call of line.matchAll(/\b(\w+)\s*\(/g)) {
        if (!defined.has(call[1])) continue;
        sites += 1;
        edges.add(`${current}->${call[1]}`);
      }
    }
    return { routines: bodies.length, forwards: forwards.size, sites, edges: edges.size };
  }

  /** A limit declared in the Lanternfly source. */
  function limit(file: string, name: string): number {
    const text = readFileSync(file, "utf8");
    const found = new RegExp(`^const ${name} as u\\d+ = (\\d+)`, "m").exec(text);
    expect(found, `${name} is not declared in ${file}`).not.toBeNull();
    return Number(found![1]);
  }

  const measured = graph();
  const STATEMENT = "candlemoth/statement.lafy";

  it("measures every Candlemoth file, not only the front end", () => {
    // Against the directory, not against itself. The earlier version compared
    // `SOURCE` with `SOURCES` when one was assigned from the other, so it held
    // whatever the list happened to contain.
    const onDisk = readdirSync("candlemoth")
      .filter((name) => name.endsWith(".lafy"))
      .map((name) => `candlemoth/${name}`)
      .sort();
    expect([...SOURCE].sort()).toEqual(onDisk);
  });

  it("reports what the source actually contains", () => {
    const routineLimit = limit(STATEMENT, "routineLimit");
    const edgeLimit = limit(STATEMENT, "callSiteLimit");
    console.log(
      [
        "call graph, measured",
        `  routine bodies        ${measured.routines}   limit ${routineLimit}`,
        `  forward declarations  ${measured.forwards}`,
        `  call sites            ${measured.sites}   limit ${edgeLimit}`,
        `  files                 ${SOURCE.length}`,
        `  unique edges          ${measured.edges}`,
        "",
        "  representations for this graph:",
        `    edge list, ${measured.sites} sites x 2 u8      ${measured.sites * 2} bytes`,
        `    bit matrix, ${measured.routines} x ${Math.ceil(measured.routines / 8)}         ${
          measured.routines * Math.ceil(measured.routines / 8)
        } bytes`,
      ].join("\n"),
    );
    expect(measured.routines).toBeGreaterThan(0);
  });

  it("holds every routine the source declares", () => {
    // This failed when the limit was 128 and the source had 144.
    expect(measured.routines).toBeLessThanOrEqual(limit(STATEMENT, "routineLimit"));
  });

  it("holds every call site the source makes", () => {
    expect(measured.sites).toBeLessThanOrEqual(limit(STATEMENT, "callSiteLimit"));
  });

  it("a call-site list is smaller than a matrix plus a redirection list", () => {
    // The honest comparison. A matrix carries edges and nothing else, so a
    // separate list of operand offsets is needed to redirect call sites once
    // the components are known — and that list already carries the callee, so
    // the matrix is pure overhead on top of it.
    const siteList = measured.sites * 4; // offset, caller, callee
    const matrixPlus = measured.routines * Math.ceil(measured.routines / 8) + measured.sites * 3;
    expect(siteList).toBeLessThan(matrixPlus);
    console.log(
      `call-site list ${siteList} bytes against matrix-plus-redirection ${matrixPlus}`,
    );
  });

  it("a routine ordinal fits a byte, which is why an edge is two", () => {
    expect(limit(STATEMENT, "routineLimit")).toBeLessThan(256);
  });
});
