/**
 * Re-exports the addressing step DSL symbols consumed by `emit.ts`.
 * Keeps `emit.ts` focused on orchestration rather than a long `steps.js` import list.
 */

export {
  EA_GLOB_CONST,
  EA_GLOB_REG,
  EA_GLOB_RP,
  EA_FVAR_CONST,
  EA_FVAR_REG,
  EA_FVAR_RP,
  EA_GLOB_GLOB,
  EA_FVAR_GLOB,
  EA_GLOB_FVAR,
  EA_FVAR_FVAR,
  EAW_GLOB_CONST,
  EAW_GLOB_REG,
  EAW_GLOB_RP,
  EAW_FVAR_CONST,
  EAW_FVAR_REG,
  EAW_FVAR_RP,
  EAW_GLOB_GLOB,
  EAW_FVAR_GLOB,
  EAW_GLOB_FVAR,
  EAW_FVAR_FVAR,
  LOAD_BASE_GLOB,
  LOAD_BASE_FVAR,
  LOAD_RP_EA,
  LOAD_RP_FVAR,
  LOAD_RP_GLOB,
  STORE_RP_EA,
  STORE_RP_FVAR,
  STORE_RP_GLOB,
  CALC_EA,
  CALC_EA_2,
  TEMPLATE_L_ABC,
  TEMPLATE_LW_HL,
  TEMPLATE_L_HL,
  TEMPLATE_L_DE,
  TEMPLATE_LW_BC,
  TEMPLATE_LW_DE,
  TEMPLATE_SW_DEBC,
  TEMPLATE_SW_HL,
  TEMPLATE_S_ANY,
  TEMPLATE_S_HL,
  type StepPipeline,
} from './steps.js';
