#!/usr/bin/env bash
# Concatenate the learning chapters into a single BOOK.md.
# Usage: scripts/build-book.sh
#
# Source of truth: the individual chapter .md files.
# BOOK.md is a derived artifact — do not edit it directly.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LEARNING="$ROOT/learning"
OUT="$LEARNING/BOOK.md"

# Chapter files in reading order (no READMEs).
PART1=(
  part1/01-the-computer.md
  part1/02-machine-code.md
  part1/03-assembly-language.md
  part1/04-flags-comparisons-jumps.md
  part1/05-counting-loops-and-djnz.md
  part1/06-data-tables-and-indexed-access.md
  part1/07-stack-and-subroutines.md
  part1/08-io-and-ports.md
  part1/09-a-phase-a-program.md
  part1/10-functions-and-the-ix-frame.md
  part1/11-structured-control-flow.md
  part1/12-typed-assignment.md
  part1/13-op-macros-and-pseudo-opcodes.md
)

PART2=(
  part2/00-introduction.md
  part2/01-foundations.md
  part2/02-arrays-and-loops.md
  part2/03-strings.md
  part2/04-bit-patterns.md
  part2/05-records.md
  part2/06-recursion.md
  part2/07-composition.md
  part2/08-pointer-structures.md
  part2/09-gaps-and-futures.md
)

APPENDICES=(
  appendices/01-numbers-notation-and-ascii.md
  appendices/02-registers-flags-and-conditions.md
  appendices/03-addressing-prefixes-and-instruction-forms.md
  appendices/04-classic-z80-instruction-support.md
)

# Strip nav header/footer lines and surrounding horizontal rules.
# Nav lines contain "[Part 1](README.md)" or "[Part 2](README.md)".
strip_nav() {
  sed -E '
    /\[Part [12]\]\(.*README\.md\)/d
  '
}

# Remove leading blank lines, trailing blank lines, and trailing "---".
trim_chapter() {
  awk '
    # Buffer all lines; strip leading blanks, trailing blanks, and trailing ---
    { lines[NR] = $0 }
    END {
      # Find first non-blank line
      start = 1
      while (start <= NR && lines[start] ~ /^[[:space:]]*$/) start++
      # Find last non-blank, non-"---" line
      end = NR
      while (end >= start && (lines[end] ~ /^[[:space:]]*$/ || lines[end] ~ /^---[[:space:]]*$/)) end--
      for (i = start; i <= end; i++) print lines[i]
    }
  '
}

{
  cat <<'HEADER'
# Learning ZAX

This file is generated from the chapter files under `learning/`.
To regenerate: `bash scripts/build-book.sh`

Do not edit this file directly — edit the chapter sources instead.
HEADER

  # Part 1
  printf '\n---\n\n# Part 1 — Learn Z80 Programming in ZAX\n\n'

  for f in "${PART1[@]}"; do
    content=$(cat "$LEARNING/$f" | strip_nav | trim_chapter)
    printf '%s\n\n' "$content"
  done

  # Part 2
  printf '\n---\n\n# Part 2 — Algorithms and Data Structures in ZAX\n\n'

  for f in "${PART2[@]}"; do
    content=$(cat "$LEARNING/$f" | strip_nav | trim_chapter)
    printf '%s\n\n' "$content"
  done

  # Appendices
  printf '\n---\n\n# Appendices — Global Reference\n\n'

  for f in "${APPENDICES[@]}"; do
    content=$(cat "$LEARNING/$f" | strip_nav | trim_chapter)
    printf '%s\n\n' "$content"
  done

} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
