; ZAX lowered ASM80 output

ORG $2000
glob_w:
DW $BEEF

ORG $0100
; ZAX: func touch_scalar_word_glob begin
touch_scalar_word_glob:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
DB $2A, $00, $20
DB $22, $00, $20
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func touch_scalar_word_glob end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
DB $CD, $00, $01
__zax_epilogue_1:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $2002
__zax_startup:
DB $21, $4A, $20, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $54, $20, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $19, $01
DB $01, $00, $00, $20, $00, $00, $02, $00, $00, $00, $EF, $BE
