; ZAX lowered ASM80 output

ORG $2000
dummy:
DW $00

ORG $0100
; ZAX: func touch_scalar_word_frame begin
touch_scalar_word_frame:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
ld e, (IX+$04)
ld d, (IX+$05)
ld (IX+$04), e
ld (IX+$05), d
ex de, hl
__zax_epilogue_0:
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func touch_scalar_word_frame end
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
ld hl, $1234
push hl
DB $CD, $00, $01
inc sp
inc sp
__zax_epilogue_1:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $2002
__zax_startup:
DB $21, $4A, $20, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $54, $20, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $20, $01
DB $01, $00, $00, $20, $00, $00, $02, $00, $00, $00, $00, $00
