; ZAX lowered ASM80 output

ORG $00
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
DB $CA, $13, $00
nop
DB $C3, $14, $00
__zax_if_else_1:
nop
__zax_if_end_2:
__zax_while_cond_3:
DB $CA, $1B, $00
nop
DB $C3, $14, $00
__zax_while_end_4:
__zax_repeat_body_5:
nop
__zax_repeat_cond_6:
DB $C2, $1B, $00
__zax_repeat_end_7:
DB $C3, $2A, $00
__zax_case_10:
nop
DB $C3, $3C, $00
__zax_select_else_11:
nop
DB $C3, $3C, $00
__zax_select_dispatch_8:
push hl
ld h, $00
ld l, a
DB $7D
DB $FE, $00
DB $C2, $38, $00
pop hl
DB $C3, $22, $00
__zax_select_next_12:
pop hl
DB $C3, $26, $00
__zax_select_end_9:
__zax_epilogue_0:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end
