; ZAX lowered ASM80 output

ORG $1000
idx:
DB $00
idxw:
DW $00
arr:
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
grid:
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00
DB $00

ORG $00
; ZAX: func main begin
main:
push ix
ld ix, $00
add ix, sp
push af
push bc
push de
push hl
DB $3A, $00, $10
ld h, $00
ld l, a
push hl
pop hl
push hl
DB $21, $03, $10
pop de
add hl, de
push hl
pop hl
DB $7E
push de
push hl
DB $11, $03, $10
DB $2A, $01, $10
add hl, de
ld a, (HL)
pop hl
pop de
push de
push hl
DB $11, $03, $10
add hl, de
ld a, (HL)
pop hl
pop de
DB $7E
ld l, a
ld h, $00
push hl
DB $21, $03, $10
pop de
add hl, de
push hl
pop hl
DB $7E
DB $3A, $00, $10
ld h, $00
ld l, a
push hl
pop hl
add hl, hl
add hl, hl
add hl, hl
push hl
DB $21, $13, $10
pop de
add hl, de
push hl
pop hl
DB $7E
__zax_epilogue_0:
pop hl
pop de
pop bc
pop af
ld sp, ix
pop ix
ret
; ZAX: func main end

ORG $1033
__zax_startup:
DB $21, $7B, $10, $4E, $23, $46, $23, $78, $B1, $28, $1B, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $E5, $21, $97, $10, $09, $E3, $4E, $23, $46, $23, $E3, $ED, $B0, $E1, $C1, $0B, $18, $E1, $4E, $23, $46, $23, $78, $B1, $28, $17, $C5, $5E, $23, $56, $23, $4E, $23, $46, $23, $78, $B1, $28, $06, $AF, $12, $13, $0B, $18, $F6, $C1, $0B, $18, $E5, $C3, $00, $00
DB $04, $00, $00, $10, $00, $00, $01, $00, $01, $10, $01, $00, $02, $00, $03, $10, $03, $00, $10, $00, $13, $10, $13, $00, $20, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
