CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_ILEND
JP   Z,TK_UCHAR
CP   $27
JP   Z,TK_ICHAR
CP   $5C
JR   Z,.SCESCAPE
CP   $20
JP   C,TK_IB
CP   $7F
JP   NC,TK_IB
LD   (TK_SVAL),A
JR   .SCCLOSE
.SCESCAPE:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CP   $78
JR   Z,.SCHEX
CALL TK_DESCA
JP   C,TK_IESCA
LD   (TK_SVAL),A
JR   .SCCLOSE
.SCHEX:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_HDIGI
JP   NC,TK_IESCA
ADD  A,A
ADD  A,A
ADD  A,A
ADD  A,A
LD   (TK_SVAL),A
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_HDIGI
JP   NC,TK_IESCA
LD   HL,TK_SVAL
OR   (HL)
LD   (TK_SVAL),A
.SCCLOSE:
CALL TK_STAKE
JP   C,TK_UCHAR
INC  B
CALL TK_ILEND
JP   Z,TK_UCHAR
CP   $27
JP   NZ,TK_ICHAR
JP   TK_FNLEN
TK_RCEND:
;@ROUTINE OUT A,B,HL
TK_LLEXE:
LD   HL,(TK_REC+TK_LOFF)
LD   A,(TK_REC+TK_LOFF1)
LD   B,A
RET
TK_IBEG:
TK_PTABL:
DB $2C,TK_COMMA
DB $3A,TK_COLON
DB $28,TK_LPARE
DB $29,TK_RPARE
DB $2B,TK_PLUS
DB $2D,TK_MINUS
DB $2A,TK_STAR
DB $2F,TK_SLASH
DB $26,TK_AMPER
DB $5E,TK_CARET
DB $7C,TK_PIPE
DB $7E,TK_TILDE
DB $27,TK_APOST
TK_PEND:
TK_PCNT EQU (TK_PEND-TK_PTABL)/2
TK_ETABL:
DB $30,0,$6E,$0A,$72,$0D,$74,$09,$27,$27,$22,$22,$5C,$5C
TK_ECNT EQU 7
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HL,ZERO,SIGN,PARITY,HALFCARRY
TK_DESCA:
LD   HL,TK_ETABL
LD   C,TK_ECNT
.DELOOP:
CP   (HL)
JR   Z,.DEFOUND
INC  HL
INC  HL
DEC  C
JR   NZ,.DELOOP
SCF
RET
.DEFOUND:
INC  HL
LD   A,(HL)
RET
;@ROUTINE IN A OUT A,ZERO CLOBBERS CARRY,SIGN,PARITY,HALFCARRY
TK_ILEND:
CP   $0A
RET  Z
CP   $0D
RET
TK_IEND:
TK_CEND:
TK_WBEG:
TK_SRCBA: DW 0
TK_SCURS: DW 0
TK_SEND: DW 0
TK_SOSTA: DW 0
TK_SPART: DB 0
TK_LHTOK: DB 0
TK_EPEND: DB 0
TK_SPTR: DW 0
TK_BCNT: DB 0
TK_PREV: DB 0
TK_SOFF1: DW 0
TK_SLEN: DB 0
TK_SVAL: DW 0
TK_DSEEN: DB 0
TK_ESTAT EQU TK_SLEN
TK_EPART EQU TK_SVAL
TK_EOFF EQU TK_SVAL+1
TK_REC: DS TK_RECB
TK_TBUF: DS 256
TK_WEND:
EX_CBEG:
EX_RESOL EQU 0
EX_UNRES EQU 1
EX_SLEXI EQU 2
EX_SEPRI EQU 3
EX_SERIG EQU 4
EX_SDZER EQU 5
EX_SRANG EQU 6
EX_SFFOR EQU 7
EX_SCAP EQU 8
EX_SSYM EQU 9
EX_SINT EQU 10
EX_OPOR EQU 0
EX_OPXOR EQU 1
EX_OPAND EQU 2
EX_OLEFT EQU 3
EX_ORIGH EQU 4
EX_OPADD EQU 5
EX_OSUBT EQU 6
EX_OMULT EQU 7
EX_ODIVI EQU 8
EX_OREMA EQU 9
EX_VALB EQU 10
EX_VCAP EQU 16
EX_OPERB EQU 4
EX_OCAP EQU 16
EX_MLPAR EQU $0F
EX_UPLUS EQU $7A
EX_UMINU EQU $7B
EX_UTILD EQU $72
EX_ULO EQU $7D
EX_UHI EQU $7E
EX_FPLAI EQU 1
EX_FLO EQU 2
EX_FHI EQU 3
;@ROUTINE IN BC OUT A,HL,IX,CARRY CLOBBERS BC,DE,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_PARSE:
LD   A,1
LD   (EX_PSYM),A
JR   EX_PCOMM
;@ROUTINE IN BC OUT A,HL,IX,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO,BC,DE,IY
EX_PDEFR:
XOR  A
LD   (EX_PSYM),A
EX_PCOMM:
LD   (EX_CADR),BC
XOR  A
LD   (EX_VDEPT),A
LD   (EX_ODEPT),A
LD   (EX_PDEPT),A
INC  A
LD   (EX_EOP),A
.PLOOP:
LD   A,(EX_EOP)
OR   A
JR   Z,.POPER
CALL EX_POP
RET  C
JR   .PLOOP
.POPER:
CALL EX_POPER
RET  C
JR   NZ,.PLOOP
CALL EX_FSTAC
RET  C
LD   A,(EX_RUNRE)
OR   A
JR   NZ,.FUNRESOL
CALL EX_REQW
RET  C
LD   HL,(EX_RVAL)
XOR  A
RET
.FUNRESOL:
CALL EX_RADDE
RET  C
LD   A,(EX_PSYM)
OR   A
JR   Z,.FINDEFR
LD   HL,EX_RKEY
CALL SY_REF
JR   C,EX_SFAIL
.RUNRESOL:
LD   HL,(EX_RVAL)
LD   A,EX_UNRES
OR   A
RET
.FINDEFR:
LD   IX,EX_RKEY
JR   .RUNRESOL
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_SFAIL:
LD   (EX_SSTAT),A
LD   A,EX_SSYM
JP   EX_FSYM
;@ROUTINE IN A,IX,HL,DE,B OUT A,CARRY CLOBBERS C,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
EX_QUEUE:
LD   C,L
JP   SY_ADD
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
EX_CFUNC:
LD   A,(TK_REC+TK_LOFF1)
CP   3
JR   Z,.CLSLO
CP   4
JR   NZ,.NFUNCTIO
LD   C,EX_UHI
LD   DE,$336F
JR   .CFPACK
.CLSLO:
LD   C,EX_ULO
LD   DE,$4D6F
.CFPACK:
PUSH DE
PUSH BC
LD   HL,(TK_REC+TK_LOFF)
LD   B,A
LD   DE,EX_RKEY
CALL EN_R40PK
POP  BC
POP  DE
JR   C,.NFUNCTIO
LD   HL,(EX_RKEY)
OR   A
SBC  HL,DE
JR   NZ,.NFUNCTIO
LD   HL,(TK_SCURS)
LD   DE,(TK_SEND)
.FLOOKAHE:
LD   A,H
CP   D
JR   NZ,.FLB
LD   A,L
CP   E
JR   Z,.NFUNCTIO
.FLB:
PUSH DE
PUSH HL
LD   A,(TK_SPART)
CALL TK_SREAD
POP  HL
POP  DE
CP   $20
JR   Z,.FLSPACE
CP   $09
JR   Z,.FLSPACE
CP   $28
JR   NZ,.NFUNCTIO
LD   A,C
OR   A
RET
.FLSPACE:
INC  HL
JR   .FLOOKAHE
.NFUNCTIO:
SCF
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
EX_PHOPE:
LD   (EX_OPER),A
CALL EX_COPOS
JP   EX_POPE1
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE,IX,IY
EX_POP:
LD   A,(TK_REC+TK_KOFF)
CP   TK_PLUS
JR   Z,.PUNARY
CP   TK_MINUS
JR   Z,.PUNARY
CP   TK_TILDE
JR   Z,.PUNARY
CP   TK_NUMBE
JR   Z,.PNUMBER
CP   TK_CUR
JR   Z,.PCUR
CP   TK_NAME
JR   Z,.PNAME
.RLPAREN:
CP   TK_LPARE
JR   Z,.PPAREN
LD   A,EX_SEPRI
JP   EX_FHERE
.PUNARY:
OR   $70
CALL EX_PHOPE
RET  C
JP   EX_NTOK
.PPAREN:
LD   A,EX_MLPAR
LD   (EX_OPER),A
CALL EX_COPOS
CALL EX_POPE1
RET  C
LD   HL,EX_PDEPT
INC  (HL)
JP   EX_NTOK
.PNUMBER:
LD   HL,(TK_REC+TK_VOFF)
CALL EX_SRW
JR   .PFIN
.PCUR:
LD   HL,(EX_CADR)
CALL EX_SRW
JR   .PFIN
.PNAME:
CALL EX_CFUNC
JR   NC,.PFUNCTIO
CALL EX_PNAME
RET  C
JR   .PPUBLISH
.PFIN:
CALL EX_NTOK
RET  C
.PPUBLISH:
CALL EX_PVAL
RET  C
CALL EX_AUNAR
RET  C
XOR  A
LD   (EX_EOP),A
RET
.PFUNCTIO:
CALL EX_PHOPE
RET  C
CALL EX_NTOK
RET  C
LD   A,(TK_REC+TK_KOFF)
JR   .RLPAREN
;@ROUTINE OUT A,CARRY,ZERO CLOBBERS BC,DE,HL,IX,IY,SIGN,PARITY,HALFCARRY
EX_POPER:
LD   A,(TK_REC+TK_KOFF)
CP   TK_RPARE
JR   Z,.RPAREN
CALL EX_COPER
JR   C,.DELIMITE
CALL EX_SINCO
CALL EX_RINC1
RET  C
CALL EX_RINCO
CALL EX_POPE1
RET  C
LD   A,1
LD   (EX_EOP),A
CALL EX_NTOK
RET  C
XOR  A
INC  A
RET
.RPAREN:
LD   A,(EX_PDEPT)
OR   A
JR   Z,.DELIMITE
CALL EX_RTPAR
RET  C
CALL EX_POPE2
RET  C
LD   HL,EX_PDEPT
DEC  (HL)
CALL EX_NTOK
RET  C
CALL EX_AUNAR
RET  C
XOR  A
INC  A
RET
.DELIMITE:
LD   A,(EX_PDEPT)
OR   A
JR   Z,.DDONE
LD   A,EX_SERIG
JP   EX_FHERE
.DDONE:
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,HL,IX,ZERO,SIGN,PARITY,HALFCARRY,DE,IY
EX_PNAME:
LD   A,(TK_REC+TK_POFF)
LD   (EX_SPART),A
LD   HL,(TK_REC+TK_SOFF)
LD   (EX_SOFF),HL
CALL TK_LLEXE
LD   DE,EX_RKEY
CALL EN_PSYM
JP   C,EX_SFAIL
LD   HL,EX_RKEY
CALL SY_FIND
JR   C,.PMISSING
BIT  6,(IX+5)
JR   Z,.PUNRESOL
LD   L,(IX+SY_VALLO)
LD   H,(IX+SY_VALHI)
BIT  5,(IX+5)
JR   Z,.PPSYM
LD   (EX_RVAL),HL
LD   A,$FF
LD   (EX_RVAL+2),A
XOR  A
JR   .SUNRESOL
.PPSYM:
CALL EX_SRW
JP   EX_NTOK
.PMISSING:
CP   SY_SNFOU
JR   Z,.PUNRESOL
JP   EX_SFAIL
.PUNRESOL:
XOR  A
LD   (EX_RVAL),A
LD   (EX_RVAL+1),A
LD   (EX_RVAL+2),A
INC  A
.SUNRESOL:
LD   (EX_RUNRE),A
JP   EX_NTOK
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,C,HL
EX_COPER:
LD   A,(TK_REC+TK_KOFF)
SUB  TK_PLUS
CP   12
JR   NC,.ODELIMIT
PUSH DE
LD   E,A
LD   D,0
LD   HL,EX_OTABL
ADD  HL,DE
LD   A,(HL)
POP  DE
OR   A
JR   Z,.ODELIMIT
LD   (EX_OPER),A
CALL EX_COPOS
OR   A
RET
.ODELIMIT:
SCF
RET
EX_OTABL:
DB $55,$56,$67,$68,$69,$32,$21,$10,0,0,$43,$44
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,HL,SIGN,PARITY,HALFCARRY
EX_COPOS:
LD   A,(TK_REC+TK_POFF)
LD   (EX_OPART),A
LD   HL,(TK_REC+TK_SOFF)
LD   (EX_OOFF),HL
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_PVAL:
LD   A,(EX_VDEPT)
CP   EX_VCAP
JP   NC,EX_CFAIL
CALL EX_VADR
LD   D,H
LD   E,L
LD   HL,EX_RVAL
LD   BC,EX_VALB
LDIR
LD   HL,EX_VDEPT
INC  (HL)
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_PVAL1:
LD   DE,EX_RVAL
JR   EX_PVTO
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_PLVAL:
LD   DE,EX_LVAL
;@ROUTINE IN DE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_PVTO:
PUSH DE
LD   A,(EX_VDEPT)
OR   A
JR   Z,EX_PVEMP
DEC  A
LD   (EX_VDEPT),A
CALL EX_VADR
POP  DE
LD   BC,EX_VALB
LDIR
XOR  A
RET
EX_PVEMP:
POP  DE
JR   EX_IFAIL
;@ROUTINE IN A OUT HL CLOBBERS DE,A,F
EX_VADR:
LD   E,A
LD   D,0
LD   H,D
LD   L,E
ADD  HL,HL
ADD  HL,HL
ADD  HL,HL
EX   DE,HL
ADD  HL,HL
ADD  HL,DE
LD   DE,EX_VSTAC
ADD  HL,DE
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_POPE1:
LD   A,(EX_ODEPT)
CP   EX_OCAP
JR   NC,EX_CFAIL
CALL EX_OADR
LD   D,H
LD   E,L
LD   HL,EX_OPER
LD   BC,EX_OPERB
LDIR
LD   HL,EX_ODEPT
INC  (HL)
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE
EX_POPE2:
LD   A,(EX_ODEPT)
OR   A
JR   Z,EX_IFAIL
DEC  A
LD   (EX_ODEPT),A
CALL EX_OADR
LD   DE,EX_OPER
LD   BC,EX_OPERB
LDIR
XOR  A
RET
;@ROUTINE IN A OUT HL CLOBBERS DE,A,F
EX_OADR:
LD   L,A
LD   H,0
ADD  HL,HL
ADD  HL,HL
LD   DE,EX_OSTAC
ADD  HL,DE
RET
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,DE,HL
EX_POPE3:
LD   A,(EX_ODEPT)
OR   A
SCF
RET  Z
DEC  A
CALL EX_OADR
LD   A,(HL)
OR   A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_CFAIL:
LD   A,EX_SCAP
JP   EX_FHERE
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_IFAIL:
LD   A,EX_SINT
JP   EX_FHERE
;@ROUTINE OUT CARRY,ZERO CLOBBERS BC,DE,HL,PARITY,HALFCARRY,SIGN,A
EX_SINCO:
LD   HL,EX_OPER
LD   DE,EX_INCOM
JR   EX_CINCO
;@ROUTINE OUT CARRY,ZERO CLOBBERS BC,DE,HL,PARITY,HALFCARRY,SIGN,A
EX_RINCO:
LD   HL,EX_INCOM
LD   DE,EX_OPER
;@ROUTINE IN HL,DE OUT CARRY,ZERO CLOBBERS BC,DE,HL,PARITY,HALFCARRY,SIGN,A
EX_CINCO:
LD   BC,EX_OPERB
LDIR
RET
;@ROUTINE OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
EX_RINC1:
.RILOOP:
CALL EX_POPE3
JR   C,.RIDONE
CP   EX_MLPAR
JR   Z,.RIDONE
AND  $F0
LD   B,A
LD   A,(EX_INCOM)
AND  $F0
CP   B
JR   C,.RINOW
RET  NZ
.RINOW:
CALL EX_REDUC
RET  C
JR   .RILOOP
.RIDONE:
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
EX_RTPAR:
.RTPLOOP:
CALL EX_POPE3
JR   C,EX_IFAIL
CP   EX_MLPAR
RET  Z
CALL EX_REDUC
RET  C
JR   .RTPLOOP
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IX,IY
EX_AUNAR:
.AULOOP:
CALL EX_POPE3
JR   C,.AUDONE
AND  $F0
CP   $70
JR   NZ,.AUDONE
CALL EX_POPE2
RET  C
CALL EX_PVAL1
RET  C
LD   A,(EX_RUNRE)
OR   A
JR   Z,.AUCONCRE
LD   A,(EX_OPER)
CP   EX_UPLUS
JR   Z,.AUPUBLIS
CP   EX_ULO
JR   Z,.AUFLO
CP   EX_UHI
JR   Z,.AUFHI
.AUFFAIL:
LD   A,EX_SFFOR
JP   EX_FOPER
.AUFLO:
LD   B,EX_FLO
JR   .AUFFUNCT
.AUFHI:
LD   B,EX_FHI
.AUFFUNCT:
LD   A,(EX_RUNRE)
CP   EX_FPLAI
JR   NZ,.AUFFAIL
LD   A,B
LD   (EX_RUNRE),A
JR   .AUPUBLIS
.AUCONCRE:
LD   A,(EX_OPER)
CP   EX_UPLUS
JR   Z,.AUPUBLIS
CP   EX_UMINU
JR   Z,.AUNEGATE
CP   EX_UTILD
JR   Z,.AUCOMPLE
CP   EX_ULO
JR   Z,.AULO
CP   EX_UHI
JR   Z,.AUHI
JP   EX_IFAIL
.AUNEGATE:
CALL EX_NRES
JR   .AUCDONE
.AUCOMPLE:
CALL EX_CRES
JR   .AUCDONE
.AULO:
XOR  A
LD   (EX_RVAL+1),A
LD   (EX_RVAL+2),A
JR   .AUCDONE
.AUHI:
LD   A,(EX_RVAL+1)
LD   (EX_RVAL),A
XOR  A
LD   (EX_RVAL+1),A
LD   (EX_RVAL+2),A
.AUCDONE:
RET  C
.AUPUBLIS:
CALL EX_PVAL
RET  C
JP   .AULOOP
.AUDONE:
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
EX_FSTAC:
.FREDUCE:
CALL EX_POPE3
JR   C,.FINVAL
CP   EX_MLPAR
JP   Z,EX_IFAIL
CALL EX_REDUC
RET  C
JR   .FREDUCE
.FINVAL:
CALL EX_PVAL1
RET  C
LD   A,(EX_VDEPT)
OR   A
JP   NZ,EX_IFAIL
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IX,IY
EX_REDUC:
CALL EX_POPE2
RET  C
CALL EX_PVAL1
RET  C
CALL EX_PLVAL
RET  C
CALL EX_RLOAD
RET  C
JP   EX_PVAL
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_RLOAD:
LD   A,(EX_LUNRE)
LD   B,A
LD   A,(EX_RUNRE)
OR   B
JR   NZ,EX_RFORW
LD   A,(EX_OPER)
AND  $0F
CP   10
JP   NC,EX_IFAIL
ADD  A,A
LD   L,A
LD   H,0
LD   DE,EX_RTABL
ADD  HL,DE
LD   E,(HL)
INC  HL
LD   D,(HL)
EX   DE,HL
JP   (HL)
EX_RTABL:
DW EX_OR,EX_XOR,EX_AND
DW EX_SLEFT,EX_SRIGH
DW EX_ADD,EX_SUBTR
DW EX_MULTI,EX_DIVID
DW EX_REMAI
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_RFORW:
LD   A,(EX_LUNRE)
CP   EX_FLO
JR   NC,.FFAIL
LD   A,(EX_RUNRE)
CP   EX_FLO
JR   NC,.FFAIL
LD   A,(EX_LUNRE)
OR   A
JR   Z,.FRIGHT
LD   A,(EX_RUNRE)
OR   A
JR   NZ,.FFAIL
LD   A,(EX_OPER)
AND  $0F
CP   EX_OPADD
JR   Z,.FLADD
CP   EX_OSUBT
JR   NZ,.FFAIL
CALL EX_SUBTR
JR   C,.FRETURN
JR   .FULKEY
.FLADD:
CALL EX_ADD
JR   C,.FRETURN
.FULKEY:
LD   HL,EX_LKEY
LD   DE,EX_RKEY
LD   BC,6
LDIR
JR   .FFIN
.FRIGHT:
LD   A,(EX_OPER)
AND  $0F
CP   EX_OPADD
JR   NZ,.FFAIL
CALL EX_ADD
JR   C,.FRETURN
.FFIN:
LD   A,EX_FPLAI
LD   (EX_RUNRE),A
CALL EX_RADDE
.FRETURN:
RET
.FFAIL:
LD   A,EX_SFFOR
JP   EX_FOPER
;@ROUTINE OUT A,BC,HL CLOBBERS CARRY,ZERO,SIGN,PARITY,HALFCARRY
EX_LARIT:
LD   A,(EX_LVAL+2)
LD   B,A
LD   A,(EX_RVAL+2)
LD   C,A
LD   A,(EX_LVAL)
LD   HL,EX_RVAL
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,HL,SIGN,PARITY,HALFCARRY,DE,ZERO
EX_ADD:
CALL EX_LARIT
ADD  A,(HL)
LD   (HL),A
INC  HL
LD   A,(EX_LVAL+1)
ADC  A,(HL)
LD   (HL),A
INC  HL
LD   A,B
ADC  A,(HL)
LD   (HL),A
LD   D,A
LD   A,B
XOR  C
BIT  7,A
JR   NZ,EX_AOK
LD   A,B
XOR  D
BIT  7,A
JP   NZ,EX_ROPER
;@ROUTINE OUT A,CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY
EX_AOK:
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,HL,SIGN,PARITY,HALFCARRY,DE,ZERO,IX,IY
EX_SUBTR:
CALL EX_LARIT
SUB  (HL)
LD   (HL),A
INC  HL
LD   A,(EX_LVAL+1)
SBC  A,(HL)
LD   (HL),A
INC  HL
LD   A,B
SBC  A,(HL)
LD   (HL),A
LD   D,A
LD   A,B
XOR  C
BIT  7,A
JR   Z,EX_AOK
LD   A,B
XOR  D
BIT  7,A
JP   NZ,EX_ROPER
JR   EX_AOK
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
EX_AND:
LD   HL,EX_RVAL
LD   DE,EX_LVAL
LD   B,3
.ANDLOOP:
LD   A,(DE)
AND  (HL)
LD   (HL),A
INC  DE
INC  HL
DJNZ .ANDLOOP
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
EX_XOR:
LD   HL,EX_RVAL
LD   DE,EX_LVAL
LD   B,3
.XORLOOP:
LD   A,(DE)
XOR  (HL)
LD   (HL),A
INC  DE
INC  HL
DJNZ .XORLOOP
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
EX_OR:
LD   HL,EX_RVAL
LD   DE,EX_LVAL
LD   B,3
.ORLOOP:
LD   A,(DE)
OR   (HL)
LD   (HL),A
INC  DE
INC  HL
DJNZ .ORLOOP
XOR  A
RET
;@ROUTINE IN HL OUT A,HL,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
EX_SL24:
LD   A,(HL)
SLA  A
LD   (HL),A
INC  HL
LD   A,(HL)
RL   A
LD   (HL),A
INC  HL
LD   A,(HL)
RL   A
LD   (HL),A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE,IX,IY
EX_SLEFT:
CALL EX_SCNT
RET  C
LD   B,A
OR   A
JR   Z,.SLCOPY
.SLLOOP:
LD   A,(EX_LVAL+2)
LD   C,A
LD   HL,EX_LVAL
CALL EX_SL24
XOR  C
BIT  7,A
JP   NZ,EX_ROPER
DJNZ .SLLOOP
.SLCOPY:
LD   HL,EX_LVAL
LD   DE,EX_RVAL
LD   BC,3
LDIR
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE,IX,IY
EX_SRIGH:
CALL EX_SCNT
RET  C
LD   B,A
PUSH BC
LD   HL,EX_LVAL
LD   DE,EX_RVAL
LD   BC,3
LDIR
POP  BC
LD   A,B
OR   A
JP   Z,EX_AOK
LD   B,A
.SRLOOP:
LD   HL,EX_RVAL+2
LD   A,(HL)
SRA  A
CALL EX_SRL16
DJNZ .SRLOOP
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_SCNT:
LD   A,(EX_RVAL+2)
OR   A
JP   NZ,EX_ROPER
LD   A,(EX_RVAL+1)
OR   A
JP   NZ,EX_ROPER
LD   A,(EX_RVAL)
CP   24
JP   NC,EX_ROPER
OR   A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_MULTI:
CALL EX_PMAGN
XOR  A
LD   (EX_ACCUM),A
LD   (EX_ACCUM+1),A
LD   (EX_ACCUM+2),A
LD   A,24
LD   (EX_MCOUN),A
.MLOOP:
LD   A,(EX_MRIGH)
BIT  0,A
JR   Z,.MSADD
CALL EX_AALEF
JP   C,EX_ROPER
.MSADD:
CALL EX_MRSHI
LD   A,(EX_MRIGH)
LD   C,A
LD   A,(EX_MRIGH+1)
OR   C
LD   C,A
LD   A,(EX_MRIGH+2)
OR   C
JR   Z,.MDONE
LD   A,(EX_MLEFT+2)
BIT  7,A
JP   NZ,EX_ROPER
CALL EX_MLSHI
LD   HL,EX_MCOUN
DEC  (HL)
JR   NZ,.MLOOP
.MDONE:
LD   HL,EX_ACCUM
LD   DE,EX_RVAL
LD   BC,3
LDIR
LD   A,(EX_SRES)
OR   A
EX_ASRES:
CALL NZ,EX_NRES
RET  C
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_DIVID:
XOR  A
LD   (EX_DRMOD),A
JR   EX_DCOMM
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
EX_REMAI:
LD   A,1
LD   (EX_DRMOD),A
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,SIGN,PARITY,HALFCARRY,ZERO
EX_DCOMM:
LD   A,(EX_RVAL)
LD   B,A
LD   A,(EX_RVAL+1)
OR   B
LD   B,A
LD   A,(EX_RVAL+2)
OR   B
JR   Z,.DZERO
CALL EX_PMAGN
XOR  A
LD   (EX_ACCUM),A
LD   (EX_ACCUM+1),A
LD   (EX_ACCUM+2),A
LD   (EX_QUOTI),A
LD   (EX_QUOTI+1),A
LD   (EX_QUOTI+2),A
LD   B,24
.DLOOP:
LD   HL,EX_MLEFT
CALL EX_SL24
LD   HL,EX_ACCUM
LD   A,(HL)
RL   A
LD   (HL),A
INC  HL
LD   A,(HL)
RL   A
LD   (HL),A
INC  HL
LD   A,(HL)
RL   A
LD   (HL),A
LD   HL,EX_QUOTI
CALL EX_SL24
CALL EX_RALDI
JR   C,.DNEXT
CALL EX_RSDIV
LD   HL,EX_QUOTI
LD   A,(HL)
SET  0,A
LD   (HL),A
.DNEXT:
DJNZ .DLOOP
LD   A,(EX_DRMOD)
OR   A
JR   NZ,.UREMAIND
LD   HL,EX_QUOTI
LD   A,(EX_SRES)
JR   .DSTORE
.UREMAIND:
LD   HL,EX_ACCUM
LD   A,(EX_SLEF1)
.DSTORE:
LD   DE,EX_RVAL
LD   BC,3
LDIR
OR   A
JP   EX_ASRES
.DZERO:
LD   A,EX_SDZER
JP   EX_FOPER
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,BC,DE,HL,IX,IY,SIGN,PARITY,HALFCARRY
EX_PMAGN:
LD   HL,EX_LVAL
LD   DE,EX_MLEFT
LD   BC,3
LDIR
LD   HL,EX_RVAL
LD   DE,EX_MRIGH
LD   BC,3
LDIR
LD   A,(EX_LVAL+2)
RLCA
AND  1
LD   (EX_SLEF1),A
OR   A
CALL NZ,EX_NMLEF
LD   A,(EX_RVAL+2)
RLCA
AND  1
LD   (EX_SRIG1),A
OR   A
CALL NZ,EX_NMRIG
LD   A,(EX_SLEF1)
LD   HL,EX_SRIG1
XOR  (HL)
LD   (EX_SRES),A
OR   A
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY,A,BC,DE,IX,IY
EX_NRES:
LD   HL,EX_RVAL
JR   EX_NAHL
;@ROUTINE OUT CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY,A,BC,DE,IX,IY
EX_NMLEF:
LD   HL,EX_MLEFT
JR   EX_NAHL
;@ROUTINE OUT CARRY,ZERO CLOBBERS HL,A,BC,DE,IX,IY,SIGN,PARITY,HALFCARRY
EX_NMRIG:
LD   HL,EX_MRIGH
;@ROUTINE IN HL OUT A,CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY
EX_NAHL:
LD   A,(HL)
CPL
ADD  A,1
LD   (HL),A
INC  HL
LD   A,(HL)
CPL
ADC  A,0
LD   (HL),A
INC  HL
LD   A,(HL)
CPL
ADC  A,0
LD   (HL),A
XOR  A
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY,A
EX_CRES:
LD   HL,EX_RVAL
LD   A,(HL)
CPL
LD   (HL),A
INC  HL
LD   A,(HL)
CPL
LD   (HL),A
INC  HL
LD   A,(HL)
CPL
LD   (HL),A
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_AALEF:
LD   HL,EX_ACCUM
LD   A,(EX_MLEFT)
ADD  A,(HL)
LD   (HL),A
INC  HL
LD   A,(EX_MLEFT+1)
ADC  A,(HL)
LD   (HL),A
INC  HL
LD   A,(EX_MLEFT+2)
ADC  A,(HL)
LD   (HL),A
RET
;@ROUTINE OUT CARRY,ZERO MAYBE-OUT BC,DE CLOBBERS A,HL,SIGN,PARITY,HALFCARRY,IX,IY,BC,DE
EX_MLSHI:
LD   HL,EX_MLEFT
JP   EX_SL24
;@ROUTINE OUT CARRY,ZERO MAYBE-OUT BC,DE CLOBBERS A,HL,SIGN,PARITY,HALFCARRY,IX,IY,BC,DE
EX_MRSHI:
LD   HL,EX_MRIGH+2
LD   A,(HL)
SRL  A
;@ROUTINE IN A,HL OUT CARRY,ZERO CLOBBERS A,HL,SIGN,PARITY,HALFCARRY
EX_SRL16:
LD   (HL),A
DEC  HL
LD   A,(HL)
RR   A
LD   (HL),A
DEC  HL
LD   A,(HL)
RR   A
LD   (HL),A
RET
;@ROUTINE OUT A,CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY
EX_RALDI:
LD   A,(EX_ACCUM+2)
LD   HL,EX_MRIGH+2
CP   (HL)
RET  NZ
LD   A,(EX_ACCUM+1)
DEC  HL
CP   (HL)
RET  NZ
LD   A,(EX_ACCUM)
DEC  HL
CP   (HL)
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,C,DE,HL,SIGN,PARITY,HALFCARRY
EX_RSDIV:
LD   HL,EX_ACCUM
LD   DE,EX_MRIGH
LD   A,(DE)
LD   C,A
LD   A,(HL)
SUB  C
LD   (HL),A
INC  HL
INC  DE
LD   A,(DE)
LD   C,A
LD   A,(HL)
SBC  A,C
LD   (HL),A
INC  HL
INC  DE
LD   A,(DE)
LD   C,A
LD   A,(HL)
SBC  A,C
LD   (HL),A
RET
;@ROUTINE IN HL OUT CARRY,ZERO CLOBBERS A,SIGN,PARITY,HALFCARRY
EX_SRW:
LD   (EX_RVAL),HL
XOR  A
LD   (EX_RVAL+2),A
LD   (EX_RUNRE),A
RET
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,HL
EX_REQW:
LD   A,(EX_RVAL+2)
OR   A
RET  Z
INC  A
JR   NZ,.RHERE
LD   A,(EX_RVAL+1)
BIT  7,A
RET  NZ
.RHERE:
LD   A,EX_SRANG
JR   EX_FHERE
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE,IX,IY
EX_RADDE:
LD   A,(EX_RVAL+2)
OR   A
JR   Z,.APOSITIV
INC  A
JR   NZ,EX_ROPER
LD   A,(EX_RVAL+1)
INC  A
JR   NZ,EX_ROPER
LD   A,(EX_RVAL)
BIT  7,A
RET  NZ
JR   EX_ROPER
.APOSITIV:
LD   A,(EX_RVAL+1)
OR   A
JR   NZ,EX_ROPER
LD   A,(EX_RVAL)
BIT  7,A
JR   NZ,EX_ROPER
OR   A
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
EX_NTOK:
CALL TK_NEXT
RET  NC
LD   A,EX_SLEXI
JR   EX_FTOKE
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY
EX_ROPER:
LD   A,EX_SRANG
JR   EX_FOPER
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
EX_FHERE:
LD   HL,TK_REC+TK_POFF
JR   EX_FPOSI
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
EX_FOPER:
LD   HL,EX_OPART
JR   EX_FPOSI
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
EX_FSYM:
LD   HL,EX_SPART
JR   EX_FPOSI
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
EX_FTOKE:
LD   HL,TK_EPART
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
EX_FPOSI:
PUSH BC
PUSH DE
LD   DE,EX_EPART
LD   BC,3
LDIR
POP  DE
POP  BC
SCF
RET
EX_RCEND:
EX_CEND:
EX_WBEG:
EX_CADR: DW 0
EX_PSYM: DB 0
EX_RVAL: DS 3
EX_RUNRE: DB 0
EX_RKEY: DS 6
EX_LVAL: DS 3
EX_LUNRE: DB 0
EX_LKEY: DS 6
EX_OPER: DB 0
EX_OPART: DB 0
EX_OOFF: DW 0
EX_INCOM: DS EX_OPERB
EX_SPART: DB 0
EX_SOFF: DW 0
EX_SSTAT: DB 0
EX_MCOUN EQU EX_SSTAT
EX_VDEPT: DB 0
EX_ODEPT: DB 0
EX_PDEPT: DB 0
EX_EOP: DB 0
EX_SLEF1 EQU EX_SPART
EX_SRIG1 EQU EX_SOFF
EX_SRES EQU EX_SOFF+1
EX_DRMOD EQU EX_MCOUN
EX_MLEFT EQU EX_RKEY
EX_MRIGH EQU EX_RKEY+3
EX_ACCUM EQU EX_LKEY
EX_EPART EQU EX_ACCUM
EX_EOFF EQU EX_ACCUM+1
EX_QUOTI EQU EX_LKEY+3
EX_VSTAC: DS EX_VALB*EX_VCAP
