LD   DE,OU_INSB
CALL EN_NAME
RET  C
LD   (OU_ILEN),A
LD   B,A
LD   HL,(OU_REM)
LD   A,H
OR   A
JR   NZ,.ICREADY
LD   A,L
CP   B
JR   C,.ICFAIL
.ICREADY:
CALL PR_CREFE
RET  C
XOR  A
LD   (OU_ISCAN),A
.INSLOOP:
LD   A,(OU_ILEN)
LD   B,A
LD   A,(OU_ISCAN)
CP   B
JR   Z,.INSDONE
LD   E,A
LD   D,0
LD   HL,OU_INSB
ADD  HL,DE
LD   A,(HL)
CALL OU_EBREA
RET  C
LD   HL,OU_ISCAN
INC  (HL)
JR   .INSLOOP
.INSDONE:
LD   DE,(OU_IBEG)
JP   PR_QREFE
.ICFAIL:
LD   A,OU_SCAP
SCF
RET
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
OU_RSLV:
BIT  6,(IX+5)
JP   Z,OU_RINT
PUSH IX
POP  HL
LD   (OU_RSPTR),HL
.RSLVLOOP:
LD   IX,(OU_RSPTR)
;@EXPECTOUT A,CARRY,BC,DE
CALL SY_PEEK
JP   C,.RPFAIL
LD   (OU_RPADR),DE
LD   A,B
AND  SY_KMASK
LD   (OU_RKIND),A
LD   A,C
LD   (OU_RADDE),A
LD   IX,(OU_RSPTR)
LD   L,(IX+SY_VALLO)
LD   H,(IX+SY_VALHI)
XOR  A
BIT  5,(IX+5)
JR   Z,.RBREADY
DEC  A
.RBREADY:
LD   (OU_RBHI),A
LD   A,(OU_RADDE)
LD   C,A
LD   D,0
BIT  7,C
JR   Z,.RSREADY
DEC  D
.RSREADY:
LD   A,L
ADD  A,C
LD   (OU_RVAL),A
LD   A,H
ADC  A,D
LD   (OU_RVAL+1),A
LD   A,(OU_RBHI)
ADC  A,D
LD   (OU_RVAL+2),A
CALL OU_RWDOM
RET  C
LD   A,(OU_RKIND)
CP   PT_KINDB
JR   Z,.RSLVB
CP   PT_KINDW
JR   Z,.RSLVW
CP   PT_KRELA
JR   Z,.RRELATIV
CP   PT_KDISP
JR   Z,.RDISPLAC
CP   PT_KTB
JR   Z,.RSB
CP   PT_KLB
JR   Z,.RSB
CP   PT_KHB
JP   NZ,OU_RINT
.RSLVHIB:
LD   A,(OU_RVAL+1)
JR   .RSBA
.RSLVB:
LD   A,(OU_RVAL+2)
OR   A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
OR   A
JR   NZ,OU_RVRAN
JR   .RSB
.RDISPLAC:
LD   A,(OU_RVAL+2)
OR   A
JR   Z,.RDPOSITI
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL)
BIT  7,A
JR   Z,OU_RVRAN
JR   .RSB
.RDPOSITI:
LD   A,(OU_RVAL+1)
OR   A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL)
BIT  7,A
JR   NZ,OU_RVRAN
JR   .RSB
.RRELATIV:
LD   HL,(OU_RVAL)
LD   DE,(OU_RPADR)
INC  DE
OR   A
SBC  HL,DE
LD   A,H
OR   A
JR   Z,.RRPOSITI
INC  A
JR   NZ,OU_RRRAN
BIT  7,L
JR   Z,OU_RRRAN
LD   A,L
JR   .RSBA
.RRPOSITI:
BIT  7,L
JR   NZ,OU_RRRAN
LD   A,L
JR   .RSBA
.RSB:
LD   A,(OU_RVAL)
.RSBA:
LD   HL,(OU_RPADR)
LD   C,0
CALL HS_PB
RET  C
JR   .RREMOVE
.RSLVW:
LD   HL,(OU_RVAL)
LD   DE,(OU_RPADR)
LD   C,0
CALL HS_PW
RET  C
.RREMOVE:
LD   IX,(OU_RSPTR)
;@EXPECTOUT A,CARRY,BC,DE
CALL SY_TAKE
JR   C,OU_RINT
JP   .RSLVLOOP
.RPFAIL:
CP   SY_SNFOU
RET  NZ
XOR  A
RET
OU_RVRAN:
LD   A,OU_SVRAN
SCF
RET
OU_RRRAN:
LD   A,OU_SRRAN
SCF
RET
OU_RINT:
LD   A,OU_SINT
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,BC,DE,HL,IX,IY
OU_RWDOM:
LD   A,(OU_RVAL+2)
OR   A
RET  Z
INC  A
JR   NZ,OU_RVRAN
LD   A,(OU_RVAL+1)
BIT  7,A
RET  NZ
JR   OU_RVRAN
OU_CEND:
OU_WBEG:
OU_CURSO: DW 0
OU_REM: DW 0
OU_WUNIO: DS 10
OU_IBEG EQU OU_WUNIO
OU_INSB EQU OU_WUNIO+2
OU_ILEN EQU OU_WUNIO+6
OU_ISCAN EQU OU_WUNIO+7
OU_RSPTR EQU OU_WUNIO
OU_RPADR EQU OU_WUNIO+2
OU_RKIND EQU OU_WUNIO+4
OU_RADDE EQU OU_WUNIO+5
OU_RVAL EQU OU_WUNIO+6
OU_RBHI EQU OU_WUNIO+9
OU_WEND:
ST_CBEG:
ST_SOK EQU 0
ST_SLEXI EQU 1
ST_SEXP EQU 2
ST_SDIR EQU 3
ST_SEQUA EQU 4
ST_SSYM EQU 5
ST_SINS EQU 6
ST_SOUT EQU 7
ST_SUNDE EQU 8
ST_SINT EQU 9
ST_EQU EQU 1
ST_ORG EQU 2
ST_DB EQU 3
ST_DW EQU 4
ST_DS EQU 5
ST_CSTR EQU 6
ST_PSTR EQU 7
ST_ISTR EQU 8
ST_ALIGN EQU 9
ST_CNT EQU 9
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
DR_APART:
ST_NEXT:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOF
JP   Z,ST_SUCCE
CP   TK_EOL
JR   Z,ST_NEXT
CP   TK_NAME
JP   NZ,ST_EHERE
CALL ST_CPOSI
CALL TK_LLEXE
LD   DE,ST_KEY
CALL EN_PSYM
JP   C,ST_SFAIL
CALL TK_LLEXE
CALL EN_RECOG
JR   C,ST_NMNEM
LD   (ST_MNEM),A
LD   A,1
LD   (ST_MVALI),A
XOR  A
LD   (ST_DVALI),A
JR   ST_AFNAM
ST_NMNEM:
XOR  A
LD   (ST_MVALI),A
CALL TK_LLEXE
CALL EN_RDIR
JR   C,ST_NDIR
LD   (ST_DIR),A
LD   A,1
LD   (ST_DVALI),A
JR   ST_AFNAM
ST_NDIR:
XOR  A
LD   (ST_DVALI),A
ST_AFNAM:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_COLON
JR   Z,ST_LABEL
LD   A,(ST_MVALI)
OR   A
JP   NZ,ST_IPUB
LD   A,(ST_DVALI)
OR   A
JR   Z,ST_TEQUA
LD   A,(ST_DIR)
JP   ST_DPUB
ST_TEQUA:
LD   A,(TK_REC+TK_KOFF)
CP   TK_NAME
JP   NZ,ST_ESAVE
CALL TK_LLEXE
CALL EN_RDIR
JP   C,ST_ESAVE
CP   ST_EQU
JP   NZ,ST_ESAVE
JP   ST_EQUAT
ST_LABEL:
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_NAME
JR   NZ,ST_LPUBL
CALL TK_LLEXE
CALL EN_RDIR
JR   C,ST_LPUBL
CP   ST_EQU
JR   Z,ST_EQUAT
ST_LPUBL:
LD   HL,ST_KEY+5
BIT  7,(HL)
LD   HL,ST_KEY
LD   DE,(OU_CURSO)
JR   NZ,ST_PLABE
CALL SY_DGLAB
JR   ST_LDECL
ST_PLABE:
CALL SY_DECL
ST_LDECL:
JP   C,ST_SFAIL
CALL OU_RSLV
JP   C,ST_OFAIL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_NEXT
CP   TK_NAME
JP   NZ,ST_EHERE
CALL ST_CPOSI
CALL TK_LLEXE
CALL EN_RECOG
JR   C,ST_LDIR
LD   (ST_MNEM),A
CALL TK_NEXT
JP   C,ST_LFAIL
JR   ST_IPUB
ST_LDIR:
CALL TK_LLEXE
CALL EN_RDIR
JP   C,ST_ESAVE
LD   (ST_DIR),A
CALL TK_NEXT
JP   C,ST_LFAIL
LD   A,(ST_DIR)
JR   ST_DPUB
ST_IPUB:
LD   A,(ST_MNEM)
LD   BC,(OU_CURSO)
LD   DE,ST_INS
CALL PR_PUB
JP   C,ST_IFAIL
CALL OU_EINS
ST_OTNEX:
JP   C,ST_OFAIL
JP   ST_NEXT
ST_EQUAT:
CALL TK_NEXT
JP   C,ST_LFAIL
CALL ST_PEXPR
JP   C,ST_EFAIL
OR   A
JP   NZ,ST_EUNRE
LD   (ST_EVAL),HL
XOR  A
LD   HL,EX_RVAL+2
CP   (HL)
JR   Z,ST_ESREA
INC  A
ST_ESREA:
LD   (ST_ESIGN),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_EDELI
LD   HL,ST_KEY
LD   DE,(ST_EVAL)
CALL SY_DECL
JP   C,ST_SFAIL
LD   A,(ST_ESIGN)
OR   A
JR   Z,ST_ERSLV
SET  5,(IX+5)
ST_ERSLV:
CALL OU_RSLV
JR   ST_OTNEX
ST_DPUB:
SUB  ST_ORG
CP   8
JP   NC,ST_ESAVE
ADD  A,A
LD   L,A
LD   H,0
LD   DE,ST_DDTAB
ADD  HL,DE
LD   E,(HL)
INC  HL
LD   D,(HL)
EX   DE,HL
JP   (HL)
ST_DDTAB:
DW ST_ORG1,ST_DB1,ST_DW1,ST_DS1
DW ST_CSTR1,ST_PSTR1,ST_ISTR1
DW ST_ALIG1
ST_ORG1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   (ST_DVAL),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(ST_DVAL)
CALL OU_SORIG
JP   ST_OTNEX
ST_DB1:
LD   A,1
LD   (ST_DWIDT),A
LD   A,PT_KTB
LD   (ST_DPKIN),A
JR   ST_DITEM
ST_DW1:
LD   A,2
LD   (ST_DWIDT),A
LD   A,PT_KINDW
LD   (ST_DPKIN),A
ST_DITEM:
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_DEXP
CP   TK_STRIN
JR   NZ,ST_DEXPR
LD   A,(ST_DWIDT)
CP   1
JP   NZ,ST_DSTR1
XOR  A
LD   (ST_SMODE),A
JP   ST_DSTRI
ST_DEXPR:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JR   NZ,ST_DUNRE
LD   A,(ST_DWIDT)
CP   1
JR   Z,ST_DRB
CALL OU_EMITW
JR   ST_DORES
ST_DRB:
LD   A,L
CALL OU_EMITB
ST_DORES:
JP   C,ST_OFAIL
JP   ST_DDELI
ST_DUNRE:
LD   A,L
LD   (ST_DADDE),A
PUSH IX
POP  HL
LD   (ST_DKEY),HL
LD   A,(ST_DWIDT)
LD   L,A
LD   H,0
CALL OU_CCAP
JP   C,ST_OFAIL
CALL SY_CCAP
JP   C,ST_SFAIL
LD   A,(EX_RUNRE)
CP   EX_FLO
JR   Z,ST_DPLO
CP   EX_FHI
JR   Z,ST_DPHI
LD   A,(ST_DPKIN)
JR   ST_DPKRE
ST_DPLO:
LD   A,PT_KLB
JR   ST_DPKRE
ST_DPHI:
LD   A,PT_KHB
ST_DPKRE:
LD   (ST_DPKI1),A
LD   HL,(ST_DKEY)
CALL SY_REF
JP   C,ST_SFAIL
LD   A,B
OR   A
JR   Z,ST_DDREA
LD   HL,(EX_SOFF)
LD   (IX+SY_VALLO),L
LD   (IX+SY_VALHI),H
LD   A,SY_DANCH
LD   HL,ST_DPKI1
OR   (HL)
LD   (HL),A
ST_DDREA:
PUSH IX
POP  HL
LD   (ST_DSYM),HL
LD   HL,(OU_CURSO)
LD   (ST_DADR),HL
LD   A,(ST_DWIDT)
CP   1
JR   Z,ST_DPB
LD   HL,0
CALL OU_EMITW
JP   C,ST_OFAIL
JR   ST_DQUEU
ST_DPB:
XOR  A
CALL OU_EMITB
JP   C,ST_OFAIL
ST_DQUEU:
LD   IX,(ST_DSYM)
LD   DE,(ST_DADR)
LD   A,(ST_DPKI1)
LD   B,A
LD   A,(ST_DADDE)
LD   C,A
LD   A,(EX_SPART)
CALL SY_ADD
JP   C,ST_SFAIL
ST_DDELI:
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,ST_NEXT
CP   TK_COMMA
JP   NZ,ST_DDEL1
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOL
JP   Z,ST_DEXP
JP   ST_DITEM
ST_DSTRI:
LD   HL,(TK_REC+TK_SOFF)
INC  HL
LD   A,(TK_REC+TK_LOFF1)
SUB  2
LD   B,A
LD   C,0
ST_SCLOO:
LD   A,B
OR   A
JR   Z,ST_SCDON
PUSH HL
LD   A,(TK_REC+TK_POFF)
CALL TK_SREAD
POP  HL
INC  HL
DEC  B
CP   $5C
JR   NZ,ST_SCONE
PUSH HL
LD   A,(TK_REC+TK_POFF)
CALL TK_SREAD
POP  HL
INC  HL
DEC  B
CP   $78
JR   NZ,ST_SCONE
INC  HL
INC  HL
DEC  B
DEC  B
ST_SCONE:
INC  C
JR   ST_SCLOO
ST_SCDON:
LD   A,C
LD   (ST_SCNT),A
LD   HL,(TK_REC+TK_SOFF)
INC  HL
LD   (ST_SPTR),HL
LD   A,(TK_REC+TK_POFF)
LD   (ST_SPART),A
LD   A,(TK_REC+TK_LOFF1)
SUB  2
LD   (ST_SREM),A
LD   A,(ST_SMODE)
OR   A
JR   Z,ST_SCAP
CALL ST_NTKIN
JP   C,ST_LFAIL
CP   TK_EOL
JP   NZ,ST_DDEL1
ST_SCAP:
LD   A,(ST_SCNT)
LD   L,A
LD   H,0
LD   A,(ST_SMODE)
CP   1
JR   Z,ST_SCEXT
CP   2
JR   NZ,ST_SCREA
ST_SCEXT:
INC  HL
ST_SCREA:
CALL OU_CCAP
JP   C,ST_OFAIL
LD   A,(ST_SMODE)
CP   2
JR   NZ,ST_SELOO
LD   A,(ST_SCNT)
CALL OU_EMITB
JP   C,ST_OFAIL
ST_SELOO:
LD   A,(ST_SREM)
OR   A
JR   Z,ST_SDONE
CALL ST_STAKE
CP   $5C
JR   NZ,ST_SEMIT
CALL ST_STAKE
CP   $78
JR   Z,ST_SHEX
CALL TK_DESCA
JP   C,ST_DSTR1
JR   ST_SEMIT
ST_SHEX:
CALL ST_STAKE
CALL TK_HDIGI
JP   NC,ST_DSTR1
ADD  A,A
ADD  A,A
ADD  A,A
ADD  A,A
LD   (ST_SNIBB),A
CALL ST_STAKE
CALL TK_HDIGI
JP   NC,ST_DSTR1
LD   HL,ST_SNIBB
OR   (HL)
ST_SEMIT:
LD   C,A
LD   A,(ST_SMODE)
CP   3
LD   A,C
JR   NZ,ST_SEREA
LD   HL,ST_SREM
LD   A,(HL)
OR   A
LD   A,C
JR   NZ,ST_SEREA
OR   $80
ST_SEREA:
CALL OU_EMITB
JP   C,ST_OFAIL
JR   ST_SELOO
ST_SDONE:
LD   A,(ST_SMODE)
OR   A
JR   Z,ST_SDDON
CP   1
JP   NZ,ST_NEXT
XOR  A
CALL OU_EMITB
JP   ST_OTNEX
ST_SDDON:
CALL TK_NEXT
JP   C,ST_LFAIL
JP   ST_DDELI
ST_CSTR1:
LD   A,1
JR   ST_SDIR1
ST_PSTR1:
LD   A,2
JR   ST_SDIR1
ST_ISTR1:
LD   A,3
ST_SDIR1:
LD   (ST_SMODE),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_STRIN
JP   NZ,ST_DSTR1
JP   ST_DSTRI
ST_DS1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   (ST_DCNT),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JR   Z,ST_DRESE
CP   TK_COMMA
JP   NZ,ST_DDEL1
CALL TK_NEXT
JP   C,ST_LFAIL
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   A,L
LD   (ST_DFILL),A
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(ST_DCNT)
CALL OU_CCAP
JP   C,ST_OFAIL
ST_DFLOO:
LD   HL,(ST_DCNT)
LD   A,H
OR   L
JP   Z,ST_NEXT
LD   A,(ST_DFILL)
CALL OU_EMITB
JP   C,ST_OFAIL
LD   HL,(ST_DCNT)
DEC  HL
LD   (ST_DCNT),HL
JR   ST_DFLOO
ST_DRESE:
LD   HL,(ST_DCNT)
CALL OU_RESER
JP   ST_OTNEX
ST_ALIG1:
CALL ST_PEXPR
JP   C,ST_DFAIL
OR   A
JP   NZ,ST_DUNR1
LD   A,(EX_RVAL+2)
OR   A
JP   NZ,ST_DRANG
LD   A,H
OR   L
JP   Z,ST_DRANG
LD   (ST_DVAL),HL
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   NZ,ST_DDEL1
LD   HL,(OU_CURSO)
LD   (EX_LVAL),HL
XOR  A
LD   (EX_LVAL+2),A
LD   HL,(ST_DVAL)
LD   (EX_RVAL),HL
LD   (EX_RVAL+2),A
CALL EX_REMAI
JP   C,ST_DFAIL
LD   HL,(EX_RVAL)
LD   A,H
OR   L
JR   Z,ST_ACREA
EX   DE,HL
LD   HL,(ST_DVAL)
OR   A
SBC  HL,DE
ST_ACREA:
LD   (ST_DCNT),HL
XOR  A
LD   (ST_DFILL),A
LD   HL,(ST_DCNT)
CALL OU_CCAP
JP   C,ST_OFAIL
JR   ST_DFLOO
ST_SUCCE:
XOR  A
RET
;@ROUTINE IN B,HL OUT A,CARRY CLOBBERS BC,HL,IX,ZERO,SIGN,PARITY,HALFCARRY,DE
EN_RDIR:
LD   A,B
CP   6
JR   NC,EN_RDNFO
LD   DE,EN_SCRAT
CALL EN_R40PK
RET  C
LD   IX,ST_DTABL
LD   B,ST_CNT
LD   C,ST_EQU
EN_RDLOO:
LD   A,(EN_SCRAT)
CP   (IX+0)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+1)
CP   (IX+1)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+2)
CP   (IX+2)
JR   NZ,EN_RDNEX
LD   A,(EN_SCRAT+3)
CP   (IX+3)
JR   NZ,EN_RDNEX
LD   A,C
OR   A
RET
EN_RDNEX:
LD   DE,4
ADD  IX,DE
INC  C
DJNZ EN_RDLOO
EN_RDNFO:
XOR  A
SCF
RET
ST_DTABL:
DW $21FD,$0000
DW $6097,$0000
DW $1950,$0000
DW $1C98,$0000
DW $1BF8,$0000
DW $15CC,$7080
DW $670C,$7080
DW $3B4C,$7080
DW $0829,$2DF0
;@ROUTINE OUT A CLOBBERS DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
ST_STAKE:
LD   HL,(ST_SPTR)
LD   A,(ST_SPART)
CALL TK_SREAD
LD   HL,(ST_SPTR)
INC  HL
LD   (ST_SPTR),HL
LD   HL,ST_SREM
DEC  (HL)
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
ST_NTKIN:
CALL TK_NEXT
LD   A,(TK_REC+TK_KOFF)
RET
;@ROUTINE OUT A,HL,IX,CARRY CLOBBERS BC,DE,IY,ZERO,SIGN,PARITY,HALFCARRY
ST_PEXPR:
LD   BC,(OU_CURSO)
JP   EX_PDEFR
;@ROUTINE OUT CARRY CLOBBERS A,HL,ZERO,SIGN,PARITY,HALFCARRY
ST_CPOSI:
LD   A,(TK_REC+TK_POFF)
LD   (ST_EPART),A
LD   HL,(TK_REC+TK_SOFF)
LD   (ST_EOFF),HL
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
ST_LFAIL:
LD   (ST_DETAI),A
LD   A,(TK_EPART)
LD   (ST_EPART),A
LD   HL,(TK_EOFF)
LD   (ST_EOFF),HL
LD   A,ST_SLEXI
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS C,HL,ZERO,SIGN,PARITY,HALFCARRY
ST_EHERE:
CALL ST_CPOSI
LD   A,(TK_REC+TK_KOFF)
CP   TK_DIR
JR   NZ,ST_ESAVE
;@ROUTINE OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_UDIR:
LD   A,TK_DIR
LD   C,ST_SDIR
JR   ST_FAIL
;@ROUTINE OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_ESAVE:
LD   A,(TK_REC+TK_KOFF)
LD   C,ST_SEXP
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_SFAIL:
LD   C,ST_SSYM
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_IFAIL:
LD   C,ST_SINS
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_OFAIL:
LD   C,ST_SOUT
JR   ST_FAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_EFAIL:
LD   C,ST_SEQUA
JR   ST_FAIL
ST_EUNRE:
LD   A,EX_UNRES
JR   ST_EFAIL
ST_EDELI:
LD   A,EX_SEPRI
JR   ST_EFAIL
;@ROUTINE IN A OUT A,CARRY CLOBBERS C,HALFCARRY,ZERO,SIGN,PARITY
ST_DFAIL:
LD   C,ST_SDIR
;@ROUTINE IN A,C OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
ST_FAIL:
LD   (ST_DETAI),A
LD   A,C
SCF
RET
ST_DUNR1:
LD   A,EX_UNRES
JR   ST_DFAIL
ST_DRANG:
LD   A,EX_SRANG
JR   ST_DFAIL
ST_DEXP:
LD   A,EX_SEPRI
JR   ST_DFAIL
ST_DDEL1:
LD   A,(TK_REC+TK_KOFF)
JR   ST_DFAIL
ST_DSTR1:
LD   A,TK_STRIN
JR   ST_DFAIL
ST_CEND:
ST_WBEG:
ST_WUNIO: DS 20
ST_KEY EQU ST_WUNIO
ST_INS EQU ST_WUNIO
ST_MNEM EQU ST_WUNIO+6
ST_MVALI EQU ST_WUNIO+7
ST_DIR EQU ST_WUNIO+8
ST_DVALI EQU ST_WUNIO+9
ST_DETAI EQU ST_WUNIO+10
ST_EVAL EQU ST_WUNIO+6
ST_ESIGN EQU ST_WUNIO+8
ST_DWIDT EQU ST_WUNIO
ST_DPKIN EQU ST_WUNIO+1
ST_DADDE EQU ST_WUNIO+2
ST_DFILL EQU ST_WUNIO+3
ST_DVAL EQU ST_WUNIO+4
ST_DPKI1 EQU ST_DVAL
ST_DCNT EQU ST_WUNIO+6
ST_DKEY EQU ST_WUNIO+8
ST_DSYM EQU ST_WUNIO+10
ST_DADR EQU ST_WUNIO+12
ST_SPTR EQU ST_WUNIO+14
ST_SREM EQU ST_WUNIO+16
ST_SCNT EQU ST_WUNIO+17
ST_SNIBB EQU ST_WUNIO+18
ST_SMODE EQU ST_WUNIO+19
ST_EPART: DB 0
ST_EOFF: DW 0
ST_SPART: DB 0
ST_WEND:
DR_CBEG:
DR_SOK EQU 0
DR_SCFG EQU 1
DR_SSRC EQU 2
DR_SUNDE EQU 3
DR_SOUT EQU 4
DR_SINT EQU 5
DR_CPCNT EQU 1
DR_CTRAN EQU 2
DR_CPORD EQU 3
DR_CSRAN EQU 4
DR_CSRA1 EQU 5
DR_CPRAN EQU 6
DR_CORAN EQU 7
DR_PCAP EQU 255
DR_PDB EQU 5
DR_PORDI EQU 0
DR_PBEG EQU 1
DR_PEND EQU 3
DR_DPCNT EQU 0
DR_DPART EQU 1
DR_DSBEG EQU 3
DR_DSEND EQU 5
DR_DPBEG EQU 7
DR_DPEND EQU 9
DR_DTBEG EQU 11
DR_DTB EQU 13
DR_DESCB EQU 15
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
DR_ASM:
PUSH IX
POP  HL
LD   (DR_DESC),HL
XOR  A
LD   (DR_DETAI),A
LD   (DR_USYM),A
LD   (DR_USYM+1),A
LD   HL,ST_EPART
LD   (HL),A
INC  HL
LD   (HL),A
INC  HL
LD   (HL),A
CALL DR_VDESC
RET  C
LD   IX,(DR_DESC)
LD   C,DR_DSBEG
CALL DR_LRANG
CALL SY_RESET
JP   C,DR_IFAIL
LD   IX,(DR_DESC)
LD   C,DR_DPBEG
CALL DR_LRANG
CALL SY_RESE1
JP   C,DR_IFAIL
LD   IX,(DR_DESC)
LD   C,DR_DTBEG
CALL DR_LRANG
CALL OU_RESET
JP   C,DR_IFAIL
LD   IX,(DR_DESC)
CALL HS_BEG
JP   C,DR_BFAIL
LD   IX,(DR_DESC)
LD   A,(IX+DR_DPCNT)
LD   (DR_PREM),A
LD   L,(IX+DR_DPART)
LD   H,(IX+DR_DPART+1)
LD   (DR_PCURS),HL
XOR  A
LD   (DR_PINDE),A
DR_PLOOP:
LD   A,(DR_PREM)
OR   A
JR   Z,DR_FIN
LD   HL,(DR_PCURS)
INC  HL
LD   E,(HL)
INC  HL
LD   D,(HL)
INC  HL
PUSH DE
LD   E,(HL)
INC  HL
LD   D,(HL)
INC  HL
LD   (DR_PCURS),HL
POP  HL
LD   A,(DR_PINDE)
CALL TK_RESET
JR   C,DR_IABOR
CALL DR_APART
JR   C,DR_SFAIL
LD   HL,DR_PINDE
INC  (HL)
LD   HL,DR_PREM
DEC  (HL)
JR   DR_PLOOP
DR_FIN:
CALL DR_AFIN
JR   C,DR_FFAIL
LD   IX,(DR_DESC)
LD   HL,(OU_CURSO)
LD   DE,(OU_REM)
CALL HS_CMT
JR   C,DR_CFAIL
XOR  A
RET
DR_SFAIL:
LD   (DR_DETAI),A
LD   A,DR_SSRC
JR   DR_ABORT
DR_FFAIL:
LD   (DR_DETAI),A
CP   ST_SUNDE
LD   A,DR_SUNDE
JR   Z,DR_ABORT
LD   A,DR_SINT
JR   DR_ABORT
DR_IABOR:
LD   (DR_DETAI),A
LD   A,DR_SINT
JR   DR_ABORT
DR_CFAIL:
LD   (DR_DETAI),A
LD   A,DR_SOUT
DR_ABORT:
PUSH AF
CALL HS_ABORT
POP  AF
SCF
RET
DR_BFAIL:
LD   (DR_DETAI),A
LD   A,DR_SOUT
SCF
RET
DR_IFAIL:
LD   (DR_DETAI),A
LD   A,DR_SINT
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,IX,SIGN,PARITY,HALFCARRY,HL,ZERO,IY
DR_VDESC:
LD   IX,(DR_DESC)
LD   A,(IX+DR_DPCNT)
OR   A
JP   Z,DR_BPCNT
LD   (DR_PREM),A
LD   L,(IX+DR_DPART)
LD   H,(IX+DR_DPART+1)
LD   (DR_PCURS),HL
LD   C,A
LD   B,0
PUSH HL
LD   H,B
LD   L,C
ADD  HL,HL
ADD  HL,HL
ADD  HL,BC
POP  DE
ADD  HL,DE
JR   C,DR_BPTAB
XOR  A
LD   (DR_PINDE),A
DR_VPLOO:
LD   A,(DR_PREM)
OR   A
JR   Z,DR_VAREN
LD   HL,(DR_PCURS)
LD   A,(DR_PINDE)
CP   (HL)
JR   NZ,DR_BPORD
INC  HL
LD   E,(HL)
INC  HL
LD   D,(HL)
INC  HL
LD   C,(HL)
INC  HL
LD   B,(HL)
INC  HL
LD   (DR_PCURS),HL
LD   H,B
LD   L,C
OR   A
SBC  HL,DE
JR   C,DR_BSRAN
LD   HL,DR_PINDE
INC  (HL)
LD   HL,DR_PREM
DEC  (HL)
JR   DR_VPLOO
DR_VAREN:
LD   IX,(DR_DESC)
LD   C,DR_DSBEG
CALL DR_LRANG
CALL DR_VRANG
JR   C,DR_BSRA1
LD   IX,(DR_DESC)
LD   C,DR_DPBEG
CALL DR_LRANG
CALL DR_VRANG
JR   C,DR_BPRAN
LD   IX,(DR_DESC)
LD   C,DR_DTBEG
CALL DR_LRANG
ADD  HL,DE
JR   C,DR_BORAN
XOR  A
RET
;@ROUTINE IN IX,C OUT HL,DE CLOBBERS A,B,ZERO,SIGN,PARITY,HALFCARRY,CARRY
DR_LRANG:
PUSH IX
POP  HL
LD   B,0
ADD  HL,BC
LD   E,(HL)
INC  HL
LD   D,(HL)
INC  HL
LD   A,(HL)
INC  HL
LD   H,(HL)
LD   L,A
EX   DE,HL
RET
;@ROUTINE IN HL,DE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY,HL,DE
DR_VRANG:
EX   DE,HL
OR   A
SBC  HL,DE
RET  NC
SCF
RET
DR_BPCNT:
LD   A,DR_CPCNT
JR   DR_CFAI1
DR_BPTAB:
LD   A,DR_CTRAN
JR   DR_CFAI1
DR_BPORD:
LD   A,DR_CPORD
JR   DR_CFAI1
DR_BSRAN:
LD   A,DR_CSRAN
JR   DR_CFAI1
DR_BSRA1:
LD   A,DR_CSRA1
JR   DR_CFAI1
DR_BPRAN:
LD   A,DR_CPRAN
JR   DR_CFAI1
DR_BORAN:
LD   A,DR_CORAN
DR_CFAI1:
LD   (DR_DETAI),A
LD   A,DR_SCFG
SCF
RET
;@ROUTINE OUT A,CARRY,IX CLOBBERS DE,ZERO,SIGN,PARITY,HALFCARRY,HL,BC,IY
DR_AFIN:
LD   IX,(SY_ABAS1)
LD   DE,(SY_NEXT)
CALL AT_CIDE
JR   Z,DR_FNPEN
DR_FPLOO:
BIT  7,(IX+4)
JR   NZ,DR_FANCH
LD   BC,SY_RECB1
ADD  IX,BC
CALL AT_CIDE
JR   NZ,DR_FPLOO
JR   DR_FINT
DR_FANCH:
LD   L,(IX+0)
LD   H,(IX+1)
LD   (DR_USYM),HL
CALL DR_VSPTR
JR   C,DR_FINT
LD   IY,(DR_USYM)
BIT  6,(IY+5)
JR   NZ,DR_FINT
LD   A,(IX+4)
AND  SY_KMASK
JR   Z,DR_FINT
CP   PT_KHB+1
JR   NC,DR_FINT
LD   A,(IX+SY_PMASK)
LD   (ST_EPART),A
LD   L,(IY+SY_VALLO)
LD   H,(IY+SY_VALHI)
LD   (ST_EOFF),HL
XOR  A
LD   (ST_DETAI),A
LD   IX,(DR_USYM)
LD   A,ST_SUNDE
SCF
RET
DR_FNPEN:
CALL SY_VSCOP
JR   C,DR_FINT
LD   IX,(SY_ABASE)
LD   DE,(SY_GEND)
DR_FGLOO:
CALL AT_CIDE
JR   Z,DR_FSUCC
BIT  6,(IX+5)
JR   Z,DR_FINT
LD   BC,SY_RECB
ADD  IX,BC
JR   DR_FGLOO
DR_FSUCC:
XOR  A
RET
DR_FINT:
XOR  A
LD   (DR_USYM),A
LD   (DR_USYM+1),A
LD   A,ST_SINT
SCF
RET
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC
DR_VSPTR:
PUSH HL
LD   DE,(SY_ABASE)
OR   A
SBC  HL,DE
POP  HL
JR   C,DR_VPPTR
PUSH HL
LD   DE,(SY_GEND)
OR   A
SBC  HL,DE
POP  HL
JR   NC,DR_VPPTR
LD   DE,(SY_ABASE)
OR   A
SBC  HL,DE
LD   A,L
AND  SY_RECB-1
RET  Z
SCF
RET
DR_VPPTR:
PUSH HL
LD   DE,(SY_LBEG)
OR   A
SBC  HL,DE
POP  HL
RET  C
PUSH HL
LD   DE,(SY_AEND)
OR   A
SBC  HL,DE
POP  HL
JR   NC,DR_ISPTR
LD   DE,(SY_AEND)
EX   DE,HL
OR   A
SBC  HL,DE
LD   A,L
AND  SY_RECB-1
RET  Z
DR_ISPTR:
SCF
RET
DR_CEND:
DR_WBEG:
DR_DESC: DW 0
DR_PCURS: DW 0
DR_PREM: DB 0
DR_PINDE: DB 0
DR_DETAI: DB 0
DR_USYM: DW 0
DR_WEND:
HS_SCBEG:
;@ROUTINE IN IX OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_BEG:
NOP
;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_IB:
NOP
;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_PB:
NOP
;@ROUTINE IN C,DE,HL OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_PW:
NOP
;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_CMT:
NOP
;@ROUTINE OUT A,CARRY CLOBBERS HALFCARRY,ZERO,SIGN,PARITY
HS_ABORT:
HS_FCLOS:
SCF
SBC  A,A
RET
HS_SCEND:
HS_REND:
