EX_OSTAC: DS EX_OPERB*EX_OCAP
EX_WEND:
PT_CBEG:
PT_KINDB EQU 1
PT_KINDW EQU 2
PT_KRELA EQU 3
PT_KDISP EQU 4
PT_KTB EQU 5
PT_KLB EQU 6
PT_KHB EQU 7
;@ROUTINE IN IX,A OUT A,B,CARRY CLOBBERS HL,SIGN,PARITY,HALFCARRY,DE,ZERO
PT_LOCAT:
CP   3
JR   NC,.INVALID
LD   E,A
LD   D,0
PUSH DE
CALL EN_LEN
POP  DE
JR   C,.INVALID
LD   B,A
LD   HL,EN_OP0
ADD  HL,DE
PUSH IX
POP  DE
ADD  HL,DE
LD   A,(HL)
SUB  EN_IIX
CP   7
JR   NC,.INVALID
LD   E,A
LD   D,0
LD   HL,PT_OKIND
ADD  HL,DE
LD   A,(HL)
OR   A
JR   Z,.INVALID
CP   PT_KDISP
JR   Z,.DISPLACE
DEC  B
CP   PT_KINDW
JR   NZ,.READY
DEC  B
.READY:
OR   A
RET
.INVALID:
XOR  A
SCF
RET
.DISPLACE:
LD   B,2
OR   A
RET
PT_OKIND:
DB PT_KDISP,PT_KDISP
DB PT_KINDW,PT_KINDB,PT_KINDW
DB 0,PT_KRELA
PT_CEND:
PR_CBEG:
PR_SOK EQU 0
PR_SEOF EQU 1
PR_SLEXI EQU 2
PR_SEMNE EQU 3
PR_SUMNE EQU 4
PR_SEOP EQU 5
PR_SUOP EQU 6
PR_SEDEL EQU 7
PR_STMOP EQU 8
PR_SIFOR EQU 9
PR_SVRAN EQU 10
PR_SRRAN EQU 11
PR_SINT EQU 12
PR_SEXPR EQU 13
PR_SUNPA EQU 14
PR_SSYM EQU 15
PR_SRCAP EQU 16
PR_SPCAP EQU 17
PR_RCAP EQU 2
PR_BRB EQU 13
PR_PRB EQU 9
PR_BKEY EQU 0
PR_BADDE EQU 6
PR_BLDOP EQU 7
PR_BKIND EQU 8
PR_BPOFF EQU 9
PR_BPART EQU 10
PR_BSOFF EQU 11
PR_RSYM EQU 0
PR_RADDE EQU 2
PR_REFOP EQU 3
PR_RKIND EQU 4
PR_RPOFF EQU 5
PR_RPART EQU 6
PR_RSOFF EQU 7
PR_GNUMB EQU 240
PR_GPNUM EQU 241
PR_GC EQU 242
;@ROUTINE IN A,BC,DE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_PUB:
PUSH AF
LD   (PR_IADR),BC
LD   (PR_DST),DE
XOR  A
LD   (PR_RCNT),A
CALL PR_ISCRA
POP  AF
LD   (PR_SCRAT+EN_MNEM),A
JR   PR_POPER
;@ROUTINE IN BC,DE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_PARSE:
LD   (PR_IADR),BC
LD   (PR_DST),DE
XOR  A
LD   (PR_RCNT),A
CALL PR_ISCRA
CALL PR_NTOK
RET  C
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOF
JR   Z,PR_EOF
CP   TK_NAME
JP   NZ,PR_EMNEM
LD   A,(TK_REC+TK_POFF)
LD   (PR_IPART),A
LD   HL,(TK_REC+TK_SOFF)
LD   (PR_IOFF),HL
CALL TK_LLEXE
CALL EN_RECOG
JP   C,PR_UMNEM
LD   (PR_SCRAT+EN_MNEM),A
CALL PR_NTOK
RET  C
PR_POPER:
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JR   Z,PR_POPE1
PR_OLOOP:
LD   A,(PR_OPCNT)
CP   3
JP   NC,PR_TMOPE
CALL PR_SOP
CALL PR_POP
RET  C
LD   HL,PR_OPCNT
INC  (HL)
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JR   Z,PR_POPE1
CP   TK_COMMA
JP   NZ,PR_EDELI
CALL PR_NTOK
RET  C
LD   A,(TK_REC+TK_KOFF)
CP   TK_EOL
JP   Z,PR_EXPOP
JR   PR_OLOOP
PR_POPE1:
CALL PR_NAALI
RET  C
CALL PR_NNUMB
RET  C
CALL PR_VCAND
RET  C
LD   (PR_ILEN),A
CALL PR_CCVAL
RET  C
CALL PR_FREFE
RET  C
JP   PR_CMT
PR_EOF:
LD   A,PR_SEOF
OR   A
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,B,HL,SIGN,PARITY,HALFCARRY
PR_ISCRA:
LD   HL,PR_SCRAT
XOR  A
LD   (HL),A
INC  HL
LD   B,3
LD   A,EN_NONE
.IOPERAND:
LD   (HL),A
INC  HL
DJNZ .IOPERAND
XOR  A
LD   B,6
.IVALUES:
LD   (HL),A
INC  HL
DJNZ .IVALUES
LD   (PR_OPCNT),A
LD   (PR_FMASK),A
LD   (PR_CMASK),A
LD   (PR_RBCNT),A
LD   (PR_UMASK),A
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_NTOK:
CALL TK_NEXT
RET  NC
LD   A,(TK_EPART)
LD   (PR_EPART),A
LD   HL,(TK_EOFF)
LD   (PR_EOFF),HL
LD   A,PR_SLEXI
SCF
RET
;@ROUTINE IN A OUT CARRY,ZERO CLOBBERS A,DE,HL,SIGN,PARITY,HALFCARRY
PR_SOP:
LD   E,A
LD   D,0
LD   HL,PR_SCRAT+EN_OP0
ADD  HL,DE
LD   (PR_CPTR),HL
LD   A,E
ADD  A,A
LD   E,A
LD   HL,PR_SCRAT+EN_VAL0
ADD  HL,DE
LD   (PR_VPTR),HL
RET
;@ROUTINE IN A OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY
PR_IESTA:
CP   TK_NUMBE
RET  Z
CP   TK_CUR
RET  Z
CP   TK_PLUS
RET  Z
CP   TK_MINUS
RET  Z
CP   TK_TILDE
RET  Z
SCF
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_POP:
LD   A,(TK_REC+TK_KOFF)
CP   TK_NAME
JR   Z,.OPNAME
CALL PR_IESTA
JR   NC,.OPEXPR
CP   TK_LPARE
JP   Z,PR_PMEMO
JP   PR_EXPOP
.OPNAME:
CALL PR_LOW
JR   C,.OPEXPR
LD   HL,(PR_CPTR)
LD   (HL),A
LD   (PR_LCLAS),A
CALL PR_NTOK
RET  C
LD   A,(PR_LCLAS)
CP   EN_AF
JR   NZ,.OPPARSED
LD   A,(TK_REC+TK_KOFF)
CP   TK_APOST
JR   NZ,.OPPARSED
LD   HL,(PR_CPTR)
LD   (HL),EN_APRIM
JR   PR_NTOK
.OPPARSED:
XOR  A
RET
.OPEXPR:
CALL PR_PEXPR
RET  C
LD   A,PR_GNUMB
LD   HL,(PR_CPTR)
LD   (HL),A
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_PEXPR:
LD   BC,(PR_IADR)
CALL EX_PDEFR
JR   C,PR_EFAIL
CP   EX_UNRES
JR   Z,PR_AREF
;@ROUTINE IN HL OUT CARRY,ZERO CLOBBERS DE,SIGN,PARITY,HALFCARRY,A
PR_SHVAL:
LD   DE,(PR_VPTR)
LD   A,L
LD   (DE),A
INC  DE
LD   A,H
LD   (DE),A
XOR  A
RET
;@ROUTINE IN IX,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IX
PR_AREF:
LD   (PR_RASCR),HL
LD   A,(PR_RBCNT)
CP   PR_RCAP
JR   NC,PR_RCFAI
CALL PR_BRADR
PUSH IX
POP  HL
LD   BC,6
LDIR
LD   HL,(PR_RASCR)
LD   A,L
LD   (DE),A
INC  DE
LD   A,(PR_OPCNT)
LD   (DE),A
INC  DE
LD   A,(EX_RUNRE)
LD   (DE),A
INC  DE
XOR  A
LD   (DE),A
INC  DE
LD   A,(EX_SPART)
LD   (DE),A
INC  DE
LD   HL,(EX_SOFF)
LD   A,L
LD   (DE),A
INC  DE
LD   A,H
LD   (DE),A
LD   A,(PR_OPCNT)
CALL PR_IBIT
LD   HL,PR_UMASK
OR   (HL)
LD   (HL),A
LD   HL,PR_RBCNT
INC  (HL)
LD   HL,0
JR   PR_SHVAL
PR_RCFAI:
LD   A,PR_SRCAP
JP   PR_FESYM
;@ROUTINE IN A OUT DE CLOBBERS HL,A,F
PR_BRADR:
LD   DE,PR_RBLD
OR   A
RET  Z
LD   HL,PR_BRB
ADD  HL,DE
EX   DE,HL
RET
PR_EFAIL:
LD   (PR_ESTA1),A
LD   A,(EX_EPART)
LD   (PR_EPART),A
LD   HL,(EX_EOFF)
LD   (PR_EOFF),HL
LD   A,PR_SEXPR
LD   (PR_ESTAT),A
SCF
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
PR_LOW:
CALL TK_LLEXE
CP   4
JR   NC,.UOP
LD   DE,PR_NKEY
CALL EN_R40PK
JR   C,.UOP
LD   DE,(PR_NKEY)
LD   HL,PR_OWTAB
LD   B,PR_OWCNT
.LOLOOP:
LD   A,(HL)
CP   E
INC  HL
JR   NZ,.LOSHI
LD   A,(HL)
CP   D
JR   Z,.LOFOUND
.LOSHI:
INC  HL
INC  HL
DJNZ .LOLOOP
.UOP:
LD   A,PR_SUOP
JP   PR_FHERE
.LOFOUND:
INC  HL
LD   A,(HL)
OR   A
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_PMEMO:
CALL PR_NTOK
RET  C
LD   A,(TK_REC+TK_KOFF)
CALL PR_IESTA
JR   NC,.MEXPR
CP   TK_LPARE
JR   Z,.MEXPR
CP   TK_NAME
JP   NZ,PR_EXPOP
CALL PR_LOW
JR   C,.MEXPR
LD   (PR_MBASE),A
CALL PR_NTOK
RET  C
LD   A,(PR_MBASE)
CP   PR_GC
JR   Z,.MPC
CP   EN_BC
JR   Z,.MEMORYBC
CP   EN_DE
JR   Z,.MEMORYDE
CP   EN_HL
JR   Z,.MEMORYHL
CP   EN_SP
JR   Z,.MEMORYSP
CP   EN_IX
JR   Z,.MEMORYIX
CP   EN_IY
JR   Z,.MEMORYIY
JP   PR_UOP
.MEXPR:
CALL PR_PEXPR
RET  C
LD   HL,(PR_CPTR)
LD   (HL),PR_GPNUM
JR   PR_RRPAR
.MPC:
LD   A,EN_PORTC
JR   .MSIMPLE
.MEMORYBC:
LD   A,EN_MEMBC
JR   .MSIMPLE
.MEMORYDE:
LD   A,EN_MEMDE
JR   .MSIMPLE
.MEMORYHL:
LD   A,EN_MEMHL
JR   .MSIMPLE
.MEMORYSP:
LD   A,EN_MEMSP
.MSIMPLE:
LD   HL,(PR_CPTR)
LD   (HL),A
JR   PR_RRPAR
.MEMORYIX:
LD   B,EN_MEMIX
LD   A,EN_IIX
LD   (PR_ICLAS),A
JR   .MINDEX
.MEMORYIY:
LD   B,EN_MEMIY
LD   A,EN_IIY
LD   (PR_ICLAS),A
.MINDEX:
LD   A,(TK_REC+TK_KOFF)
CP   TK_RPARE
JR   Z,.MIPLAIN
CP   TK_PLUS
JR   Z,.MIEXPR
CP   TK_MINUS
JP   NZ,PR_EDELI
.MIEXPR:
CALL PR_PEXPR
RET  C
LD   HL,(PR_CPTR)
LD   A,(PR_ICLAS)
LD   (HL),A
JR   PR_RRPAR
.MIPLAIN:
LD   HL,(PR_CPTR)
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MJP
LD   A,B
JR   Z,.MIPSTORE
LD   A,(PR_ICLAS)
.MIPSTORE:
LD   (HL),A
JP   PR_NTOK
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,IY,ZERO,SIGN,PARITY,HALFCARRY
PR_RRPAR:
LD   A,(TK_REC+TK_KOFF)
CP   TK_RPARE
JP   NZ,PR_EDELI
JP   PR_NTOK
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,DE,HL,SIGN,PARITY,HALFCARRY
PR_STVAL:
LD   HL,(TK_REC+TK_VOFF)
JP   PR_SHVAL
;@ROUTINE OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,HL,ZERO,BC,DE
PR_NAALI:
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MADD
JR   C,.ASUCCESS
CP   AT_MCP+1
JR   NC,.ASUCCESS
LD   A,(PR_OPCNT)
CP   1
JR   NZ,.MAALIAS
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MADD
JR   Z,.RACCUMUL
CP   AT_MADC
JR   Z,.RACCUMUL
CP   AT_MSBC
JR   NZ,.ASUCCESS
.RACCUMUL:
LD   A,PR_SIFOR
JP   PR_FBEG
.MAALIAS:
CP   2
JR   NZ,.ASUCCESS
LD   A,(PR_SCRAT+EN_OP0)
CP   EN_A
JR   NZ,.ASUCCESS
LD   A,(PR_SCRAT+EN_OP1)
LD   (PR_SCRAT+EN_OP0),A
LD   HL,(PR_SCRAT+EN_VAL1)
LD   (PR_SCRAT+EN_VAL0),HL
LD   A,EN_NONE
LD   (PR_SCRAT+EN_OP1),A
XOR  A
LD   (PR_SCRAT+EN_VAL1),A
LD   (PR_SCRAT+EN_VAL1+1),A
INC  A
LD   (PR_OPCNT),A
LD   A,(PR_UMASK)
AND  2
JR   Z,.ASUCCESS
LD   A,1
LD   (PR_UMASK),A
CALL PR_RAREF
.ASUCCESS:
XOR  A
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS B,SIGN,PARITY,HALFCARRY,DE,HL,A
PR_RAREF:
XOR  A
LD   B,A
.RALOOP:
LD   A,(PR_RBCNT)
CP   B
RET  Z
LD   A,B
CALL PR_BRADR
LD   HL,PR_BLDOP
ADD  HL,DE
LD   A,(HL)
CP   1
JR   NZ,.RANEXT
LD   (HL),0
.RANEXT:
INC  B
JR   .RALOOP
;@ROUTINE OUT A,CARRY CLOBBERS BC,ZERO,SIGN,PARITY,HALFCARRY,DE,HL,IX,IY
PR_NNUMB:
XOR  A
LD   (PR_FMASK),A
LD   (PR_CMASK),A
LD   (PR_SINDE),A
.NLOOP:
LD   A,(PR_SINDE)
LD   B,A
LD   A,(PR_OPCNT)
CP   B
RET  Z
LD   A,B
CALL PR_SOP
LD   HL,(PR_CPTR)
LD   A,(HL)
CP   PR_GC
JR   Z,.NC
CP   PR_GPNUM
JR   Z,.NPNUMBER
CP   PR_GNUMB
JR   NZ,.NNEXT
CALL PR_NBNUM
RET  C
JR   .NNEXT
.NC:
LD   (HL),EN_C
LD   A,(PR_SINDE)
CALL PR_IBIT
LD   HL,PR_CMASK
OR   (HL)
LD   (HL),A
JR   .NNEXT
.NPNUMBER:
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MIN
JR   Z,.NPB
CP   AT_MOUT
JR   Z,.NPB
LD   HL,(PR_CPTR)
LD   (HL),EN_MABS
JR   .NNEXT
.NPB:
CALL PR_RBVAL
RET  C
LD   HL,(PR_CPTR)
LD   (HL),EN_IMM8
.NNEXT:
LD   HL,PR_SINDE
INC  (HL)
JR   .NLOOP
;@ROUTINE OUT A,CARRY CLOBBERS HL,SIGN,PARITY,HALFCARRY,ZERO,BC,DE
PR_NBNUM:
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MIM
JR   Z,.NIM
CP   AT_MRST
JR   Z,.NRST
CP   AT_MBIT
JR   C,.NBRANCH
CP   AT_MSET+1
JR   C,.NBIT
.NBRANCH:
LD   A,(PR_SCRAT+EN_MNEM)
CP   AT_MJP
JR   Z,.NW
CP   AT_MCALL
JR   Z,.NW
CP   AT_MJR
JR   Z,.NRELATIV
CP   AT_MDJNZ
JR   Z,.NRELATIV
CP   AT_MOUT
JR   NZ,.NFLEXIBL
CALL PR_SVAL
LD   A,H
OR   L
JR   NZ,.NFLEXIBL
LD   HL,(PR_CPTR)
LD   (HL),EN_ZERO
XOR  A
RET
.NIM:
CALL PR_SVAL
LD   A,H
OR   A
JP   NZ,PR_VRANG
LD   A,L
CP   3
JP   NC,PR_VRANG
ADD  A,EN_IM0
JR   .SENUM
.NRST:
CALL PR_SVAL
LD   A,H
OR   A
JP   NZ,PR_VRANG
LD   A,L
CP   57
JP   NC,PR_VRANG
AND  7
JP   NZ,PR_VRANG
LD   A,L
RRCA
RRCA
RRCA
AND  7
ADD  A,EN_RST0
JR   .SENUM
.NBIT:
LD   A,(PR_SINDE)
OR   A
JR   NZ,.NFLEXIBL
CALL PR_SVAL
LD   A,H
OR   A
JP   NZ,PR_VRANG
LD   A,L
CP   8
JP   NC,PR_VRANG
ADD  A,EN_BIT0
.SENUM:
LD   HL,(PR_CPTR)
LD   (HL),A
CALL PR_CSVAL
XOR  A
RET
.NW:
LD   HL,(PR_CPTR)
LD   (HL),EN_IMM16
XOR  A
RET
.NRELATIV:
LD   HL,(PR_CPTR)
LD   (HL),EN_REL8
XOR  A
RET
.NFLEXIBL:
LD   HL,(PR_CPTR)
LD   (HL),EN_IMM8
LD   A,(PR_SINDE)
CALL PR_IBIT
LD   HL,PR_FMASK
OR   (HL)
LD   (HL),A
XOR  A
RET
;@ROUTINE OUT HL CLOBBERS A
PR_SVAL:
LD   HL,(PR_VPTR)
LD   A,(HL)
INC  HL
LD   H,(HL)
LD   L,A
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS A,HL,SIGN,PARITY,HALFCARRY
PR_CSVAL:
LD   HL,(PR_VPTR)
XOR  A
LD   (HL),A
INC  HL
LD   (HL),A
RET
;@ROUTINE OUT A,CARRY CLOBBERS HL,ZERO,SIGN,PARITY,HALFCARRY,BC,DE,IX,IY
PR_RBVAL:
CALL PR_SVAL
LD   A,H
OR   A
RET  Z
JP   PR_VRANG
;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
PR_IBIT:
OR   A
JR   NZ,.IBDOUBLE
INC  A
RET
.IBDOUBLE:
ADD  A,A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
PR_VCAND:
CALL PR_VCUR
RET  NC
CALL PR_TCOND
RET  NC
LD   A,(PR_FMASK)
OR   A
JR   Z,.IFORM
CALL PR_WFLEX
CALL PR_VCUR
RET  NC
CALL PR_TCOND
RET  NC
.IFORM:
LD   A,PR_SIFOR
JP   PR_FBEG
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
PR_VCUR:
LD   IX,PR_SCRAT
JP   EN_VFORM
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,IX,ZERO,SIGN,PARITY,HALFCARRY,HL
PR_TCOND:
XOR  A
LD   (PR_SINDE),A
.TCLOOP:
LD   A,(PR_SINDE)
CP   3
JR   Z,.TCFAILED
LD   B,A
CALL PR_IBIT
LD   HL,PR_CMASK
AND  (HL)
JR   Z,.TCNEXT
LD   A,B
CALL PR_SOP
LD   HL,(PR_CPTR)
LD   (HL),EN_CC
PUSH HL
CALL PR_VCUR
POP  HL
RET  NC
LD   (HL),EN_C
.TCNEXT:
LD   HL,PR_SINDE
INC  (HL)
JR   .TCLOOP
.TCFAILED:
SCF
RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,B,DE,HL,A
PR_WFLEX:
XOR  A
LD   (PR_SINDE),A
.WLOOP:
LD   A,(PR_SINDE)
CP   3
RET  Z
LD   B,A
CALL PR_IBIT
LD   HL,PR_FMASK
AND  (HL)
JR   Z,.WNEXT
LD   A,B
CALL PR_SOP
LD   HL,(PR_CPTR)
LD   (HL),EN_IMM16
.WNEXT:
LD   HL,PR_SINDE
INC  (HL)
JR   .WLOOP
;@ROUTINE OUT A,CARRY CLOBBERS BC,ZERO,SIGN,PARITY,HALFCARRY,DE,HL,IX,IY
PR_CCVAL:
XOR  A
LD   (PR_SINDE),A
.CVLOOP:
LD   A,(PR_SINDE)
LD   B,A
LD   A,(PR_OPCNT)
CP   B
RET  Z
LD   A,B
CALL PR_SOP
LD   A,(PR_SINDE)
CALL PR_IBIT
LD   HL,PR_UMASK
AND  (HL)
JR   NZ,.CVNEXT
LD   HL,(PR_CPTR)
LD   A,(HL)
CP   EN_IMM8
JR   Z,.CHKB
CP   EN_REL8
JR   Z,.CRELATIV
CP   EN_IIX
JR   Z,.CDISPLAC
CP   EN_IIY
JR   Z,.CDISPLAC
.CVNEXT:
LD   HL,PR_SINDE
INC  (HL)
JR   .CVLOOP
.CHKB:
CALL PR_RBVAL
RET  C
JR   .CVNEXT
.CDISPLAC:
CALL PR_SVAL
LD   A,H
OR   A
JR   Z,.CDPOSITI
INC  A
JP   NZ,PR_VRANG
BIT  7,L
JP   Z,PR_VRANG
JR   .CVNEXT
.CDPOSITI:
BIT  7,L
JP   NZ,PR_VRANG
JR   .CVNEXT
.CRELATIV:
CALL PR_SVAL
LD   DE,(PR_IADR)
LD   A,(PR_ILEN)
ADD  A,E
LD   E,A
JR   NC,.RBREADY
INC  D
.RBREADY:
OR   A
SBC  HL,DE
LD   A,H
OR   A
JR   Z,.RPOSITIV
INC  A
JP   NZ,PR_RRANG
BIT  7,L
JP   Z,PR_RRANG
JR   .RSTORE
.RPOSITIV:
BIT  7,L
JP   NZ,PR_RRANG
.RSTORE:
CALL PR_SHVAL
JR   .CVNEXT
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY,IY
PR_FREFE:
XOR  A
LD   (PR_RSCAN),A
.LRLOOP:
LD   A,(PR_RBCNT)
LD   B,A
LD   A,(PR_RSCAN)
CP   B
JR   Z,.PREFEREN
CALL PR_BRADR
LD   HL,PR_BLDOP
ADD  HL,DE
LD   A,(HL)
LD   IX,PR_SCRAT
CALL PT_LOCAT
JR   C,.UREF
LD   (PR_RKSCR),A
LD   A,B
LD   (PR_ROSCR),A
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   HL,PR_BKIND
ADD  HL,DE
LD   A,(HL)
CP   EX_FLO
JR   Z,.LLREF
CP   EX_FHI
JR   Z,.LHREF
LD   A,(PR_RKSCR)
JR   .LSKIND
.LLREF:
LD   A,PT_KLB
JR   .LBFUNCTI
.LHREF:
LD   A,PT_KHB
.LBFUNCTI:
PUSH AF
LD   A,(PR_RKSCR)
CP   PT_KRELA
JR   Z,.LBFINVAL
CP   PT_KDISP
JR   Z,.LBFINVAL
POP  AF
.LSKIND:
LD   (HL),A
INC  HL
LD   A,(PR_ROSCR)
LD   (HL),A
LD   HL,PR_RSCAN
INC  (HL)
JR   .LRLOOP
.LBFINVAL:
POP  AF
.UREF:
LD   A,PR_SUNPA
JP   PR_FREF
.PREFEREN:
XOR  A
LD   (PR_RMCNT),A
LD   (PR_RSKEY),A
LD   A,(PR_RBCNT)
OR   A
RET  Z
CP   2
JR   NZ,.PFIRST
CALL PR_CRKEY
SBC  A,A
INC  A
LD   (PR_RSKEY),A
.PFIRST:
XOR  A
LD   (PR_RSCAN),A
CALL PR_PREF
RET  C
LD   A,(PR_RBCNT)
CP   2
JR   NZ,.PCAP
LD   A,(PR_RSKEY)
OR   A
JR   NZ,.PCAP
LD   A,1
LD   (PR_RSCAN),A
CALL PR_PREF
RET  C
.PCAP:
LD   A,(PR_RMCNT)
OR   A
JR   Z,.PREFERE1
ADD  A,A
ADD  A,A
ADD  A,A
LD   B,A
LD   HL,(SY_LBEG)
LD   DE,(SY_GEND)
CALL AT_RHCAP
JP   C,PR_SCFAI
.PREFERE1:
XOR  A
LD   (PR_RSCAN),A
.PRLOOP:
LD   A,(PR_RBCNT)
LD   B,A
LD   A,(PR_RSCAN)
CP   B
JR   Z,.PRCNT
CALL PR_BRADR
LD   H,D
LD   L,E
CALL SY_REF
JP   C,PR_USFAI
LD   A,B
OR   A
JR   Z,.RDREADY
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   HL,PR_BSOFF
ADD  HL,DE
LD   A,(HL)
LD   (IX+SY_VALLO),A
INC  HL
LD   A,(HL)
LD   (IX+SY_VALHI),A
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   A,SY_DANCH
LD   HL,PR_BKIND
ADD  HL,DE
OR   (HL)
LD   (HL),A
.RDREADY:
PUSH IX
POP  BC
LD   A,(PR_RSCAN)
CALL PR_PRADR
LD   (HL),C
INC  HL
LD   (HL),B
INC  HL
PUSH HL
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   HL,PR_BADDE
ADD  HL,DE
POP  DE
LD   BC,7
LDIR
LD   HL,PR_RSCAN
INC  (HL)
JR   .PRLOOP
.PRCNT:
LD   A,(PR_RBCNT)
LD   (PR_RCNT),A
XOR  A
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY,IY
PR_PREF:
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   H,D
LD   L,E
CALL SY_FIND
RET  NC
CP   SY_SNFOU
JR   NZ,PR_SFAIL
LD   HL,PR_RMCNT
INC  (HL)
XOR  A
RET
PR_SFAIL:
LD   (PR_SSTAT),A
LD   A,PR_SSYM
JP   PR_FREF
;@ROUTINE OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,B
PR_CRKEY:
LD   HL,PR_RBLD
LD   DE,PR_RBLD+PR_BRB
LD   B,6
.CRKLOOP:
LD   A,(DE)
CP   (HL)
SCF
RET  NZ
INC  DE
INC  HL
DJNZ .CRKLOOP
OR   A
RET
PR_SCFAI:
LD   A,SY_SSCAP
JR   PR_SFAIL
PR_USFAI:
LD   (PR_SSTAT),A
LD   A,PR_SINT
JP   PR_FREF
;@ROUTINE IN A OUT HL CLOBBERS DE,A,F
PR_PRADR:
LD   HL,PR_REFER
OR   A
RET  Z
LD   DE,PR_PRB
ADD  HL,DE
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO,IX
PR_CREFE:
LD   A,(PR_RCNT)
LD   B,A
ADD  A,A
ADD  A,B
ADD  A,A
ADD  A,B
LD   B,A
LD   HL,(SY_AEND1)
LD   DE,(SY_NEXT)
CALL AT_RHCAP
JR   C,PR_QCAP
.QCSYMBOL:
XOR  A
LD   (PR_RSCAN),A
.QCLOOP:
LD   A,(PR_RCNT)
LD   B,A
LD   A,(PR_RSCAN)
CP   B
JR   Z,.QPDONE
CALL PR_PRADR
LD   E,(HL)
INC  HL
LD   D,(HL)
EX   DE,HL
LD   DE,5
ADD  HL,DE
BIT  6,(HL)
JR   NZ,PR_QADEF
LD   HL,PR_RSCAN
INC  (HL)
JR   .QCLOOP
.QPDONE:
XOR  A
RET
;@ROUTINE IN DE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
PR_QREFE:
LD   (PR_QBASE),DE
CALL PR_CREFE
RET  C
.QUEUECMT:
XOR  A
LD   (PR_RSCAN),A
.QLOOP:
LD   A,(PR_RCNT)
LD   B,A
LD   A,(PR_RSCAN)
CP   B
JR   Z,.QDONE
CALL PR_PRADR
LD   E,(HL)
INC  HL
LD   D,(HL)
PUSH DE
POP  IX
INC  HL
LD   C,(HL)
INC  HL
INC  HL
LD   B,(HL)
INC  HL
LD   A,(HL)
LD   (PR_ROSCR),A
INC  HL
LD   A,(HL)
LD   (PR_RKSCR),A
LD   A,(PR_ROSCR)
LD   HL,(PR_QBASE)
LD   E,A
LD   D,0
ADD  HL,DE
EX   DE,HL
LD   A,(PR_RKSCR)
CALL SY_ADD
RET  C
LD   HL,PR_RSCAN
INC  (HL)
JR   .QLOOP
.QDONE:
XOR  A
RET
PR_QCAP:
LD   A,SY_SPCAP
SCF
RET
PR_QADEF:
LD   A,SY_SADEF
SCF
RET
PR_FESYM:
LD   (PR_ESTAT),A
LD   A,(EX_SPART)
LD   (PR_EPART),A
LD   HL,(EX_SOFF)
LD   (PR_EOFF),HL
LD   A,(PR_ESTAT)
SCF
RET
PR_FREF:
LD   (PR_ESTAT),A
LD   A,(PR_RSCAN)
CALL PR_BRADR
LD   HL,PR_BPART
ADD  HL,DE
LD   A,(HL)
LD   (PR_EPART),A
INC  HL
LD   E,(HL)
INC  HL
LD   D,(HL)
LD   (PR_EOFF),DE
LD   A,(PR_ESTAT)
SCF
RET
;@ROUTINE OUT A,IX,CARRY CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY,ZERO
PR_CMT:
LD   HL,PR_SCRAT
LD   DE,(PR_DST)
LD   BC,10
LDIR
LD   IX,(PR_DST)
XOR  A
RET
PR_EMNEM:
LD   A,PR_SEMNE
JR   PR_FHERE
PR_UMNEM:
LD   A,PR_SUMNE
JR   PR_FHERE
PR_EXPOP:
LD   A,PR_SEOP
JR   PR_FHERE
PR_UOP:
LD   A,PR_SUOP
JR   PR_FHERE
PR_EDELI:
LD   A,PR_SEDEL
JR   PR_FHERE
PR_TMOPE:
LD   A,PR_STMOP
JR   PR_FHERE
PR_VRANG:
LD   A,PR_SVRAN
JR   PR_FHERE
PR_RRANG:
LD   A,PR_SRRAN
JR   PR_FBEG
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
PR_FHERE:
LD   HL,TK_REC+TK_POFF
JR   PR_FPOSI
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
PR_FBEG:
LD   HL,PR_IPART
;@ROUTINE IN A OUT A,CARRY CLOBBERS HL,HALFCARRY,ZERO,SIGN,PARITY
PR_FPOSI:
LD   (PR_ESTAT),A
PUSH BC
PUSH DE
LD   DE,PR_EPART
LD   BC,3
LDIR
POP  DE
POP  BC
LD   A,(PR_ESTAT)
SCF
RET
PR_RCEND:
PR_IBEG:
PR_OWCNT EQU 27
PR_OWTAB:
DW  $0640
DB  EN_A
DW  $0730
DB  EN_AF
DW  $0C80
DB  EN_B
DW  $0CF8
DB  EN_BC
DW  $12C0
DB  PR_GC
DW  $1900
DB  EN_D
DW  $19C8
DB  EN_DE
DW  $1F40
DB  EN_E
DW  $3200
DB  EN_H
DW  $33E0
DB  EN_HL
DW  $3840
DB  EN_I
DW  $3C00
DB  EN_IX
DW  $3C08
DB  EN_IXH
DW  $3C0C
DB  EN_IXL
DW  $3C28
DB  EN_IY
DW  $3C30
DB  EN_IYH
DW  $3C34
DB  EN_IYL
DW  $4B00
DB  EN_L
DW  $5140
DB  EN_M
DW  $57F8
DB  EN_NC
DW  $5B90
DB  EN_NZ
DW  $6400
DB  EN_P
DW  $64C8
DB  EN_PE
DW  $6658
DB  EN_PO
DW  $7080
DB  EN_R
DW  $7940
DB  EN_SP
DW  $A280
DB  EN_Z
PR_OWTEN:
PR_IEND:
PR_CEND:
PR_WBEG:
PR_DST: DW 0
PR_IADR: DW 0
PR_IPART: DB 0
PR_IOFF: DW 0
PR_ILEN: DB 0
PR_OPCNT: DB 0
PR_SINDE: DB 0
PR_FMASK: DB 0
PR_CMASK: DB 0
PR_CPTR: DW 0
PR_VPTR: DW 0
PR_LCLAS: DB 0
PR_MBASE: DB 0
PR_ICLAS: DB 0
PR_DSIGN: DB 0
PR_NKEY: DS 6
PR_SCRAT: DS 10
PR_ESTAT EQU PR_SCRAT+6
PR_EPART EQU PR_SCRAT+7
PR_EOFF EQU PR_SCRAT+8
PR_ESTA1 EQU PR_SCRAT+5
PR_SSTAT EQU PR_SCRAT+5
PR_RCNT: DB 0
PR_RBCNT: DB 0
PR_UMASK: DB 0
PR_RSCAN: DB 0
PR_RMCNT: DB 0
PR_RSKEY: DB 0
PR_RKSCR: DB 0
PR_ROSCR: DB 0
PR_RASCR: DW 0
PR_QBASE: DW 0
PR_RBLD: DS PR_BRB*PR_RCAP
PR_REFER: DS PR_PRB*PR_RCAP
PR_WEND:
OU_CBEG:
OU_SCAP EQU 1
OU_SINT EQU 2
OU_SVRAN EQU 3
OU_SRRAN EQU 4
;@ROUTINE IN DE,HL OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
OU_RESET:
LD   (OU_CURSO),HL
LD   (OU_REM),DE
XOR  A
RET
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,SIGN,PARITY,HALFCARRY,HL,ZERO
OU_CCAP:
EX   DE,HL
LD   HL,(OU_REM)
OR   A
SBC  HL,DE
JR   C,OU_DCFAI
XOR  A
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
OU_EMITB:
LD   B,A
LD   HL,1
CALL OU_CCAP
RET  C
LD   A,B
JR   OU_EBREA
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY,BC,IX,IY
OU_EMITW:
LD   B,H
LD   C,L
LD   HL,2
CALL OU_CCAP
RET  C
LD   A,C
PUSH BC
CALL OU_EBREA
POP  BC
RET  C
LD   A,B
JR   OU_EBREA
;@ROUTINE IN HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
OU_RESER:
PUSH HL
CALL OU_CCAP
POP  DE
RET  C
LD   HL,(OU_CURSO)
ADD  HL,DE
LD   (OU_CURSO),HL
LD   HL,(OU_REM)
OR   A
SBC  HL,DE
LD   (OU_REM),HL
XOR  A
RET
;@ROUTINE IN HL OUT A,CARRY CLOBBERS SIGN,PARITY,HALFCARRY,ZERO
OU_SORIG:
LD   (OU_CURSO),HL
XOR  A
RET
;@ROUTINE IN A OUT A,CARRY CLOBBERS BC,HL,ZERO,SIGN,PARITY,HALFCARRY,DE,IX,IY
OU_EBREA:
LD   HL,(OU_CURSO)
LD   C,0
CALL HS_IB
RET  C
LD   HL,(OU_CURSO)
INC  HL
LD   (OU_CURSO),HL
LD   HL,(OU_REM)
DEC  HL
LD   (OU_REM),HL
XOR  A
RET
OU_DCFAI:
LD   A,OU_SCAP
SCF
RET
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY,IX,IY
OU_EINS:
LD   HL,(OU_CURSO)
LD   (OU_IBEG),HL
