; Atom CP/M 2.2 transient adapter.
;
; The generated COM links the native Atom core at $0110. The first sixteen
; bytes are supplied by scripts/generate-cpm22.mjs. Source bytes are read from
; BDOS through one random-record cache; output is patched in TPA and published
; through a temporary file only after Atom commits.

CP_BDOS_ENTRY       EQU $0005
CP_SYMBOL_START     EQU $5000
CP_SYMBOL_END       EQU $8000
CP_PENDING_START    EQU $8000
CP_PENDING_END      EQU $9000
CP_OUTPUT_START     EQU $9000
CP_OUTPUT_END       EQU $D780
CP_SOURCE_CACHE     EQU $3E80
CP_SOURCE_CACHE_END EQU $3F00
CP_PART_ORDER       EQU $3F00
CP_PART_ORDER_END   EQU $4000
CP_PART_NAMES       EQU $4000
CP_PART_NAMES_END   EQU $4AF5
CP_PART_DESCRIPTORS EQU $4AF5
CP_PART_DESCRIPTORS_END EQU $4FF0
CP_NAME_COUNT       EQU $4FF0
CP_ORDER_COUNT      EQU $4FF1
CP_DESCRIPTOR_CURSOR EQU $4FF2
CP_ACTIVE_PART      EQU $4FF4
CP_SCAN_MODE        EQU $4FF5
CP_SCAN_INDEX       EQU $4FF6
CP_SCAN_PROGRESS    EQU $4FF7
CP_HEADER_OPEN      EQU $4FF8
CP_RAW_OFFSET       EQU $4FF9
CP_NEXT_VALUE       EQU $4FFB
CP_TARGET_START     EQU $0100
CP_TARGET_CAPACITY  EQU $4780
CP_STACK_TOP        EQU $E400
CP_DMA_FUNCTION     EQU 26
CP_OPEN_FUNCTION    EQU 15
CP_CLOSE_FUNCTION   EQU 16
CP_DELETE_FUNCTION  EQU 19
CP_READ_FUNCTION    EQU 20
CP_RANDOM_READ_FUNCTION EQU 33
CP_WRITE_FUNCTION   EQU 21
CP_MAKE_FUNCTION    EQU 22
CP_RENAME_FUNCTION  EQU 23
CP_PRINT_FUNCTION   EQU 9
CP_COMMAND_LENGTH   EQU $0080
CP_COMMAND_START    EQU $0081

CP_ADAPTER_CODE_START:
; CP/M standardizes only the 8080 register set. Preserve the Z80 index
; registers promised by Atom's private tool-service client adapter.
;@ROUTINE IN C,DE OUT A,CARRY,ZERO CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY
CP_BDOS:
PUSH IX
PUSH IY
CALL CP_BDOS_ENTRY
POP  IY
POP  IX
RET

;@ROUTINE CLOBBERS A,BC,DE,HL,IX,IY,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_ENTRY:
LD   (CP_SAVED_SP),SP
LD   SP,CP_STACK_TOP
CALL CP_PARSE_COMMAND
JR   C,CP_COMMAND_FAILED
OR   A
JR   NZ,CP_SUCCESS
CALL CP_RESOLVE_SOURCE
JR   C,CP_BUILD_FAILED
LD   HL,CP_OUTPUT_START
LD   DE,CP_OUTPUT_START+1
LD   BC,CP_OUTPUT_END-CP_OUTPUT_START-1
LD   (HL),0
LDIR
LD   IX,CP_DESCRIPTOR
CALL DR_ASM
JR   C,CP_ASSEMBLY_FAILED
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
LD   HL,CP_OUTPUT_NAME
CALL CP_PRINT_NAME
LD   DE,CP_WRITTEN_TEXT
CALL CP_PRINT
CP_SUCCESS:
XOR  A
JR   CP_RETURN
CP_COMMAND_FAILED:
CALL CP_PRINT
LD   A,2
JR   CP_RETURN
CP_ASSEMBLY_FAILED:
PUSH AF
LD   DE,CP_ASSEMBLY_TEXT
CALL CP_PRINT
POP  AF
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   A,(ST_EPART)
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   HL,(ST_EOFF)
PUSH HL
LD   A,H
CALL CP_PRINT_HEX
POP  HL
LD   A,L
CALL CP_PRINT_HEX
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
CP_BUILD_FAILED:
LD   A,1
CP_RETURN:
LD   SP,(CP_SAVED_SP)
RET

CP_COMMAND_CODE_START:
; Accept no arguments or two current-drive CP/M 8.3 names. The CCP
; canonicalises the names into its two default FCBs.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_COMMAND:
XOR  A
LD   (CP_ACTIVE_PART),A
LD   A,(CP_COMMAND_LENGTH)
LD   B,A
LD   HL,CP_COMMAND_START
CALL CP_SKIP_SPACES
JP   Z,CP_CHECK_AUXILIARY_NAMES
LD   A,B
CP   1
JR   NZ,CP_COMMAND_SOURCE
LD   A,(HL)
CP   '?'
JR   NZ,CP_COMMAND_SOURCE
LD   DE,CP_USAGE_TEXT
CALL CP_PRINT
XOR  A
INC  A
RET
CP_COMMAND_SOURCE:
CALL CP_PARSE_FILENAME
JP   C,CP_BAD_SOURCE_NAME
CALL CP_SKIP_SPACES
JR   Z,CP_SINGLE_NAME
CALL CP_PARSE_FILENAME
JP   C,CP_BAD_OUTPUT_NAME
CALL CP_SKIP_SPACES
JP   NZ,CP_BAD_USAGE
JR   CP_COMMAND_NAMES_READY
CP_SINGLE_NAME:
LD   HL,$005C
LD   DE,$006C
LD   BC,12
LDIR
LD   HL,CP_COM_EXTENSION
LD   DE,$006C+9
LD   BC,3
LDIR
CP_COMMAND_NAMES_READY:
LD   HL,$005C
LD   DE,CP_INPUT_FCB
LD   BC,12
LDIR
LD   A,(CP_INPUT_FCB+9)
CP   ' '
JR   NZ,CP_INPUT_TYPE_READY
LD   HL,CP_ASM_EXTENSION
LD   DE,CP_INPUT_FCB+9
LD   BC,3
LDIR
CP_INPUT_TYPE_READY:
LD   HL,$006C
LD   DE,CP_OUTPUT_NAME
LD   BC,12
LDIR
LD   HL,CP_OUTPUT_NAME+9
LD   DE,CP_COM_EXTENSION
LD   B,3
CP_OUTPUT_TYPE_BYTE:
LD   A,(DE)
CP   (HL)
JR   NZ,CP_BAD_OUTPUT_NAME
INC  DE
INC  HL
DJNZ CP_OUTPUT_TYPE_BYTE
LD   HL,CP_INPUT_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
CALL CP_SET_TEMP_FCB
CALL CP_CHECK_WORK_NAME
RET  C
CALL CP_SET_BACKUP_FCB
CALL CP_CHECK_WORK_NAME
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_WORK_NAME:
LD   HL,CP_INPUT_FCB
LD   DE,CP_WORK_FCB
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
JP   CP_AUXILIARY_MUST_NOT_EXIST
CP_BAD_USAGE:
LD   DE,CP_USAGE_TEXT
SCF
RET
CP_BAD_SOURCE_NAME:
LD   DE,CP_SOURCE_NAME_TEXT
SCF
RET
CP_BAD_OUTPUT_NAME:
LD   DE,CP_OUTPUT_NAME_TEXT
SCF
RET
CP_BAD_NAME_CONFLICT:
LD   DE,CP_NAME_CONFLICT_TEXT
SCF
RET

; Refuse to claim pre-existing temporary or backup files. CP/M is
; single-tasking, so successful preflight reserves both names until return.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_AUXILIARY_NAMES:
CALL CP_SET_TEMP_FCB
CALL CP_AUXILIARY_MUST_NOT_EXIST
RET  C
CALL CP_SET_BACKUP_FCB
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_AUXILIARY_MUST_NOT_EXIST:
LD   DE,CP_WORK_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_AUXILIARY_AVAILABLE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
LD   DE,CP_AUXILIARY_EXISTS_TEXT
SCF
RET
CP_AUXILIARY_AVAILABLE:
XOR  A
RET

;@ROUTINE IN B,HL OUT A,B,HL,ZERO CLOBBERS CARRY,SIGN,PARITY,HALFCARRY
CP_SKIP_SPACES:
LD   A,B
OR   A
RET  Z
LD   A,(HL)
CP   ' '
RET  NZ
INC  HL
DEC  B
JR   CP_SKIP_SPACES

; Parse one unquoted, current-drive 8.3 filename without consuming its
; trailing space. Carry reports an empty, overlong, wildcard, drive-qualified,
; or otherwise invalid field.
;@ROUTINE IN B,HL OUT A,B,HL,CARRY CLOBBERS C,D,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_FILENAME:
LD   D,8
LD   C,0
CP_PARSE_FILENAME_BYTE:
LD   A,B
OR   A
JR   Z,CP_FILENAME_DONE
LD   A,(HL)
CP   ' '
JR   Z,CP_FILENAME_DONE
CP   '.'
JR   NZ,CP_FILENAME_DATA
LD   A,D
CP   8
JR   NZ,CP_FILENAME_FAILURE
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
LD   D,3
LD   C,0
JR   CP_FILENAME_CONSUME
CP_FILENAME_DATA:
CALL CP_FILENAME_CHAR
RET  C
INC  C
LD   A,D
CP   C
JR   C,CP_FILENAME_FAILURE
CP_FILENAME_CONSUME:
INC  HL
DEC  B
JR   CP_PARSE_FILENAME_BYTE
CP_FILENAME_DONE:
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
RET
CP_FILENAME_FAILURE:
SCF
RET

;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_FILENAME_CHAR:
CP   '!'
RET  C
CP   $7F
JR   NC,CP_FILENAME_CHAR_BAD
CP   '*'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '-'
JR   C,CP_FILENAME_CHAR_BAD
CP   '/'
JR   Z,CP_FILENAME_CHAR_BAD
CP   ':'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '@'
JR   C,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_HIGH:
CP   '['
JR   C,CP_FILENAME_CHAR_OK
CP   '^'
JR   C,CP_FILENAME_CHAR_BAD
CP   '_'
JR   Z,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_OK:
OR   A
RET
CP_FILENAME_CHAR_BAD:
SCF
RET

;@ROUTINE IN DE,HL OUT A,ZERO CLOBBERS B,DE,HL,CARRY,SIGN,PARITY,HALFCARRY
CP_NAMES_EQUAL:
LD   B,12
CP_NAMES_EQUAL_BYTE:
LD   A,(DE)
CP   (HL)
RET  NZ
INC  DE
INC  HL
DJNZ CP_NAMES_EQUAL_BYTE
XOR  A
RET
CP_COMMAND_CODE_END:

CP_SOURCE_CODE_START:
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_CLEAR_INPUT_FCB:
LD   DE,CP_INPUT_FCB
XOR  A
LD   (DE),A
INC  DE
LD   B,11
LD   A,' '
CALL CP_CLEAR_WORK_FCB
JP   CP_CLEAR_FCB_TAIL

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_SOURCE_CONFLICT:
LD   HL,CP_INPUT_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_NAMES_EQUAL
JR   Z,CP_SOURCE_NAME_CONFLICT
CALL CP_SET_TEMP_FCB
LD   HL,CP_INPUT_FCB
LD   DE,CP_WORK_FCB
CALL CP_NAMES_EQUAL
JR   Z,CP_SOURCE_NAME_CONFLICT
CALL CP_SET_BACKUP_FCB
LD   HL,CP_INPUT_FCB
LD   DE,CP_WORK_FCB
CALL CP_NAMES_EQUAL
JR   Z,CP_SOURCE_NAME_CONFLICT
XOR  A
RET
CP_SOURCE_NAME_CONFLICT:
LD   DE,CP_NAME_CONFLICT_TEXT
SCF
RET

; Read one logical source byte through a 128-byte random-record cache. The
; pre-scan proves every requested record exists for the life of this transient.
;@ROUTINE IN A,HL OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
CP_SOURCE_READ_BYTE:
JP   CP_RESOLVED_READ_BYTE

; Resolve the root source and its leading %INCLUDE graph. Names are retained
; as exact CP/M 8.3 identities, while descriptors are emitted in dependency-
; first order. No intermediate source-order file is involved.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
CP_RESOLVE_SOURCE:
XOR  A
LD   (CP_DESCRIPTOR),A
LD   (CP_ORDER_COUNT),A
LD   (CP_SCAN_INDEX),A
INC  A
LD   (CP_NAME_COUNT),A
LD   HL,CP_INPUT_FCB+1
LD   DE,CP_PART_NAMES
LD   BC,11
LDIR
LD   A,$FF
LD   (CP_ACTIVE_PART),A
; First discover every exact name reachable from the root.
CP_DISCOVER_PART:
XOR  A
LD   (CP_SCAN_MODE),A
LD   A,(CP_SCAN_INDEX)
CALL CP_SCAN_PART
JP   C,CP_RESOLVE_FAILURE
LD   HL,CP_SCAN_INDEX
INC  (HL)
LD   A,(CP_NAME_COUNT)
CP   (HL)
JR   NZ,CP_DISCOVER_PART
; Repeatedly emit a part whose dependencies have all been emitted. Failure to
; make progress proves a cycle without recursion or an unbounded call stack.
CP_TOPO_PASS:
XOR  A
LD   (CP_SCAN_INDEX),A
LD   (CP_SCAN_PROGRESS),A
CP_TOPO_PART:
LD   A,(CP_SCAN_INDEX)
CALL CP_NAME_POINTER
BIT  7,(HL)
JR   NZ,CP_TOPO_NEXT
LD   A,1
LD   (CP_SCAN_MODE),A
LD   A,(CP_SCAN_INDEX)
CALL CP_SCAN_PART
JP   C,CP_RESOLVE_FAILURE
OR   A
JR   NZ,CP_TOPO_NEXT
LD   A,(CP_ORDER_COUNT)
LD   E,A
LD   D,CP_PART_ORDER/256
LD   A,(CP_SCAN_INDEX)
LD   (DE),A
CALL CP_NAME_POINTER
SET  7,(HL)
LD   HL,CP_ORDER_COUNT
INC  (HL)
LD   A,1
LD   (CP_SCAN_PROGRESS),A
CP_TOPO_NEXT:
LD   HL,CP_SCAN_INDEX
INC  (HL)
LD   A,(CP_NAME_COUNT)
CP   (HL)
JR   NZ,CP_TOPO_PART
LD   A,(CP_ORDER_COUNT)
LD   HL,CP_NAME_COUNT
CP   (HL)
JR   Z,CP_BUILD_DESCRIPTORS
LD   A,(CP_SCAN_PROGRESS)
OR   A
JR   NZ,CP_TOPO_PASS
LD   DE,CP_INCLUDE_CYCLE_TEXT
JR   CP_RESOLVE_FAILURE
; Measure the already validated parts in final order and build the ordinary
; native five-byte descriptors.
CP_BUILD_DESCRIPTORS:
XOR  A
LD   (CP_SCAN_INDEX),A
LD   HL,CP_PART_DESCRIPTORS
LD   (CP_DESCRIPTOR_CURSOR),HL
CP_BUILD_DESCRIPTOR:
LD   A,(CP_SCAN_INDEX)
LD   E,A
LD   D,CP_PART_ORDER/256
LD   A,(DE)
CALL CP_OPEN_PART
JP   C,CP_RESOLVE_FAILURE
LD   HL,0
CP_MEASURE_BYTE:
CALL CP_NEXT_SOURCE_BYTE
JR   NC,CP_MEASURE_BYTE
OR   A
JP   NZ,CP_RESOLVE_IO
CALL CP_APPEND_DESCRIPTOR
LD   HL,CP_SCAN_INDEX
INC  (HL)
LD   A,(CP_NAME_COUNT)
CP   (HL)
JR   NZ,CP_BUILD_DESCRIPTOR
LD   A,(CP_NAME_COUNT)
LD   (CP_DESCRIPTOR),A
XOR  A
RET
CP_RESOLVE_IO:
LD   HL,CP_INPUT_FCB
CALL CP_PRINT_NAME
LD   DE,CP_READ_FAILED_TEXT
CP_RESOLVE_FAILURE:
CALL CP_PRINT
SCF
RET

; Scan and validate one source header. Mode zero discovers names; mode one
; reports A=1 when any dependency has not yet been emitted.
;@ROUTINE IN A OUT A,DE,CARRY CLOBBERS BC,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
CP_SCAN_PART:
CALL CP_OPEN_PART
JR   C,CP_SCAN_FAILURE
LD   A,1
LD   (CP_HEADER_OPEN),A
LD   HL,0
CP_SCAN_LINE:
CALL CP_NEXT_SOURCE_BYTE
JR   C,CP_SCAN_EOF
CP   ' '
JR   Z,CP_SCAN_LINE
CP   9
JR   Z,CP_SCAN_LINE
CP   13
JR   Z,CP_SCAN_LINE
CP   10
JR   Z,CP_SCAN_LINE
CP   ';'
JR   Z,CP_SCAN_SKIP_LINE
CP   '%'
JR   Z,CP_SCAN_DIRECTIVE
XOR  A
LD   (CP_HEADER_OPEN),A
CP_SCAN_SKIP_LINE:
CALL CP_SKIP_SOURCE_LINE
JR   NC,CP_SCAN_LINE
OR   A
JR   Z,CP_SCAN_COMPLETE
JR   CP_SCAN_IO
CP_SCAN_DIRECTIVE:
LD   A,(CP_HEADER_OPEN)
OR   A
JR   Z,CP_SCAN_INVALID
CALL CP_PARSE_INCLUDE
JR   C,CP_SCAN_FAILURE
OR   A
JR   NZ,CP_SCAN_DONE
JR   CP_SCAN_LINE
CP_SCAN_EOF:
OR   A
JR   NZ,CP_SCAN_IO
CP_SCAN_COMPLETE:
XOR  A
CP_SCAN_DONE:
RET
CP_SCAN_IO:
LD   HL,CP_INPUT_FCB
CALL CP_PRINT_NAME
LD   DE,CP_READ_FAILED_TEXT
JR   CP_SCAN_FAILURE
CP_SCAN_INVALID:
LD   DE,CP_INVALID_INCLUDE_TEXT
CP_SCAN_FAILURE:
SCF
RET

;@ROUTINE IN HL OUT A,DE,HL CLOBBERS CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_APPEND_DESCRIPTOR:
LD   DE,(CP_DESCRIPTOR_CURSOR)
LD   A,(CP_SCAN_INDEX)
LD   (DE),A
INC  DE
XOR  A
LD   (DE),A
INC  DE
LD   (DE),A
INC  DE
LD   A,L
LD   (DE),A
INC  DE
LD   A,H
LD   (DE),A
INC  DE
LD   (CP_DESCRIPTOR_CURSOR),DE
RET

; Parse INCLUDE, one quoted current-drive 8.3 filename, and the rest of its
; directive line. Discovery records the child; ordering checks its emitted bit.
;@ROUTINE IN HL OUT A,CARRY,HL CLOBBERS BC,DE,IX,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_INCLUDE:
LD   DE,CP_INCLUDE_WORD
LD   B,7
CP_INCLUDE_WORD_BYTE:
CALL CP_NEXT_SOURCE_BYTE
JP   C,CP_INCLUDE_INVALID
CP   'a'
JR   C,CP_INCLUDE_WORD_CASED
CP   'z'+1
JR   NC,CP_INCLUDE_WORD_CASED
AND  $DF
CP_INCLUDE_WORD_CASED:
EX   DE,HL
CP   (HL)
INC  HL
EX   DE,HL
JP   NZ,CP_INCLUDE_INVALID
DJNZ CP_INCLUDE_WORD_BYTE
CALL CP_NEXT_SOURCE_BYTE
JP   C,CP_INCLUDE_INVALID
CP   ' '
JR   Z,CP_INCLUDE_SPACE
CP   9
JP   NZ,CP_INCLUDE_INVALID
CP_INCLUDE_SPACE:
CALL CP_NEXT_SOURCE_BYTE
JP   C,CP_INCLUDE_INVALID
CP   ' '
JR   Z,CP_INCLUDE_SPACE
CP   9
JR   Z,CP_INCLUDE_SPACE
CP   '"'
JP   NZ,CP_INCLUDE_INVALID
CALL CP_CLEAR_INCLUDE_FCB
PUSH IX
CALL CP_PARSE_INCLUDE_NAME
POP  IX
RET  C
CP_INCLUDE_TRAILING:
CALL CP_NEXT_SOURCE_BYTE
JR   C,CP_INCLUDE_TRAILING_EOF
CP   ' '
JR   Z,CP_INCLUDE_TRAILING
CP   9
JR   Z,CP_INCLUDE_TRAILING
CP   ';'
JR   Z,CP_INCLUDE_SKIP_COMMENT
CP   13
JR   Z,CP_INCLUDE_READY
CP   10
JP   NZ,CP_INCLUDE_INVALID
CP_INCLUDE_READY:
PUSH IX
PUSH HL
CALL CP_FIND_OR_ADD_NAME
POP  HL
POP  IX
RET  C
PUSH HL
CALL CP_VISIT_INCLUDED_CHILD
POP  HL
RET
CP_INCLUDE_SKIP_COMMENT:
CALL CP_SKIP_SOURCE_LINE
JR   C,CP_INCLUDE_TRAILING_EOF
JR   CP_INCLUDE_READY
CP_INCLUDE_TRAILING_EOF:
OR   A
JP   NZ,CP_INCLUDE_INVALID
JR   CP_INCLUDE_READY
CP_INCLUDE_INVALID:
LD   DE,CP_INVALID_INCLUDE_TEXT
SCF
RET

;@ROUTINE IN HL OUT A,CARRY,HL CLOBBERS BC,DE,IX,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_INCLUDE_NAME:
LD   IX,CP_WORK_FCB+1
LD   D,8
LD   C,0
CP_INCLUDE_NAME_BYTE:
CALL CP_NEXT_SOURCE_BYTE
JP   C,CP_INCLUDE_NAME_BAD
CP   '"'
JR   Z,CP_INCLUDE_NAME_DONE
CP   '.'
JR   NZ,CP_INCLUDE_NAME_DATA
LD   A,D
CP   8
JP   NZ,CP_INCLUDE_NAME_BAD
LD   A,C
OR   A
JP   Z,CP_INCLUDE_NAME_BAD
LD   IX,CP_WORK_FCB+9
LD   D,3
LD   C,0
JR   CP_INCLUDE_NAME_BYTE
CP_INCLUDE_NAME_DATA:
CP   'a'
JR   C,CP_INCLUDE_NAME_CASED
CP   'z'+1
JR   NC,CP_INCLUDE_NAME_CASED
AND  $DF
CP_INCLUDE_NAME_CASED:
CALL CP_FILENAME_CHAR
JP   C,CP_INCLUDE_NAME_BAD
INC  C
LD   B,A
LD   A,D
CP   C
JP   C,CP_INCLUDE_NAME_BAD
LD   A,B
LD   (IX+0),A
INC  IX
JR   CP_INCLUDE_NAME_BYTE
CP_INCLUDE_NAME_DONE:
LD   A,C
OR   A
RET  NZ
CP_INCLUDE_NAME_BAD:
LD   DE,CP_INVALID_INCLUDE_TEXT
SCF
RET

;@ROUTINE IN A OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_VISIT_INCLUDED_CHILD:
LD   E,A
LD   A,(CP_SCAN_MODE)
OR   A
RET  Z
LD   A,E
CALL CP_NAME_POINTER
BIT  7,(HL)
LD   A,0
RET  NZ
INC  A
RET

;@ROUTINE OUT A CLOBBERS B,DE,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_CLEAR_INCLUDE_FCB:
LD   DE,CP_WORK_FCB
XOR  A
LD   (DE),A
INC  DE
LD   B,11
LD   A,' '
CALL CP_CLEAR_WORK_FCB
JP   CP_CLEAR_FCB_TAIL

; Find an exact retained name, or append it if capacity remains.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
CP_FIND_OR_ADD_NAME:
LD   C,0
CP_FIND_NAME_LOOP:
LD   A,(CP_NAME_COUNT)
CP   C
JR   Z,CP_ADD_NAME
LD   A,C
CALL CP_NAME_POINTER
LD   IX,CP_WORK_FCB+1
LD   B,11
CP_FIND_NAME_BYTE:
LD   A,(HL)
AND  $7F
CP   (IX+0)
JR   NZ,CP_FIND_NAME_NEXT
INC  HL
INC  IX
DJNZ CP_FIND_NAME_BYTE
LD   A,C
OR   A
RET
CP_FIND_NAME_NEXT:
INC  C
JR   CP_FIND_NAME_LOOP
CP_ADD_NAME:
LD   A,C
CP   255
JR   Z,CP_NAME_CAPACITY
PUSH AF
CALL CP_NAME_POINTER
EX   DE,HL
LD   HL,CP_WORK_FCB+1
LD   BC,11
LDIR
LD   HL,CP_NAME_COUNT
INC  (HL)
POP  AF
OR   A
RET
CP_NAME_CAPACITY:
LD   DE,CP_SOURCE_CAPACITY_TEXT
SCF
RET

;@ROUTINE IN A OUT A,HL CLOBBERS DE,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_NAME_POINTER:
LD   L,A
LD   H,0
LD   D,H
LD   E,L
ADD  HL,HL
ADD  HL,HL
ADD  HL,DE
ADD  HL,HL
ADD  HL,DE
LD   DE,CP_PART_NAMES
ADD  HL,DE
RET

; Rebuild and open the ordinary input FCB from one retained name.
;@ROUTINE IN A OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_OPEN_PART:
PUSH AF
CALL CP_CLEAR_INPUT_FCB
POP  AF
CALL CP_NAME_POINTER
LD   DE,CP_INPUT_FCB+1
LD   B,11
CP_OPEN_NAME_BYTE:
LD   A,(HL)
AND  $7F
LD   (DE),A
INC  HL
INC  DE
DJNZ CP_OPEN_NAME_BYTE
CALL CP_CHECK_SOURCE_CONFLICT
RET  C
LD   DE,CP_INPUT_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_OPEN_FAILURE
LD   A,1
LD   (CP_SOURCE_CACHE_KEY),A
XOR  A
RET
CP_OPEN_FAILURE:
LD   HL,CP_INPUT_FCB
CALL CP_PRINT_NAME
LD   DE,CP_READ_FAILED_TEXT
SCF
RET

; Return the next raw source byte and advance HL. Carry with A=0 is EOF;
; carry with A=2 is disk failure. BC and DE survive for parsers.
;@ROUTINE IN HL OUT A,CARRY,HL CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_NEXT_SOURCE_BYTE:
PUSH BC
PUSH DE
PUSH HL
CALL CP_RAW_SOURCE_BYTE
POP  HL
POP  DE
POP  BC
RET  C
LD   (CP_NEXT_VALUE),A
INC  HL
LD   A,H
OR   L
JR   Z,CP_SOURCE_TOO_LONG
LD   A,(CP_NEXT_VALUE)
OR   A
RET
CP_SOURCE_TOO_LONG:
LD   A,2
SCF
RET

;@ROUTINE IN HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_RAW_SOURCE_BYTE:
LD   (CP_RAW_OFFSET),HL
LD   A,L
AND  $80
LD   E,A
LD   D,H
LD   HL,(CP_SOURCE_CACHE_KEY)
OR   A
SBC  HL,DE
JR   Z,CP_RAW_CACHE_READY
CP_RAW_CACHE_MISS:
LD   (CP_SOURCE_CACHE_KEY),DE
RLC  E
LD   A,D
ADD  A,A
OR   E
LD   (CP_INPUT_FCB+33),A
LD   A,D
RLCA
AND  1
LD   (CP_INPUT_FCB+34),A
LD   DE,CP_SOURCE_CACHE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_INPUT_FCB
LD   C,CP_RANDOM_READ_FUNCTION
CALL CP_BDOS
OR   A
JR   NZ,CP_RAW_READ_EOF
CP_RAW_CACHE_READY:
LD   HL,(CP_RAW_OFFSET)
SET  7,L
LD   H,CP_SOURCE_CACHE/256
LD   A,(HL)
CP   $1A
JR   Z,CP_RAW_EOF
OR   A
RET
CP_RAW_READ_EOF:
CP_RAW_EOF:
XOR  A
SCF
RET

;@ROUTINE IN HL OUT A,CARRY,HL CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_SKIP_SOURCE_LINE:
CALL CP_NEXT_SOURCE_BYTE
RET  C
CP   13
RET  Z
CP   10
JR   NZ,CP_SKIP_SOURCE_LINE
RET

; Open a part on ordinal change, then return one byte. A line-leading percent
; is changed to a semicolon after preflight has proved it is %INCLUDE.
;@ROUTINE IN A,HL OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
CP_RESOLVED_READ_BYTE:
LD   E,A
LD   A,(CP_ACTIVE_PART)
CP   E
JR   Z,CP_RESOLVED_SOURCE_READY
PUSH BC
PUSH HL
LD   A,E
LD   (CP_ACTIVE_PART),A
LD   D,CP_PART_ORDER/256
LD   A,(DE)
CALL CP_OPEN_PART
POP  HL
POP  BC
CP_RESOLVED_SOURCE_READY:
PUSH BC
PUSH HL
CALL CP_RAW_SOURCE_BYTE
POP  HL
POP  BC
RET  C
CP   '%'
JR   Z,CP_RESOLVED_PERCENT
OR   A
RET
CP_RESOLVED_PERCENT:
PUSH HL
CALL CP_PERCENT_IS_DIRECTIVE
POP  HL
JR   Z,CP_RESOLVED_DIRECTIVE
LD   A,'%'
OR   A
RET
CP_RESOLVED_DIRECTIVE:
LD   A,';'
OR   A
RET

;@ROUTINE IN HL OUT A,ZERO CLOBBERS BC,DE,HL,CARRY,SIGN,PARITY,HALFCARRY
CP_PERCENT_IS_DIRECTIVE:
LD   A,H
OR   L
RET  Z
DEC  HL
CP_PERCENT_PREFIX:
PUSH HL
CALL CP_RAW_SOURCE_BYTE
POP  HL
CP   13
JR   Z,CP_PERCENT_YES
CP   10
JR   Z,CP_PERCENT_YES
CP   ' '
JR   Z,CP_PERCENT_PREVIOUS
CP   9
RET  NZ
CP_PERCENT_PREVIOUS:
LD   A,H
OR   L
JR   Z,CP_PERCENT_YES
DEC  HL
JR   CP_PERCENT_PREFIX
CP_PERCENT_YES:
XOR  A
RET
CP_SOURCE_CODE_END:

; Nucleus-model sink entries linked directly in place of the host stubs.
CP_OUTPUT_CODE_START:
HS_SCBEG:
;@ROUTINE IN IX OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
HS_BEG:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_IB:
HS_PB:
PUSH AF
LD   DE,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,DE
POP  AF
LD   (HL),A
XOR  A
RET

;@ROUTINE IN C,DE,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_PW:
EX   DE,HL
LD   BC,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,BC
LD   (HL),E
INC  HL
LD   (HL),D
XOR  A
RET

;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_CMT:
LD   DE,CP_TARGET_START
OR   A
SBC  HL,DE
LD   (CP_OUTPUT_REMAINING),HL
LD   HL,CP_OUTPUT_START
LD   (CP_OUTPUT_CURSOR),HL
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_MAKE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
LD   A,1
LD   (CP_OUTPUT_OPEN),A
CP_WRITE_LOOP:
LD   HL,(CP_OUTPUT_REMAINING)
LD   A,H
OR   L
JR   Z,CP_WRITE_CLOSE
LD   DE,(CP_OUTPUT_CURSOR)
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_WORK_FCB
LD   C,CP_WRITE_FUNCTION
CALL CP_BDOS
OR   A
JP   NZ,CP_COMMIT_FAILURE
LD   HL,(CP_OUTPUT_CURSOR)
LD   DE,128
ADD  HL,DE
LD   (CP_OUTPUT_CURSOR),HL
LD   HL,(CP_OUTPUT_REMAINING)
LD   DE,128
OR   A
SBC  HL,DE
JR   NC,CP_WRITE_MORE
LD   HL,0
CP_WRITE_MORE:
LD   (CP_OUTPUT_REMAINING),HL
JR   CP_WRITE_LOOP
CP_WRITE_CLOSE:
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
XOR  A
LD   (CP_OUTPUT_OPEN),A
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_NO_BACKUP
LD   A,1
LD   (CP_BACKED_UP),A
CP_NO_BACKUP:
CALL CP_SET_TEMP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
XOR  A
LD   (CP_BACKED_UP),A
RET
CP_COMMIT_FAILURE:
LD   A,1
SCF
RET

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_ABORT:
LD   A,(CP_OUTPUT_OPEN)
OR   A
JR   Z,CP_ABORT_DELETE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
CP_ABORT_DELETE:
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   A,(CP_BACKED_UP)
OR   A
JR   Z,CP_ABORT_DONE
CALL CP_SET_BACKUP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
CP_ABORT_DONE:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

; Rebuild the single ordinary output FCB before each new BDOS operation phase.
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_COPY_OUTPUT_FCB:
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
LD   BC,12
LDIR
;@ROUTINE IN DE OUT A,B,DE,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_CLEAR_FCB_TAIL:
XOR  A
LD   B,24
;@ROUTINE IN A,B,DE OUT B,DE
CP_CLEAR_WORK_FCB:
LD   (DE),A
INC  DE
DJNZ CP_CLEAR_WORK_FCB
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_TEMP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$2424
LD   (CP_WORK_FCB+9),HL
LD   A,'$'
LD   (CP_WORK_FCB+11),A
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_BACKUP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$4142
LD   (CP_WORK_FCB+9),HL
LD   A,'K'
LD   (CP_WORK_FCB+11),A
RET

; Construct a CP/M rename FCB in the input FCB's dead storage. HL addresses
; the old 12-byte name and DE the new 12-byte name.
;@ROUTINE IN DE,HL CLOBBERS A,BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_BUILD_RENAME:
PUSH HL
PUSH DE
LD   DE,CP_RENAME_FCB
XOR  A
LD   B,36
CALL CP_CLEAR_WORK_FCB
POP  DE
POP  HL
PUSH DE
LD   DE,CP_RENAME_FCB
LD   BC,12
LDIR
POP  HL
LD   DE,CP_RENAME_FCB+16
LD   BC,12
LDIR
RET

CP_OUTPUT_CODE_END:
;@ROUTINE IN DE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT:
LD   C,CP_PRINT_FUNCTION
JP   CP_BDOS
;@ROUTINE IN HL OUT A CLOBBERS B,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NAME:
INC  HL
LD   B,8
CP_PRINT_NAME_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_NAME_BYTE
LD   A,(HL)
CP   ' '
RET  Z
LD   A,'.'
CALL CP_PUTC
LD   B,3
CP_PRINT_TYPE_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_TYPE_BYTE
RET
;@ROUTINE IN A OUT A CLOBBERS CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PUTC:
PUSH BC
PUSH DE
PUSH HL
LD   E,A
LD   C,2
CALL CP_BDOS
POP  HL
POP  DE
POP  BC
RET
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_HEX:
PUSH AF
RRCA
RRCA
RRCA
RRCA
CALL CP_PRINT_NIBBLE
POP  AF
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NIBBLE:
AND  $0F
ADD  A,'0'
CP   '9'+1
JR   C,CP_PUTC
ADD  A,7
JR   CP_PUTC

CP_ADAPTER_CODE_END:
CP_ADAPTER_WORKSPACE1_START:
CP_DESCRIPTOR:
DB   1
DW   CP_PART_DESCRIPTORS
DW   CP_SYMBOL_START,CP_SYMBOL_END
DW   CP_PENDING_START,CP_PENDING_END
DW   CP_TARGET_START,CP_TARGET_CAPACITY

CP_RENAME_FCB:
CP_INPUT_FCB:
DB 0,'I','N','P','U','T',' ',' ',' ','A','S','M'
DS 24
CP_WORK_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','$','$','$'
DS 24
CP_OUTPUT_NAME:
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
CP_ADAPTER_WORKSPACE1_END:

CP_ADAPTER_IMMUTABLE_START:
CP_WRITTEN_TEXT: DB ' ','w','r','i','t','t','e','n',13,10,'$'
CP_READ_FAILED_TEXT: DB ' ','r','e','a','d',' ','f','a','i','l','e','d',13,10,'$'
CP_ASSEMBLY_TEXT: DB 13,10,'A','t','o','m',' ','e','r','r','o','r',' ','$'
CP_NEWLINE_TEXT: DB 13,10,'$'
CP_USAGE_TEXT: DB 13,10,'U','s','a','g','e',':',' ','A','T','O','M',' ','[','S','O','U','R','C','E',' ','[','O','U','T','P','U','T','.','C','O','M',']',']',13,10,'$'
CP_SOURCE_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','s','o','u','r','c','e',' ','n','a','m','e',13,10,'$'
CP_OUTPUT_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','o','u','t','p','u','t',' ','n','a','m','e',13,10,'$'
CP_NAME_CONFLICT_TEXT: DB 13,10,'S','o','u','r','c','e','/','o','u','t','p','u','t',' ','c','o','n','f','l','i','c','t',13,10,'$'
CP_AUXILIARY_EXISTS_TEXT: DB 13,10,'T','e','m','p','/','b','a','c','k','u','p',' ','f','i','l','e',' ','e','x','i','s','t','s',13,10,'$'
CP_INVALID_INCLUDE_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','%','I','N','C','L','U','D','E',13,10,'$'
CP_INCLUDE_CYCLE_TEXT: DB 13,10,'I','n','c','l','u','d','e',' ','c','y','c','l','e',13,10,'$'
CP_SOURCE_CAPACITY_TEXT: DB 13,10,'T','o','o',' ','m','a','n','y',' ','s','o','u','r','c','e','s',13,10,'$'
CP_INCLUDE_WORD: DB 'I','N','C','L','U','D','E'
CP_ASM_EXTENSION: DB 'A','S','M'
CP_COM_EXTENSION: DB 'C','O','M'
CP_ADAPTER_IMMUTABLE_END:
CP_ADAPTER_WORKSPACE2_START:
CP_SAVED_SP: DW 0
CP_OUTPUT_CURSOR: DW 0
CP_SOURCE_CACHE_KEY EQU CP_OUTPUT_CURSOR
CP_OUTPUT_REMAINING: DW 0
CP_OUTPUT_OPEN: DB 0
CP_BACKED_UP: DB 0
CP_ADAPTER_WORKSPACE2_END:
HS_SCEND:
HS_REND:
CP_RESIDENT_END:
