; Atom CP/M 2.2 transient adapter.
;
; The generated COM links the native Atom core at $0110. The first sixteen
; bytes are supplied by scripts/generate-cpm22.mjs. Source bytes are read from
; BDOS through one random-record cache; output is patched in TPA and published
; through a temporary file only after Atom commits.

CP_BDOS_ENTRY       EQU $0005
CP_SYMBOL_START     EQU $5000
CP_SYMBOL_END       EQU $8000
CP_PENDING_START    EQU $8000
CP_PENDING_END      EQU $9000
CP_OUTPUT_START     EQU $9000
CP_OUTPUT_END       EQU $D780
CP_SOURCE_CACHE     EQU $4000
CP_SOURCE_CACHE_END EQU $4080
CP_PLAN_CACHE       EQU $4080
CP_PLAN_CACHE_END   EQU $4100
CP_PART_DESCRIPTORS EQU $4100
CP_PART_DESCRIPTORS_END EQU $45FB
CP_PLAN_FCB         EQU $4600
CP_PLAN_FCB_END     EQU $4624
CP_PLAN_POINTER     EQU $4624
CP_PLAN_REMAINING   EQU $4626
CP_PLAN_LINE_END    EQU $4627
CP_ACTIVE_PART      EQU CP_SOURCE_READ_BYTE+1
CP_TARGET_START     EQU $0100
CP_TARGET_CAPACITY  EQU $4780
CP_STACK_TOP        EQU $E400
CP_DMA_FUNCTION     EQU 26
CP_OPEN_FUNCTION    EQU 15
CP_CLOSE_FUNCTION   EQU 16
CP_DELETE_FUNCTION  EQU 19
CP_READ_FUNCTION    EQU 20
CP_RANDOM_READ_FUNCTION EQU 33
CP_WRITE_FUNCTION   EQU 21
CP_MAKE_FUNCTION    EQU 22
CP_RENAME_FUNCTION  EQU 23
CP_PRINT_FUNCTION   EQU 9
CP_COMMAND_LENGTH   EQU $0080
CP_COMMAND_START    EQU $0081

CP_ADAPTER_CODE_START:
; CP/M standardizes only the 8080 register set. Preserve the Z80 index
; registers promised by Atom's private tool-service client adapter.
;@ROUTINE IN C,DE OUT A,CARRY,ZERO CLOBBERS BC,DE,HL,SIGN,PARITY,HALFCARRY
CP_BDOS:
PUSH IX
PUSH IY
CALL CP_BDOS_ENTRY
POP  IY
POP  IX
RET

;@ROUTINE CLOBBERS A,BC,DE,HL,IX,IY,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_ENTRY:
LD   (CP_SAVED_SP),SP
LD   SP,CP_STACK_TOP
CALL CP_PARSE_COMMAND
JR   C,CP_COMMAND_FAILED
CALL CP_PREPARE_SOURCE
JR   C,CP_RETURN
LD   HL,CP_OUTPUT_START
LD   DE,CP_OUTPUT_START+1
LD   BC,CP_OUTPUT_END-CP_OUTPUT_START-1
LD   (HL),0
LDIR
LD   IX,CP_DESCRIPTOR
CALL DR_ASM
JR   C,CP_ASSEMBLY_FAILED
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
LD   HL,CP_OUTPUT_NAME
CALL CP_PRINT_NAME
LD   DE,CP_WRITTEN_TEXT
CALL CP_PRINT
JR   CP_RETURN
CP_COMMAND_FAILED:
CALL CP_PRINT
JR   CP_RETURN
CP_ASSEMBLY_FAILED:
PUSH AF
LD   DE,CP_ASSEMBLY_TEXT
CALL CP_PRINT
POP  AF
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   A,(ST_EPART)
CALL CP_PRINT_HEX
LD   A,' '
CALL CP_PUTC
LD   HL,(ST_EOFF)
PUSH HL
LD   A,H
CALL CP_PRINT_HEX
POP  HL
LD   A,L
CALL CP_PRINT_HEX
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
CP_RETURN:
LD   SP,(CP_SAVED_SP)
RET

CP_COMMAND_CODE_START:
; Accept no arguments, two current-drive CP/M 8.3 names, or those names plus
; a trailing @. The CCP canonicalises the names into its two default FCBs.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_COMMAND:
XOR  A
LD   (CP_ACTIVE_PART),A
LD   A,(CP_COMMAND_LENGTH)
LD   B,A
LD   HL,CP_COMMAND_START
CALL CP_SKIP_SPACES
JP   Z,CP_CHECK_AUXILIARY_NAMES
CALL CP_PARSE_FILENAME
JR   C,CP_BAD_SOURCE_NAME
CALL CP_SKIP_SPACES
JR   Z,CP_BAD_USAGE
CALL CP_PARSE_FILENAME
JR   C,CP_BAD_OUTPUT_NAME
CALL CP_SKIP_SPACES
JR   Z,CP_COMMAND_NAMES_READY
CP   '@'
JR   NZ,CP_BAD_USAGE
INC  HL
DEC  B
CALL CP_SKIP_SPACES
JR   NZ,CP_BAD_USAGE
LD   A,$FF
LD   (CP_ACTIVE_PART),A
CP_COMMAND_NAMES_READY:
LD   HL,$005C
LD   DE,CP_INPUT_FCB
LD   BC,12
LDIR
LD   HL,$006C
LD   DE,CP_OUTPUT_NAME
LD   BC,12
LDIR
LD   HL,CP_OUTPUT_NAME+9
LD   DE,CP_COM_EXTENSION
LD   B,3
CP_OUTPUT_TYPE_BYTE:
LD   A,(DE)
CP   (HL)
JR   NZ,CP_BAD_OUTPUT_NAME
INC  DE
INC  HL
DJNZ CP_OUTPUT_TYPE_BYTE
LD   HL,CP_INPUT_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
CALL CP_SET_TEMP_FCB
CALL CP_CHECK_WORK_NAME
RET  C
CALL CP_SET_BACKUP_FCB
CALL CP_CHECK_WORK_NAME
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_WORK_NAME:
LD   HL,CP_INPUT_FCB
LD   DE,CP_WORK_FCB
CALL CP_NAMES_EQUAL
JR   Z,CP_BAD_NAME_CONFLICT
JP   CP_AUXILIARY_MUST_NOT_EXIST
CP_BAD_USAGE:
LD   DE,CP_USAGE_TEXT
SCF
RET
CP_BAD_SOURCE_NAME:
LD   DE,CP_SOURCE_NAME_TEXT
SCF
RET
CP_BAD_OUTPUT_NAME:
LD   DE,CP_OUTPUT_NAME_TEXT
SCF
RET
CP_BAD_NAME_CONFLICT:
LD   DE,CP_NAME_CONFLICT_TEXT
SCF
RET

; Refuse to claim pre-existing temporary or backup files. CP/M is
; single-tasking, so successful preflight reserves both names until return.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_AUXILIARY_NAMES:
CALL CP_SET_TEMP_FCB
CALL CP_AUXILIARY_MUST_NOT_EXIST
RET  C
CALL CP_SET_BACKUP_FCB
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_AUXILIARY_MUST_NOT_EXIST:
LD   DE,CP_WORK_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_AUXILIARY_AVAILABLE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
LD   DE,CP_AUXILIARY_EXISTS_TEXT
SCF
RET
CP_AUXILIARY_AVAILABLE:
XOR  A
RET

;@ROUTINE IN B,HL OUT A,B,HL,ZERO CLOBBERS CARRY,SIGN,PARITY,HALFCARRY
CP_SKIP_SPACES:
LD   A,B
OR   A
RET  Z
LD   A,(HL)
CP   ' '
RET  NZ
INC  HL
DEC  B
JR   CP_SKIP_SPACES

; Parse one unquoted, current-drive 8.3 filename without consuming its
; trailing space. Carry reports an empty, overlong, wildcard, drive-qualified,
; or otherwise invalid field.
;@ROUTINE IN B,HL OUT A,B,HL,CARRY CLOBBERS C,D,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_FILENAME:
LD   D,8
LD   C,0
CP_PARSE_FILENAME_BYTE:
LD   A,B
OR   A
JR   Z,CP_FILENAME_DONE
LD   A,(HL)
CP   ' '
JR   Z,CP_FILENAME_DONE
CP   '.'
JR   NZ,CP_FILENAME_DATA
LD   A,D
CP   8
JR   NZ,CP_FILENAME_FAILURE
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
LD   D,3
LD   C,0
JR   CP_FILENAME_CONSUME
CP_FILENAME_DATA:
CALL CP_FILENAME_CHAR
RET  C
INC  C
LD   A,D
CP   C
JR   C,CP_FILENAME_FAILURE
CP_FILENAME_CONSUME:
INC  HL
DEC  B
JR   CP_PARSE_FILENAME_BYTE
CP_FILENAME_DONE:
LD   A,C
OR   A
JR   Z,CP_FILENAME_FAILURE
RET
CP_FILENAME_FAILURE:
SCF
RET

;@ROUTINE IN A OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_FILENAME_CHAR:
CP   '!'
RET  C
CP   $7F
JR   NC,CP_FILENAME_CHAR_BAD
CP   '*'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '-'
JR   C,CP_FILENAME_CHAR_BAD
CP   '/'
JR   Z,CP_FILENAME_CHAR_BAD
CP   ':'
JR   C,CP_FILENAME_CHAR_HIGH
CP   '@'
JR   C,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_HIGH:
CP   '['
JR   C,CP_FILENAME_CHAR_OK
CP   '^'
JR   C,CP_FILENAME_CHAR_BAD
CP   '_'
JR   Z,CP_FILENAME_CHAR_BAD
CP_FILENAME_CHAR_OK:
OR   A
RET
CP_FILENAME_CHAR_BAD:
SCF
RET

;@ROUTINE IN DE,HL OUT A,ZERO CLOBBERS B,DE,HL,CARRY,SIGN,PARITY,HALFCARRY
CP_NAMES_EQUAL:
LD   B,12
CP_NAMES_EQUAL_BYTE:
LD   A,(DE)
CP   (HL)
RET  NZ
INC  DE
INC  HL
DJNZ CP_NAMES_EQUAL_BYTE
XOR  A
RET
CP_COMMAND_CODE_END:

CP_SOURCE_CODE_START:
; A trailing @ selects a source list containing one current-drive CP/M 8.3
; filename per logical line. The ordinary zero- and two-argument paths retain
; one source part. All source files are opened and measured before Atom begins.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
CP_PREPARE_SOURCE:
LD   A,(CP_ACTIVE_PART)
INC  A
JR   Z,CP_LOAD_PLAN
CALL CP_SCAN_SOURCE
JP   C,CP_SELECTED_SOURCE_FAILED
LD   DE,CP_PART_DESCRIPTORS
JP   CP_STORE_DESCRIPTOR

; Append one native five-byte part descriptor and update the build count.
;@ROUTINE IN A,DE,HL OUT A,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_STORE_DESCRIPTOR:
LD   (DE),A
INC  A
LD   (CP_DESCRIPTOR),A
INC  DE
EX   DE,HL
XOR  A
LD   (HL),A
INC  HL
LD   (HL),A
INC  HL
LD   (HL),E
INC  HL
LD   (HL),D
INC  HL
RET

; Parse and preflight the complete list into the native driver's bounded
; five-byte descriptor array. Source names are parsed again during assembly;
; CP/M's single-tasking disk contract keeps the preflighted files stable.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,IX,ZERO,SIGN,PARITY,HALFCARRY
CP_LOAD_PLAN:
LD   HL,CP_INPUT_FCB
LD   DE,CP_PLAN_FCB
LD   BC,12
LDIR
CALL CP_REWIND_PLAN_WITH_TAIL
JR   C,CP_PLAN_READ_FAILED
LD   IX,CP_PART_DESCRIPTORS
LD   (CP_DESCRIPTOR),A
CP_PLAN_PART_LOOP:
CALL CP_PLAN_BYTE_BODY
JR   NC,CP_PLAN_HAVE_BYTE
OR   A
JR   NZ,CP_PLAN_READ_FAILED
LD   A,(CP_DESCRIPTOR)
OR   A
JR   Z,CP_PLAN_INVALID
JR   CP_PLAN_READY
CP_PLAN_HAVE_BYTE:
LD   B,A
LD   A,(CP_DESCRIPTOR)
CP   255
JR   Z,CP_PLAN_INVALID
LD   A,B
CALL CP_PARSE_PLAN_NAME
JR   C,CP_PLAN_PARSE_FAILED
LD   (CP_PLAN_LINE_END),A
CALL CP_CHECK_SOURCE_CONFLICT
JR   C,CP_PLAN_CONFLICT
CALL CP_SCAN_SOURCE
JR   C,CP_SELECTED_SOURCE_FAILED
LD   A,(CP_DESCRIPTOR)
PUSH IX
POP  DE
CALL CP_STORE_DESCRIPTOR
PUSH HL
POP  IX
LD   A,(CP_PLAN_LINE_END)
OR   A
JR   Z,CP_PLAN_PART_LOOP
CP_PLAN_READY:
CALL CP_REWIND_PLAN
JR   C,CP_PLAN_READ_FAILED
RET
CP_PLAN_PARSE_FAILED:
CP   2
JR   Z,CP_PLAN_READ_FAILED
CP_PLAN_INVALID:
LD   DE,CP_INVALID_PLAN_TEXT
CP_PLAN_CONFLICT:
CP_SOURCE_FAILURE_TEXT:
CALL CP_PRINT
SCF
RET
CP_PLAN_READ_FAILED:
LD   HL,CP_PLAN_FCB
JR   CP_FILE_READ_FAILED
CP_SELECTED_SOURCE_FAILED:
LD   HL,CP_INPUT_FCB
CP_FILE_READ_FAILED:
PUSH HL
LD   DE,CP_NEWLINE_TEXT
CALL CP_PRINT
POP  HL
CALL CP_PRINT_NAME
LD   DE,CP_READ_FAILED_TEXT
JR   CP_SOURCE_FAILURE_TEXT

; Preserve the plan name while resetting its sequential-read fields.
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_REWIND_PLAN:
LD   DE,CP_PLAN_FCB+12
;@ROUTINE IN DE OUT A,CARRY CLOBBERS BC,DE,HL,IX,IY,ZERO,SIGN,PARITY,HALFCARRY
CP_REWIND_PLAN_WITH_TAIL:
CALL CP_CLEAR_FCB_TAIL
LD   DE,CP_PLAN_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
SCF
RET  Z
XOR  A
LD   (CP_PLAN_REMAINING),A
RET

; Return one plan byte. Carry with A=0 is text or physical EOF; carry with A=2
; is a disk error. Plan bytes use a cache separate from source bytes.
;@ROUTINE OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
CP_PLAN_BYTE:
PUSH BC
PUSH DE
PUSH HL
CALL CP_PLAN_BYTE_BODY
POP  HL
POP  DE
POP  BC
RET
;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_PLAN_BYTE_BODY:
LD   A,(CP_PLAN_REMAINING)
OR   A
JR   NZ,CP_PLAN_CACHE_BYTE
LD   DE,CP_PLAN_CACHE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_PLAN_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
OR   A
JR   Z,CP_PLAN_RECORD_READY
DEC  A
JR   Z,CP_PLAN_EOF
LD   A,2
SCF
RET
CP_PLAN_RECORD_READY:
LD   HL,CP_PLAN_CACHE
LD   (CP_PLAN_POINTER),HL
LD   A,128
LD   (CP_PLAN_REMAINING),A
CP_PLAN_CACHE_BYTE:
LD   HL,(CP_PLAN_POINTER)
LD   A,(HL)
INC  HL
LD   (CP_PLAN_POINTER),HL
LD   HL,CP_PLAN_REMAINING
DEC  (HL)
CP   $1A
JR   Z,CP_PLAN_EOF
OR   A
RET
CP_PLAN_EOF:
XOR  A
SCF
RET

; Parse one list line into the ordinary source FCB. Success returns A=0 after
; LF or CRLF and A=1 when text or physical EOF terminates the final filename.
; Carry returns A=1 for syntax and A=2 for disk I/O.
;@ROUTINE IN A OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_PARSE_PLAN_NAME:
PUSH AF
CALL CP_CLEAR_INPUT_FCB
POP  AF
LD   HL,CP_INPUT_FCB+1
LD   D,8
LD   C,0
CP_PLAN_NAME_BYTE:
CP   13
JR   Z,CP_PLAN_NAME_CR
CP   10
JR   Z,CP_PLAN_NAME_EOL
CP   '.'
JR   NZ,CP_PLAN_NAME_DATA
LD   A,D
CP   8
JR   NZ,CP_PLAN_NAME_INVALID
LD   A,C
OR   A
JR   Z,CP_PLAN_NAME_INVALID
LD   HL,CP_INPUT_FCB+9
LD   D,3
LD   C,0
JR   CP_PLAN_NAME_NEXT
CP_PLAN_NAME_DATA:
CP   'a'
JR   C,CP_PLAN_NAME_CHECK
CP   'z'+1
JR   NC,CP_PLAN_NAME_CHECK
AND  $DF
CP_PLAN_NAME_CHECK:
CALL CP_FILENAME_CHAR
JR   C,CP_PLAN_NAME_INVALID
INC  C
LD   B,A
LD   A,D
CP   C
JR   C,CP_PLAN_NAME_INVALID
LD   A,B
LD   (HL),A
INC  HL
CP_PLAN_NAME_NEXT:
CALL CP_PLAN_BYTE
JR   NC,CP_PLAN_NAME_BYTE
OR   A
JR   NZ,CP_PLAN_NAME_IO
LD   A,C
OR   A
JR   Z,CP_PLAN_NAME_INVALID
LD   A,1
RET
CP_PLAN_NAME_CR:
CALL CP_PLAN_BYTE
JR   C,CP_PLAN_NAME_INVALID_OR_IO
CP   10
JR   NZ,CP_PLAN_NAME_INVALID
CP_PLAN_NAME_EOL:
LD   A,C
OR   A
JR   Z,CP_PLAN_NAME_INVALID
XOR  A
RET
CP_PLAN_NAME_INVALID_OR_IO:
OR   A
JR   NZ,CP_PLAN_NAME_IO
CP_PLAN_NAME_INVALID:
LD   A,1
SCF
RET
CP_PLAN_NAME_IO:
LD   A,2
SCF
RET

;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_CLEAR_INPUT_FCB:
LD   DE,CP_INPUT_FCB
XOR  A
LD   (DE),A
INC  DE
LD   B,11
LD   A,' '
CALL CP_CLEAR_WORK_FCB
JP   CP_CLEAR_FCB_TAIL

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
CP_CHECK_SOURCE_CONFLICT:
LD   HL,CP_INPUT_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_NAMES_EQUAL
JR   Z,CP_PLAN_NAME_CONFLICT
XOR  A
RET
CP_PLAN_NAME_CONFLICT:
LD   DE,CP_NAME_CONFLICT_TEXT
SCF
RET

; Scan the selected input once to establish its 16-bit logical length. CP/M
; text EOF ($1A) terminates the bytes; an exact-record file may instead end at
; BDOS EOF. Cached random reads then reuse the active read-only FCB.
;@ROUTINE OUT A,CARRY,HL CLOBBERS BC,DE,ZERO,SIGN,PARITY,HALFCARRY
CP_SCAN_SOURCE:
LD   DE,CP_INPUT_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_IO_FAILURE
LD   DE,CP_SOURCE_CACHE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   HL,0
CP_SOURCE_RECORD:
PUSH HL
LD   DE,CP_INPUT_FCB
LD   C,CP_READ_FUNCTION
CALL CP_BDOS
POP  HL
OR   A
JR   Z,CP_SOURCE_SCAN
DEC  A
JR   NZ,CP_IO_FAILURE
CP_SOURCE_DONE:
LD   A,1
LD   (CP_SOURCE_CACHE_KEY),A
XOR  A
RET
CP_IO_FAILURE:
SCF
RET
CP_SOURCE_SCAN:
LD   B,128
LD   DE,CP_SOURCE_CACHE
CP_SOURCE_SCAN_BYTE:
LD   A,(DE)
CP   $1A
JR   Z,CP_SOURCE_DONE
INC  DE
INC  HL
LD   A,H
OR   L
JR   Z,CP_IO_FAILURE
DJNZ CP_SOURCE_SCAN_BYTE
JR   CP_SOURCE_RECORD

; Select the next preflighted source when the generic native driver advances
; to another part. The plan and source files cannot change during one CP/M
; transient, so the second parse and open repeat operations already proved.
;@ROUTINE IN A OUT A CLOBBERS DE,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SELECT_SOURCE:
PUSH BC
PUSH HL
PUSH AF
CALL CP_PLAN_BYTE_BODY
CALL CP_PARSE_PLAN_NAME
LD   DE,CP_INPUT_FCB
LD   C,CP_OPEN_FUNCTION
CALL CP_BDOS
LD   DE,CP_SOURCE_CACHE
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   A,1
LD   (CP_SOURCE_CACHE_KEY),A
POP  AF
LD   (CP_ACTIVE_PART),A
POP  HL
POP  BC
RET

; Read one logical source byte through a 128-byte random-record cache. The
; pre-scan proves every requested record exists for the life of this transient.
;@ROUTINE IN A,HL OUT A,CARRY,ZERO CLOBBERS DE,HL,SIGN,PARITY,HALFCARRY
CP_SOURCE_READ_BYTE:
CP   0
JR   Z,CP_SOURCE_READY
CALL CP_SELECT_SOURCE
CP_SOURCE_READY:
PUSH BC
PUSH HL
LD   A,L
AND  $80
LD   E,A
LD   D,H
LD   HL,(CP_SOURCE_CACHE_KEY)
OR   A
SBC  HL,DE
JR   NZ,CP_SOURCE_CACHE_MISS
POP  HL
POP  BC
JP   CP_SOURCE_CACHE_BYTE
CP_SOURCE_CACHE_MISS:
LD   (CP_SOURCE_CACHE_KEY),DE
RLC  E
LD   A,D
ADD  A,A
OR   E
LD   (CP_INPUT_FCB+33),A
LD   A,D
RLCA
AND  1
LD   (CP_INPUT_FCB+34),A
LD   DE,CP_INPUT_FCB
LD   C,CP_RANDOM_READ_FUNCTION
CALL CP_BDOS
POP  HL
POP  BC
;@ROUTINE IN HL OUT A,CARRY,ZERO CLOBBERS HL,SIGN,PARITY,HALFCARRY
CP_SOURCE_CACHE_BYTE:
RES  7,L
LD   H,CP_SOURCE_CACHE/256
LD   A,(HL)
OR   A
RET
CP_SOURCE_CODE_END:

; Nucleus-model sink entries linked directly in place of the host stubs.
CP_OUTPUT_CODE_START:
HS_SCBEG:
;@ROUTINE IN IX OUT A,CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
HS_BEG:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

;@ROUTINE IN A,C,HL OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_IB:
HS_PB:
PUSH AF
LD   DE,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,DE
POP  AF
LD   (HL),A
XOR  A
RET

;@ROUTINE IN C,DE,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_PW:
EX   DE,HL
LD   BC,CP_OUTPUT_START-CP_TARGET_START
ADD  HL,BC
LD   (HL),E
INC  HL
LD   (HL),D
XOR  A
RET

;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_CMT:
LD   DE,CP_TARGET_START
OR   A
SBC  HL,DE
LD   (CP_OUTPUT_REMAINING),HL
LD   HL,CP_OUTPUT_START
LD   (CP_OUTPUT_CURSOR),HL
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_MAKE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
LD   A,1
LD   (CP_OUTPUT_OPEN),A
CP_WRITE_LOOP:
LD   HL,(CP_OUTPUT_REMAINING)
LD   A,H
OR   L
JR   Z,CP_WRITE_CLOSE
LD   DE,(CP_OUTPUT_CURSOR)
LD   C,CP_DMA_FUNCTION
CALL CP_BDOS
LD   DE,CP_WORK_FCB
LD   C,CP_WRITE_FUNCTION
CALL CP_BDOS
OR   A
JP   NZ,CP_COMMIT_FAILURE
LD   HL,(CP_OUTPUT_CURSOR)
LD   DE,128
ADD  HL,DE
LD   (CP_OUTPUT_CURSOR),HL
LD   HL,(CP_OUTPUT_REMAINING)
LD   DE,128
OR   A
SBC  HL,DE
JR   NC,CP_WRITE_MORE
LD   HL,0
CP_WRITE_MORE:
LD   (CP_OUTPUT_REMAINING),HL
JR   CP_WRITE_LOOP
CP_WRITE_CLOSE:
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
XOR  A
LD   (CP_OUTPUT_OPEN),A
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JR   Z,CP_NO_BACKUP
LD   A,1
LD   (CP_BACKED_UP),A
CP_NO_BACKUP:
CALL CP_SET_TEMP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
INC  A
JP   Z,CP_COMMIT_FAILURE
CALL CP_SET_BACKUP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
XOR  A
LD   (CP_BACKED_UP),A
RET
CP_COMMIT_FAILURE:
LD   A,1
SCF
RET

;@ROUTINE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
HS_ABORT:
LD   A,(CP_OUTPUT_OPEN)
OR   A
JR   Z,CP_ABORT_DELETE
LD   DE,CP_WORK_FCB
LD   C,CP_CLOSE_FUNCTION
CALL CP_BDOS
CP_ABORT_DELETE:
CALL CP_SET_TEMP_FCB
LD   DE,CP_WORK_FCB
LD   C,CP_DELETE_FUNCTION
CALL CP_BDOS
LD   A,(CP_BACKED_UP)
OR   A
JR   Z,CP_ABORT_DONE
CALL CP_SET_BACKUP_FCB
LD   HL,CP_WORK_FCB
LD   DE,CP_OUTPUT_NAME
CALL CP_BUILD_RENAME
LD   DE,CP_RENAME_FCB
LD   C,CP_RENAME_FUNCTION
CALL CP_BDOS
CP_ABORT_DONE:
XOR  A
LD   (CP_OUTPUT_OPEN),A
LD   (CP_BACKED_UP),A
RET

; Rebuild the single ordinary output FCB before each new BDOS operation phase.
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_COPY_OUTPUT_FCB:
LD   HL,CP_OUTPUT_NAME
LD   DE,CP_WORK_FCB
LD   BC,12
LDIR
;@ROUTINE IN DE OUT A,B,DE,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_CLEAR_FCB_TAIL:
XOR  A
LD   B,24
;@ROUTINE IN A,B,DE OUT B,DE
CP_CLEAR_WORK_FCB:
LD   (DE),A
INC  DE
DJNZ CP_CLEAR_WORK_FCB
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_TEMP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$2424
LD   (CP_WORK_FCB+9),HL
LD   A,'$'
LD   (CP_WORK_FCB+11),A
RET
;@ROUTINE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_SET_BACKUP_FCB:
CALL CP_COPY_OUTPUT_FCB
LD   HL,$4142
LD   (CP_WORK_FCB+9),HL
LD   A,'K'
LD   (CP_WORK_FCB+11),A
RET

; Construct a CP/M rename FCB in the input FCB's dead storage. HL addresses
; the old 12-byte name and DE the new 12-byte name.
;@ROUTINE IN DE,HL CLOBBERS A,BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_BUILD_RENAME:
PUSH HL
PUSH DE
LD   DE,CP_RENAME_FCB
XOR  A
LD   B,36
CALL CP_CLEAR_WORK_FCB
POP  DE
POP  HL
PUSH DE
LD   DE,CP_RENAME_FCB
LD   BC,12
LDIR
POP  HL
LD   DE,CP_RENAME_FCB+16
LD   BC,12
LDIR
RET

CP_OUTPUT_CODE_END:
;@ROUTINE IN DE OUT A CLOBBERS BC,DE,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT:
LD   C,CP_PRINT_FUNCTION
JP   CP_BDOS
;@ROUTINE IN HL OUT A CLOBBERS B,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NAME:
INC  HL
LD   B,8
CP_PRINT_NAME_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_NAME_BYTE
LD   A,(HL)
CP   ' '
RET  Z
LD   A,'.'
CALL CP_PUTC
LD   B,3
CP_PRINT_TYPE_BYTE:
LD   A,(HL)
INC  HL
CP   ' '
CALL NZ,CP_PUTC
DJNZ CP_PRINT_TYPE_BYTE
RET
;@ROUTINE IN A OUT A CLOBBERS CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PUTC:
PUSH BC
PUSH DE
PUSH HL
LD   E,A
LD   C,2
CALL CP_BDOS
POP  HL
POP  DE
POP  BC
RET
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_HEX:
PUSH AF
RRCA
RRCA
RRCA
RRCA
CALL CP_PRINT_NIBBLE
POP  AF
;@ROUTINE IN A OUT A CLOBBERS BC,HL,CARRY,ZERO,SIGN,PARITY,HALFCARRY
CP_PRINT_NIBBLE:
AND  $0F
ADD  A,'0'
CP   '9'+1
JR   C,CP_PUTC
ADD  A,7
JR   CP_PUTC

CP_ADAPTER_CODE_END:
CP_ADAPTER_WORKSPACE1_START:
CP_DESCRIPTOR:
DB   1
DW   CP_PART_DESCRIPTORS
DW   CP_SYMBOL_START,CP_SYMBOL_END
DW   CP_PENDING_START,CP_PENDING_END
DW   CP_TARGET_START,CP_TARGET_CAPACITY

CP_RENAME_FCB:
CP_INPUT_FCB:
DB 0,'I','N','P','U','T',' ',' ',' ','A','S','M'
DS 24
CP_WORK_FCB:
DB 0,'O','U','T','P','U','T',' ',' ','$','$','$'
DS 24
CP_OUTPUT_NAME:
DB 0,'O','U','T','P','U','T',' ',' ','C','O','M'
CP_ADAPTER_WORKSPACE1_END:

CP_ADAPTER_IMMUTABLE_START:
CP_WRITTEN_TEXT: DB ' ','w','r','i','t','t','e','n',13,10,'$'
CP_READ_FAILED_TEXT: DB ' ','r','e','a','d',' ','f','a','i','l','e','d',13,10,'$'
CP_ASSEMBLY_TEXT: DB 13,10,'A','t','o','m',' ','e','r','r','o','r',' ','$'
CP_NEWLINE_TEXT: DB 13,10,'$'
CP_USAGE_TEXT: DB 13,10,'U','s','a','g','e',':',' ','A','T','O','M',' ','[','S','O','U','R','C','E',' ','O','U','T','P','U','T','.','C','O','M',' ','[','@',']',']',13,10,'$'
CP_SOURCE_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','s','o','u','r','c','e',' ','n','a','m','e',13,10,'$'
CP_OUTPUT_NAME_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','o','u','t','p','u','t',' ','n','a','m','e',13,10,'$'
CP_NAME_CONFLICT_TEXT: DB 13,10,'S','o','u','r','c','e','/','o','u','t','p','u','t',' ','c','o','n','f','l','i','c','t',13,10,'$'
CP_AUXILIARY_EXISTS_TEXT: DB 13,10,'T','e','m','p','/','b','a','c','k','u','p',' ','f','i','l','e',' ','e','x','i','s','t','s',13,10,'$'
CP_INVALID_PLAN_TEXT: DB 13,10,'I','n','v','a','l','i','d',' ','p','l','a','n',13,10,'$'
CP_COM_EXTENSION: DB 'C','O','M'
CP_ADAPTER_IMMUTABLE_END:
CP_ADAPTER_WORKSPACE2_START:
CP_SAVED_SP: DW 0
CP_OUTPUT_CURSOR: DW 0
CP_SOURCE_CACHE_KEY EQU CP_OUTPUT_CURSOR
CP_OUTPUT_REMAINING: DW 0
CP_OUTPUT_OPEN: DB 0
CP_BACKED_UP: DB 0
CP_ADAPTER_WORKSPACE2_END:
HS_SCEND:
HS_REND:
CP_RESIDENT_END:
