export function cliUsage(): string {
  return [
    'azm [options] <entry.asm|entry.z80>',
    '',
    'Options:',
    '  -o, --output <file>   Primary output path (must match --type extension)',
    '  -t, --type <type>     Primary output type: hex|bin (default: hex)',
    '      --nobin           Suppress .bin',
    '      --nohex           Suppress .hex',
    '      --nod8m           Suppress .d8.json',
    '      --asm80           Emit lowered source (.z80)',
    '      --lst             Emit asm80-style listing (.lst)',
    '      --register-contracts <m> Register contracts mode: off|audit|warn|error|strict',
    '      --rc <m>           Register contracts mode alias for --register-contracts',
    '      --reg-report       Emit register contracts report artifact',
    '      --reg-report-format <f> Report format: text|json (default: text)',
    '      --reg-baseline <f> Compare against a JSON register contracts report',
    '      --reg-ratchet      Fail if register contract findings increase',
    '      --require-expectout Fail on unacknowledged caller output dependencies',
    '      --reg-interface     Emit inferred register contracts interface (.asmi)',
    '      --reg-infer         Emit inferred register contracts review artifact',
    '      --reg-infer-format <f> Inference format: json|markdown (default: json)',
    '      --contracts        Rewrite source with inferred register contracts',
    '      --fix              Enable contract rewrite and conservative fixes',
    '      --accept-out <x>   Accept register contracts output candidates',
    '      --interface <file>  Load .asmi contract file',
    '      --reg-profile <p>  Register contracts profile (currently mon3)',
    '      --source-root <d> Normalize D8 source paths relative to this directory',
    '      --symbol-case <m> Symbol lookup mode: strict|insensitive (default: strict)',
    '      --case-style <m>  Case-style lint mode: off|upper|lower|consistent',
    '      --aliases <file>  Load project directive alias JSON (repeatable)',
    '  -I, --include <dir>   Add include search path (repeatable)',
    '  -V, --version         Print version',
    '  -h, --help            Show help',
    '',
    'Notes:',
    '  - <entry.asm|entry.z80> must be the last argument (assembler-style).',
    '  - Output artifacts are written using the primary output stem with standard suffixes.',
    '',
  ].join('\n');
}
